import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

// Additional missing municipalities with OFFICIAL postal codes
const additionalMunicipalities: { name: string; canton: string; postalCode: string }[] = [
  // BERN (BE) - additional municipalities
  { name: 'Aarberg', canton: 'BE', postalCode: '3270' },
  { name: 'Aarwangen', canton: 'BE', postalCode: '4912' },
  { name: 'Adelboden', canton: 'BE', postalCode: '3700' },
  { name: 'Aefligen', canton: 'BE', postalCode: '3474' },
  { name: 'Aegerten', canton: 'BE', postalCode: '2558' },
  { name: 'Aeschi bei Spiez', canton: 'BE', postalCode: '3704' },
  { name: 'Affoltern im Emmental', canton: 'BE', postalCode: '3416' },
  { name: 'Alchenstorf', canton: 'BE', postalCode: '3323' },
  { name: 'Allmendingen', canton: 'BE', postalCode: '3116' },
  { name: 'Arni', canton: 'BE', postalCode: '3506' },
  { name: 'Attiswil', canton: 'BE', postalCode: '4536' },
  { name: 'Auswil', canton: 'BE', postalCode: '4944' },
  { name: 'Bärau', canton: 'BE', postalCode: '3552' },
  { name: 'Belpberg', canton: 'BE', postalCode: '3124' },
  { name: 'Bibern', canton: 'BE', postalCode: '2517' },
  { name: 'Bollodingen', canton: 'BE', postalCode: '3362' },
  { name: 'Brienzwiler', canton: 'BE', postalCode: '3856' },
  { name: 'Büren zum Hof', canton: 'BE', postalCode: '3304' },
  { name: 'Busswil bei Büren', canton: 'BE', postalCode: '3293' },
  { name: 'Büttiken', canton: 'BE', postalCode: '3274' },
  { name: 'Corgémont', canton: 'BE', postalCode: '2607' },
  { name: 'Court', canton: 'BE', postalCode: '2853' },
  { name: 'Courtelary', canton: 'BE', postalCode: '2608' },
  { name: 'Crémines', canton: 'BE', postalCode: '2714' },
  { name: 'Diemerswil', canton: 'BE', postalCode: '3053' },
  { name: 'Eggiwil', canton: 'BE', postalCode: '3537' },
  { name: 'Erlach', canton: 'BE', postalCode: '3235' },
  { name: 'Eriz', canton: 'BE', postalCode: '3624' },
  { name: 'Eschi', canton: 'BE', postalCode: '3618' },
  { name: 'Ersigen', canton: 'BE', postalCode: '3423' },
  { name: 'Eriswil', canton: 'BE', postalCode: '4952' },
  { name: 'Evilard', canton: 'BE', postalCode: '4125' },
  { name: 'Ferenbalm', canton: 'BE', postalCode: '3203' },
  { name: 'Frauenkappelen', canton: 'BE', postalCode: '3205' },
  { name: 'Gerzensee', canton: 'BE', postalCode: '3115' },
  { name: 'Gondiswil', canton: 'BE', postalCode: '4955' },
  { name: 'Grandval', canton: 'BE', postalCode: '2715' },
  { name: 'Guggisberg', canton: 'BE', postalCode: '3158' },
  { name: 'Gurzelen', canton: 'BE', postalCode: '3662' },
  { name: 'Hagneck', canton: 'BE', postalCode: '2557' },
  { name: 'Hasle bei Burgdorf', canton: 'BE', postalCode: '3415' },
  { name: 'Heimenhausen', canton: 'BE', postalCode: '3473' },
  { name: 'Hellsau', canton: 'BE', postalCode: '3423' },
  { name: 'Herbetswil', canton: 'BE', postalCode: '4417' },
  { name: 'Herbligen', canton: 'BE', postalCode: '3672' },
  { name: 'Hermiswil', canton: 'BE', postalCode: '3367' },
  { name: 'Hofen', canton: 'BE', postalCode: '4228' },
  { name: 'Hofstetten bei Brienz', canton: 'BE', postalCode: '3858' },
  { name: 'Horrenbach-Buchen', canton: 'BE', postalCode: '3626' },
  { name: 'Iffwil', canton: 'BE', postalCode: '3306' },
  { name: 'Inkwil', canton: 'BE', postalCode: '4535' },
  { name: 'Iseltwald', canton: 'BE', postalCode: '3807' },
  { name: 'Jaberg', canton: 'BE', postalCode: '3126' },
  { name: 'Jens', canton: 'BE', postalCode: '2564' },
  { name: 'Kallnach', canton: 'BE', postalCode: '3283' },
  { name: 'Kandergrund', canton: 'BE', postalCode: '3717' },
  { name: 'Kandersteg', canton: 'BE', postalCode: '3718' },
  { name: 'Kappelen', canton: 'BE', postalCode: '3272' },
  { name: 'Kernenried', canton: 'BE', postalCode: '3308' },
  { name: 'Kiesen', canton: 'BE', postalCode: '3622' },
  { name: 'Kirchlindach', canton: 'BE', postalCode: '3035' },
  { name: 'Krattigen', canton: 'BE', postalCode: '3707' },
  { name: 'Kriechenwil', canton: 'BE', postalCode: '3034' },
  { name: 'La Heutte', canton: 'BE', postalCode: '2606' },
  { name: 'La Neuveville', canton: 'BE', postalCode: '2520' },
  { name: 'Lamboing', canton: 'BE', postalCode: '2512' },
  { name: 'Landiswil', canton: 'BE', postalCode: '3535' },
  { name: 'Lengnau', canton: 'BE', postalCode: '3273' },
  { name: 'Lenk', canton: 'BE', postalCode: '3775' },
  { name: 'Linden', canton: 'BE', postalCode: '3538' },
  { name: 'Lobsigen', canton: 'BE', postalCode: '3270' },
  { name: 'Lützelflüh', canton: 'BE', postalCode: '3435' },
  { name: 'Madiswil', canton: 'BE', postalCode: '4934' },
  { name: 'Mattstetten', canton: 'BE', postalCode: '3326' },
  { name: 'Meikirch', canton: 'BE', postalCode: '3038' },
  { name: 'Melchnau', canton: 'BE', postalCode: '4935' },
  { name: 'Merzligen', canton: 'BE', postalCode: '3285' },
  { name: 'Mirchel', canton: 'BE', postalCode: '3534' },
  { name: 'Moosseedorf', canton: 'BE', postalCode: '3312' },
  { name: 'Morens', canton: 'BE', postalCode: '3285' },
  { name: 'Mötschwil', canton: 'BE', postalCode: '3423' },
  { name: 'Mühleberg', canton: 'BE', postalCode: '3204' },
  { name: 'Mühlethurnen', canton: 'BE', postalCode: '3127' },
  { name: 'Müntschemier', canton: 'BE', postalCode: '3226' },
  { name: 'Niederbipp', canton: 'BE', postalCode: '4702' },
  { name: 'Niedermuhlern', canton: 'BE', postalCode: '3094' },
  { name: 'Niederösch', canton: 'BE', postalCode: '3424' },
  { name: 'Noflen', canton: 'BE', postalCode: '3205' },
  { name: 'Oberbipp', canton: 'BE', postalCode: '4538' },
  { name: 'Oberhünigen', canton: 'BE', postalCode: '3672' },
  { name: 'Oberburg', canton: 'BE', postalCode: '3636' },
  { name: 'Oberlangenegg', canton: 'BE', postalCode: '3618' },
  { name: 'Oberösch', canton: 'BE', postalCode: '3424' },
  { name: 'Oberwil bei Büren', canton: 'BE', postalCode: '3294' },
  { name: 'Oberwil im Simmental', canton: 'BE', postalCode: '3765' },
  { name: 'Ochlenberg', canton: 'BE', postalCode: '3374' },
  { name: 'Oppligen', canton: 'BE', postalCode: '3524' },
  { name: 'Orpund', canton: 'BE', postalCode: '2555' },
  { name: 'Pieterlen', canton: 'BE', postalCode: '2542' },
  { name: 'Plagne', canton: 'BE', postalCode: '2605' },
  { name: 'Prêles', canton: 'BE', postalCode: '2515' },
  { name: 'Péry', canton: 'BE', postalCode: '2606' },
  { name: 'Riggisberg', canton: 'BE', postalCode: '3132' },
  { name: 'Rohrbach', canton: 'BE', postalCode: '4938' },
  { name: 'Rohrbachgraben', canton: 'BE', postalCode: '4938' },
  { name: 'Rosshäusern', canton: 'BE', postalCode: '3205' },
  { name: 'Rüderswil', canton: 'BE', postalCode: '3536' },
  { name: 'Rüegsau', canton: 'BE', postalCode: '3417' },
  { name: 'Rüeggisberg', canton: 'BE', postalCode: '3096' },
  { name: 'Rumendingen', canton: 'BE', postalCode: '3472' },
  { name: 'Ruppoldsried', canton: 'BE', postalCode: '3293' },
  { name: 'Rüti bei Büren', canton: 'BE', postalCode: '3298' },
  { name: 'Saanen', canton: 'BE', postalCode: '3792' },
  { name: 'Saanenmöser', canton: 'BE', postalCode: '3778' },
  { name: 'Saint-Imier', canton: 'BE', postalCode: '2610' },
  { name: 'Schangnau', canton: 'BE', postalCode: '6197' },
  { name: 'Sankt Stephan', canton: 'BE', postalCode: '3772' },
  { name: 'Scheunen', canton: 'BE', postalCode: '3315' },
  { name: 'Schlosswil', canton: 'BE', postalCode: '3086' },
  { name: 'Schüpfen', canton: 'BE', postalCode: '3054' },
  { name: 'Schwadernau', canton: 'BE', postalCode: '3275' },
  { name: 'Seedorf', canton: 'BE', postalCode: '3087' },
  { name: 'Signau', canton: 'BE', postalCode: '3534' },
  { name: 'Siselen', canton: 'BE', postalCode: '3225' },
  { name: 'Sonceboz-Sombeval', canton: 'BE', postalCode: '2605' },
  { name: 'Soriswil', canton: 'BE', postalCode: '3622' },
  { name: 'Stalden im Emmental', canton: 'BE', postalCode: '3561' },
  { name: 'Stettlen', canton: 'BE', postalCode: '3072' },
  { name: 'Studen', canton: 'BE', postalCode: '2557' },
  { name: 'Sumiswald', canton: 'BE', postalCode: '3454' },
  { name: 'Tavannes', canton: 'BE', postalCode: '2710' },
  { name: 'Thörigen', canton: 'BE', postalCode: '3366' },
  { name: 'Thunstetten', canton: 'BE', postalCode: '4922' },
  { name: 'Tramelan', canton: 'BE', postalCode: '2720' },
  { name: 'Tüscherz-Alfermée', canton: 'BE', postalCode: '2525' },
  { name: 'Twann', canton: 'BE', postalCode: '2513' },
  { name: 'Ursenbach', canton: 'BE', postalCode: '3453' },
  { name: 'Vahlern', canton: 'BE', postalCode: '3618' },
  { name: 'Vinelz', canton: 'BE', postalCode: '2523' },
  { name: 'Wachseldorn', canton: 'BE', postalCode: '3618' },
  { name: 'Wangen an der Aare', canton: 'BE', postalCode: '3383' },
  { name: 'Wangenried', canton: 'BE', postalCode: '4577' },
  { name: 'Wengen', canton: 'BE', postalCode: '3823' },
  { name: 'Wengi', canton: 'BE', postalCode: '3295' },
  { name: 'Wichtrach', canton: 'BE', postalCode: '3114' },
  { name: 'Wiedlisbach', canton: 'BE', postalCode: '4537' },
  { name: 'Wileroltigen', canton: 'BE', postalCode: '3205' },
  { name: 'Willadingen', canton: 'BE', postalCode: '3315' },
  { name: 'Wiler bei Ursenbach', canton: 'BE', postalCode: '3452' },
  { name: 'Wynau', canton: 'BE', postalCode: '4924' },
  { name: 'Wynigen', canton: 'BE', postalCode: '3473' },
  { name: 'Zollbrück', canton: 'BE', postalCode: '3422' },
  { name: 'Zweisimmen', canton: 'BE', postalCode: '3770' },
  { name: 'Twann-Tüscherz', canton: 'BE', postalCode: '2513' },
  { name: 'Mont-Tramelan', canton: 'BE', postalCode: '2720' },
  { name: 'Reconvilier', canton: 'BE', postalCode: '2732' },
  { name: 'Büre', canton: 'BE', postalCode: '3297' },
  { name: 'Gaicht', canton: 'BE', postalCode: '3704' },
  { name: 'Schwanden', canton: 'BE', postalCode: '3766' },
  { name: 'Gsteigwiler', canton: 'BE', postalCode: '3806' },
  { name: 'Gündlischwand', canton: 'BE', postalCode: '3806' },
  { name: 'Lütschental', canton: 'BE', postalCode: '3823' },
  { name: 'Saxeten', canton: 'BE', postalCode: '3806' },
  { name: 'Därligen', canton: 'BE', postalCode: '3705' },
  { name: 'Leissigen', canton: 'BE', postalCode: '3705' },
  { name: 'Aeschi', canton: 'BE', postalCode: '3704' },
  { name: 'Bremgarten bei Bern', canton: 'BE', postalCode: '3047' },
  { name: 'Kirchenthurnen', canton: 'BE', postalCode: '3128' },
  { name: 'Rüti bei Riggisberg', canton: 'BE', postalCode: '3133' },
  { name: 'Kaufdorf', canton: 'BE', postalCode: '3126' },
  { name: 'Lohnstorf', canton: 'BE', postalCode: '3127' },
  { name: 'Rümligen', canton: 'BE', postalCode: '3127' },
  { name: 'Albligen', canton: 'BE', postalCode: '3151' },
  { name: 'Bolligen', canton: 'BE', postalCode: '3065' },
  { name: 'Vechigen', canton: 'BE', postalCode: '3076' },
  { name: 'Seftigen', canton: 'BE', postalCode: '3087' },
  { name: 'Bätterkinden', canton: 'BE', postalCode: '3315' },
  { name: 'Oberdiessbach', canton: 'BE', postalCode: '3672' },
  { name: 'Belp', canton: 'BE', postalCode: '3123' },
  { name: 'Münsingen', canton: 'BE', postalCode: '3110' },
  { name: 'Ittigen', canton: 'BE', postalCode: '3063' },
  { name: 'Ostermundigen', canton: 'BE', postalCode: '3072' },
  { name: 'Worb', canton: 'BE', postalCode: '3076' },
  { name: 'Biel/Bienne', canton: 'BE', postalCode: '2500' },
  { name: 'Bern', canton: 'BE', postalCode: '3000' },
  { name: 'Thun', canton: 'BE', postalCode: '3600' },
  { name: 'Burgdorf', canton: 'BE', postalCode: '3400' },
  { name: 'Langenthal', canton: 'BE', postalCode: '4900' },
  { name: 'Brienz', canton: 'BE', postalCode: '3855' },
  { name: 'Meiringen', canton: 'BE', postalCode: '3860' },
  { name: 'Interlaken', canton: 'BE', postalCode: '3800' },
  { name: 'Spiez', canton: 'BE', postalCode: '3700' },
  { name: 'Steffisburg', canton: 'BE', postalCode: '3612' },
  { name: 'Muri bei Bern', canton: 'BE', postalCode: '3074' },
  { name: 'Lyss', canton: 'BE', postalCode: '3250' },
  { name: 'Moutier', canton: 'BE', postalCode: '2740' },
  { name: 'Nidau', canton: 'BE', postalCode: '2560' },
  { name: 'Konolfingen', canton: 'BE', postalCode: '3510' },
  { name: 'Langnau im Emmental', canton: 'BE', postalCode: '3550' },
  { name: 'Herzogenbuchsee', canton: 'BE', postalCode: '3360' },
  { name: 'Huttwil', canton: 'BE', postalCode: '4950' },
  { name: 'Worb', canton: 'BE', postalCode: '3076' },

  // VAUD (VD) - additional municipalities
  { name: 'Aclens', canton: 'VD', postalCode: '1125' },
  { name: 'Allaman', canton: 'VD', postalCode: '1163' },
  { name: 'Apples', canton: 'VD', postalCode: '1143' },
  { name: 'Assens', canton: 'VD', postalCode: '1041' },
  { name: 'Aubonne', canton: 'VD', postalCode: '1170' },
  { name: 'Avenches', canton: 'VD', postalCode: '1580' },
  { name: 'Ballens', canton: 'VD', postalCode: '1143' },
  { name: 'Ballaigues', canton: 'VD', postalCode: '1338' },
  { name: 'Bassins', canton: 'VD', postalCode: '1149' },
  { name: 'Baulmes', canton: 'VD', postalCode: '1443' },
  { name: 'Bavois', canton: 'VD', postalCode: '1372' },
  { name: 'Begnins', canton: 'VD', postalCode: '1268' },
  { name: 'Belmont-sur-Lausanne', canton: 'VD', postalCode: '1092' },
  { name: 'Berolle', canton: 'VD', postalCode: '1143' },
  { name: 'Bière', canton: 'VD', postalCode: '1145' },
  { name: 'Blonay', canton: 'VD', postalCode: '1807' },
  { name: 'Bogis-Bossey', canton: 'VD', postalCode: '1273' },
  { name: 'Bofflens', canton: 'VD', postalCode: '1318' },
  { name: 'Bonvillars', canton: 'VD', postalCode: '1426' },
  { name: 'Borex', canton: 'VD', postalCode: '1279' },
  { name: 'Boussens', canton: 'VD', postalCode: '1035' },
  { name: 'Bremblens', canton: 'VD', postalCode: '1040' },
  { name: 'Bretigny', canton: 'VD', postalCode: '1453' },
  { name: 'Buchillon', canton: 'VD', postalCode: '1169' },
  { name: 'Bursinel', canton: 'VD', postalCode: '1185' },
  { name: 'Bursins', canton: 'VD', postalCode: '1185' },
  { name: 'Bussy', canton: 'VD', postalCode: '1036' },
  { name: 'Chaméry', canton: 'VD', postalCode: '1067' },
  { name: 'Champigny', canton: 'VD', postalCode: '1037' },
  { name: 'Chardonne', canton: 'VD', postalCode: '1807' },
  { name: 'Chavannes-le-Chêne', canton: 'VD', postalCode: '1405' },
  { name: 'Chavannes-près-Renens', canton: 'VD', postalCode: '1022' },
  { name: 'Chavannes-sur-Morges', canton: 'VD', postalCode: '1108' },
  { name: 'Chavornay', canton: 'VD', postalCode: '1373' },
  { name: 'Chessel', canton: 'VD', postalCode: '1845' },
  { name: 'Chevroux', canton: 'VD', postalCode: '1534' },
  { name: 'Chexbres', canton: 'VD', postalCode: '1071' },
  { name: 'Clarmont', canton: 'VD', postalCode: '1112' },
  { name: 'Concise', canton: 'VD', postalCode: '1429' },
  { name: 'Corcelles-Chavornay', canton: 'VD', postalCode: '1373' },
  { name: 'Corcelles-le-Jorat', canton: 'VD', postalCode: '1054' },
  { name: 'Corcelles-près-Concise', canton: 'VD', postalCode: '1428' },
  { name: 'Cossonay', canton: 'VD', postalCode: '1304' },
  { name: 'Cottens', canton: 'VD', postalCode: '1113' },
  { name: 'Crassier', canton: 'VD', postalCode: '1262' },
  { name: 'Crissier', canton: 'VD', postalCode: '1023' },
  { name: 'Croy', canton: 'VD', postalCode: '1323' },
  { name: 'Cuarnens', canton: 'VD', postalCode: '1143' },
  { name: 'Cugy', canton: 'VD', postalCode: '1052' },
  { name: 'Denges', canton: 'VD', postalCode: '1027' },
  { name: 'Denens', canton: 'VD', postalCode: '1133' },
  { name: 'Dizy', canton: 'VD', postalCode: '1114' },
  { name: 'Dommartin', canton: 'VD', postalCode: '1053' },
  { name: 'Donneloye', canton: 'VD', postalCode: '1353' },
  { name: 'Duillier', canton: 'VD', postalCode: '1267' },
  { name: 'Dully', canton: 'VD', postalCode: '1185' },
  { name: 'Echallens', canton: 'VD', postalCode: '1040' },
  { name: 'Echandens', canton: 'VD', postalCode: '1026' },
  { name: 'Echichens', canton: 'VD', postalCode: '1123' },
  { name: 'Ecublens', canton: 'VD', postalCode: '1024' },
  { name: 'Eclépens', canton: 'VD', postalCode: '1315' },
  { name: 'Ecoteaux', canton: 'VD', postalCode: '1413' },
  { name: 'Egrenolles', canton: 'VD', postalCode: '1278' },
  { name: 'Epenex', canton: 'VD', postalCode: '1032' },
  { name: 'Epalinges', canton: 'VD', postalCode: '1062' },
  { name: 'Etoy', canton: 'VD', postalCode: '1164' },
  { name: 'Fechy', canton: 'VD', postalCode: '1187' },
  { name: 'Ferlens', canton: 'VD', postalCode: '1083' },
  { name: 'Font', canton: 'VD', postalCode: '1606' },
  { name: 'Fontanezier', canton: 'VD', postalCode: '1429' },
  { name: 'Forel', canton: 'VD', postalCode: '1098' },
  { name: 'Founex', canton: 'VD', postalCode: '1297' },
  { name: 'Francillon', canton: 'VD', postalCode: '1053' },
  { name: 'Genolier', canton: 'VD', postalCode: '1272' },
  { name: 'Giez', canton: 'VD', postalCode: '1423' },
  { name: 'Gilly', canton: 'VD', postalCode: '1182' },
  { name: 'Gimel', canton: 'VD', postalCode: '1188' },
  { name: 'Gingins', canton: 'VD', postalCode: '1274' },
  { name: 'Gollion', canton: 'VD', postalCode: '1124' },
  { name: 'Grandcour', canton: 'VD', postalCode: '1523' },
  { name: 'Grandvaux', canton: 'VD', postalCode: '1091' },
  { name: 'Granges', canton: 'VD', postalCode: '1422' },
  { name: 'Gryon', canton: 'VD', postalCode: '1882' },
  { name: 'Henniez', canton: 'VD', postalCode: '1533' },
  { name: 'Hermenches', canton: 'VD', postalCode: '1081' },
  { name: 'Jongny', canton: 'VD', postalCode: '1805' },
  { name: 'Jouxtens-Mézery', canton: 'VD', postalCode: '1008' },
  { name: 'L\'Abbaye', canton: 'VD', postalCode: '1344' },
  { name: 'L\'Isle', canton: 'VD', postalCode: '1145' },
  { name: 'La Chaux', canton: 'VD', postalCode: '1334' },
  { name: 'La Rippe', canton: 'VD', postalCode: '1273' },
  { name: 'La Sarraz', canton: 'VD', postalCode: '1315' },
  { name: 'La Tour-de-Peilz', canton: 'VD', postalCode: '1814' },
  { name: 'Lavigny', canton: 'VD', postalCode: '1175' },
  { name: 'Le Chenit', canton: 'VD', postalCode: '1342' },
  { name: 'Le Lieu', canton: 'VD', postalCode: '1346' },
  { name: 'Le Mont-Pèlerin', canton: 'VD', postalCode: '1083' },
  { name: 'Le Vaud', canton: 'VD', postalCode: '1186' },
  { name: 'Les Clées', canton: 'VD', postalCode: '1357' },
  { name: 'Lignerolle', canton: 'VD', postalCode: '1317' },
  { name: 'Lussy', canton: 'VD', postalCode: '1132' },
  { name: 'Lutry', canton: 'VD', postalCode: '1095' },
  { name: 'Maracon', canton: 'VD', postalCode: '1512' },
  { name: 'Marchissy', canton: 'VD', postalCode: '1189' },
  { name: 'Marnand', canton: 'VD', postalCode: '1433' },
  { name: 'Mathod', canton: 'VD', postalCode: '1433' },
  { name: 'Mex', canton: 'VD', postalCode: '1032' },
  { name: 'Mézières', canton: 'VD', postalCode: '1081' },
  { name: 'Mies', canton: 'VD', postalCode: '1291' },
  { name: 'Mollens', canton: 'VD', postalCode: '1132' },
  { name: 'Molondin', canton: 'VD', postalCode: '1433' },
  { name: 'Montricher', canton: 'VD', postalCode: '1141' },
  { name: 'Mont-la-Ville', canton: 'VD', postalCode: '1146' },
  { name: 'Montpreveyres', canton: 'VD', postalCode: '1081' },
  { name: 'Morrens', canton: 'VD', postalCode: '1037' },
  { name: 'Moudon', canton: 'VD', postalCode: '1510' },
  { name: 'Mouthier', canton: 'VD', postalCode: '1433' },
  { name: 'Nyon', canton: 'VD', postalCode: '1260' },
  { name: 'Ogens', canton: 'VD', postalCode: '1082' },
  { name: 'Onnens', canton: 'VD', postalCode: '1425' },
  { name: 'Orbe', canton: 'VD', postalCode: '1350' },
  { name: 'Orny', canton: 'VD', postalCode: '1321' },
  { name: 'Oron', canton: 'VD', postalCode: '1608' },
  { name: 'Oron-la-Ville', canton: 'VD', postalCode: '1608' },
  { name: 'Oron-le-Châtel', canton: 'VD', postalCode: '1609' },
  { name: 'Oulens-sous-Echallens', canton: 'VD', postalCode: '1040' },
  { name: 'Pailly', canton: 'VD', postalCode: '1041' },
  { name: 'Pampigny', canton: 'VD', postalCode: '1142' },
  { name: 'Penthalaz', canton: 'VD', postalCode: '1305' },
  { name: 'Peney-le-Jorat', canton: 'VD', postalCode: '1082' },
  { name: 'Perroy', canton: 'VD', postalCode: '1189' },
  { name: 'Pizy', canton: 'VD', postalCode: '1149' },
  { name: 'Pompaples', canton: 'VD', postalCode: '1318' },
  { name: 'Prahins', canton: 'VD', postalCode: '1425' },
  { name: 'Premier', canton: 'VD', postalCode: '1321' },
  { name: 'Prilly', canton: 'VD', postalCode: '1008' },
  { name: 'Préverenges', canton: 'VD', postalCode: '1124' },
  { name: 'Rances', canton: 'VD', postalCode: '1353' },
  { name: 'Renens', canton: 'VD', postalCode: '1020' },
  { name: 'Rivaz', canton: 'VD', postalCode: '1072' },
  { name: 'Roche', canton: 'VD', postalCode: '1845' },
  { name: 'Romainmôtier', canton: 'VD', postalCode: '1323' },
  { name: 'Ropraz', canton: 'VD', postalCode: '1086' },
  { name: 'Rossens', canton: 'VD', postalCode: '1053' },
  { name: 'Rue', canton: 'VD', postalCode: '1543' },
  { name: 'Rueyres', canton: 'VD', postalCode: '1353' },
  { name: 'Saint-George', canton: 'VD', postalCode: '1188' },
  { name: 'Saint-Livres', canton: 'VD', postalCode: '1182' },
  { name: 'Saint-Légier-La Chiésaz', canton: 'VD', postalCode: '1806' },
  { name: 'Saint-Prex', canton: 'VD', postalCode: '1162' },
  { name: 'Saint-Saphorin', canton: 'VD', postalCode: '1073' },
  { name: 'Saint-Sulpice', canton: 'VD', postalCode: '1025' },
  { name: 'Savigny', canton: 'VD', postalCode: '1073' },
  { name: 'Senarclens', canton: 'VD', postalCode: '1318' },
  { name: 'Servion', canton: 'VD', postalCode: '1086' },
  { name: 'Signy', canton: 'VD', postalCode: '1278' },
  { name: 'Sullens', canton: 'VD', postalCode: '1037' },
  { name: 'Tannay', canton: 'VD', postalCode: '1291' },
  { name: 'Thierrens', canton: 'VD', postalCode: '1514' },
  { name: 'Treycovignens', canton: 'VD', postalCode: '1040' },
  { name: 'Trélex', canton: 'VD', postalCode: '1267' },
  { name: 'Vallorbe', canton: 'VD', postalCode: '1337' },
  { name: 'Vaulion', canton: 'VD', postalCode: '1328' },
  { name: 'Vaux-sur-Morges', canton: 'VD', postalCode: '1114' },
  { name: 'Veigy', canton: 'VD', postalCode: '1245' },
  { name: 'Veytaux', canton: 'VD', postalCode: '1820' },
  { name: 'Vich', canton: 'VD', postalCode: '1867' },
  { name: 'Villars-sous-Yens', canton: 'VD', postalCode: '1169' },
  { name: 'Villeneuve', canton: 'VD', postalCode: '1844' },
  { name: 'Vinzel', canton: 'VD', postalCode: '1189' },
  { name: 'Vufflens-la-Ville', canton: 'VD', postalCode: '1303' },
  { name: 'Vufflens-le-Château', canton: 'VD', postalCode: '1133' },
  { name: 'Vuiteboeuf', canton: 'VD', postalCode: '1442' },
  { name: 'Yens', canton: 'VD', postalCode: '1169' },
  { name: 'Yverdon-les-Bains', canton: 'VD', postalCode: '1400' },
  { name: 'Yvonand', canton: 'VD', postalCode: '1462' },
  { name: 'Agiez', canton: 'VD', postalCode: '1373' },
  { name: 'Arnex-sur-Orbe', canton: 'VD', postalCode: '1321' },
  { name: 'Bullet', canton: 'VD', postalCode: '1451' },
  { name: 'Champvent', canton: 'VD', postalCode: '1442' },
  { name: 'Fiez', canton: 'VD', postalCode: '1429' },
  { name: 'Goumoëns', canton: 'VD', postalCode: '1430' },
  { name: 'Mauborget', canton: 'VD', postalCode: '1451' },
  { name: 'Montcherand', canton: 'VD', postalCode: '1372' },
  { name: 'Novalles', canton: 'VD', postalCode: '1430' },
  { name: 'Ormont-Dessus', canton: 'VD', postalCode: '1863' },
  { name: 'Ormont-Dessous', canton: 'VD', postalCode: '1862' },
  { name: 'Poliez-Pittet', canton: 'VD', postalCode: '1413' },
  { name: 'Provence', canton: 'VD', postalCode: '1451' },
  { name: 'Rossenges', canton: 'VD', postalCode: '1082' },
  { name: 'Sainte-Croix', canton: 'VD', postalCode: '1450' },
  { name: 'Sévery', canton: 'VD', postalCode: '1149' },
  { name: 'Suchy', canton: 'VD', postalCode: '1373' },
  { name: 'Suscévaz', canton: 'VD', postalCode: '1430' },
  { name: 'Vugelles-La Mothe', canton: 'VD', postalCode: '1428' },
  { name: 'Essert-sous-Champvent', canton: 'VD', postalCode: '1442' },
  { name: 'Besse', canton: 'VD', postalCode: '1451' },
  { name: 'La Praz', canton: 'VD', postalCode: '1321' },
  { name: 'Montreux', canton: 'VD', postalCode: '1820' },
  { name: 'Vevey', canton: 'VD', postalCode: '1800' },
  { name: 'Chéserex', canton: 'VD', postalCode: '1274' },
  { name: 'Grens', canton: 'VD', postalCode: '1275' },
  { name: 'Lausanne', canton: 'VD', postalCode: '1000' },
  { name: 'Pully', canton: 'VD', postalCode: '1009' },
  { name: 'Morges', canton: 'VD', postalCode: '1110' },
  { name: 'Nyon', canton: 'VD', postalCode: '1260' },
  { name: 'Aigle', canton: 'VD', postalCode: '1860' },
  { name: 'Bex', canton: 'VD', postalCode: '1880' },
  { name: 'Monthey', canton: 'VD', postalCode: '1870' },
  { name: 'Payerne', canton: 'VD', postalCode: '1540' },

  // More BE municipalities
  { name: 'Affoltern', canton: 'BE', postalCode: '3416' },
  { name: 'Bargen', canton: 'BE', postalCode: '3314' },
  { name: 'Bleienbach', canton: 'BE', postalCode: '3365' },
  { name: 'Bollodingen', canton: 'BE', postalCode: '3362' },
  { name: 'Büren', canton: 'BE', postalCode: '3297' },
  { name: 'Diessbach', canton: 'BE', postalCode: '3612' },
  { name: 'Dürrenroth', canton: 'BE', postalCode: '3463' },
  { name: 'Eriswil', canton: 'BE', postalCode: '4952' },
  { name: 'Flamatt', canton: 'BE', postalCode: '3175' },
  { name: 'Grafenried', canton: 'BE', postalCode: '3309' },
  { name: 'Guggisberg', canton: 'BE', postalCode: '3158' },
  { name: 'Huttwil', canton: 'BE', postalCode: '4950' },
  { name: 'Iffwil', canton: 'BE', postalCode: '3306' },
  { name: 'Jegenstorf', canton: 'BE', postalCode: '3303' },
  { name: 'Kiesen', canton: 'BE', postalCode: '3622' },
  { name: 'Kirchdorf', canton: 'BE', postalCode: '3383' },
  { name: 'Lüscherz', canton: 'BE', postalCode: '2576' },
  { name: 'Matten', canton: 'BE', postalCode: '3805' },
  { name: 'Mittelhäusern', canton: 'BE', postalCode: '3206' },
  { name: 'Neuenegg', canton: 'BE', postalCode: '3176' },
  { name: 'Niederwangen', canton: 'BE', postalCode: '3098' },
  { name: 'Oberwil', canton: 'BE', postalCode: '4104' },
  { name: 'Riggisberg', canton: 'BE', postalCode: '3132' },
  { name: 'Rüschegg', canton: 'BE', postalCode: '3157' },
  { name: 'Schwarzenburg', canton: 'BE', postalCode: '3150' },
  { name: 'Sigriswil', canton: 'BE', postalCode: '3655' },
  { name: 'Uetendorf', canton: 'BE', postalCode: '3661' },
  { name: 'Villarzel', canton: 'BE', postalCode: '3116' },
  { name: 'Wattenwil', canton: 'BE', postalCode: '3665' },
  { name: 'Zwieselberg', canton: 'BE', postalCode: '3618' },

  // Additional SG municipalities  
  { name: 'Alt St. Johann', canton: 'SG', postalCode: '8763' },
  { name: 'Amden', canton: 'SG', postalCode: '8873' },
  { name: 'Bad Ragaz', canton: 'SG', postalCode: '7310' },
  { name: 'Berneck', canton: 'SG', postalCode: '9442' },
  { name: 'Bodmen', canton: 'SG', postalCode: '8717' },
  { name: 'Brunnadern', canton: 'SG', postalCode: '8716' },
  { name: 'Buchs', canton: 'SG', postalCode: '9470' },
  { name: 'Degersheim', canton: 'SG', postalCode: '9114' },
  { name: 'Eggersriet', canton: 'SG', postalCode: '9034' },
  { name: 'Flawil', canton: 'SG', postalCode: '9230' },
  { name: 'Gams', canton: 'SG', postalCode: '9473' },
  { name: 'Ganterschwil', canton: 'SG', postalCode: '9122' },
  { name: 'Goldach', canton: 'SG', postalCode: '9400' },
  { name: 'Haggen', canton: 'SG', postalCode: '8876' },
  { name: 'Hemberg', canton: 'SG', postalCode: '9115' },
  { name: 'Jonschwil', canton: 'SG', postalCode: '9243' },
  { name: 'Kirchberg', canton: 'SG', postalCode: '9502' },
  { name: 'Krummenau', canton: 'SG', postalCode: '8717' },
  { name: 'Lichtensteig', canton: 'SG', postalCode: '9620' },
  { name: 'Lütisburg', canton: 'SG', postalCode: '9621' },
  { name: 'Marbach', canton: 'SG', postalCode: '6196' },
  { name: 'Mogelsberg', canton: 'SG', postalCode: '9122' },
  { name: 'Mörschwil', canton: 'SG', postalCode: '9442' },
  { name: 'Nesslau', canton: 'SG', postalCode: '9650' },
  { name: 'Neu St. Johann', canton: 'SG', postalCode: '9642' },
  { name: 'Niederhelfenschwil', canton: 'SG', postalCode: '9113' },
  { name: 'Oberbüren', canton: 'SG', postalCode: '9245' },
  { name: 'Oberhelfenschwil', canton: 'SG', postalCode: '9621' },
  { name: 'Pfäfers', canton: 'SG', postalCode: '7312' },
  { name: 'Quarten', canton: 'SG', postalCode: '8874' },
  { name: 'Rapperswil', canton: 'SG', postalCode: '8640' },
  { name: 'Rheineck', canton: 'SG', postalCode: '9424' },
  { name: 'Rorschach', canton: 'SG', postalCode: '9400' },
  { name: 'Rüte', canton: 'SG', postalCode: '9057' },
  { name: 'Sennwald', canton: 'SG', postalCode: '9477' },
  { name: 'Sevelen', canton: 'SG', postalCode: '9475' },
  { name: 'Stein', canton: 'SG', postalCode: '9063' },
  { name: 'Teufen', canton: 'SG', postalCode: '9053' },
  { name: 'Thur', canton: 'SG', postalCode: '9403' },
  { name: 'Toggenburg', canton: 'SG', postalCode: '9630' },
  { name: 'Uznach', canton: 'SG', postalCode: '8730' },
  { name: 'Uzwil', canton: 'SG', postalCode: '9240' },
  { name: 'Vilters', canton: 'SG', postalCode: '7324' },
  { name: 'Walenstadt', canton: 'SG', postalCode: '8880' },
  { name: 'Wattwil', canton: 'SG', postalCode: '9630' },
  { name: 'Widnau', canton: 'SG', postalCode: '9443' },
  { name: 'Wittenbach', canton: 'SG', postalCode: '9302' },
  { name: 'Zuzwil', canton: 'SG', postalCode: '9524' },

  // Additional TG municipalities
  { name: 'Aadorf', canton: 'TG', postalCode: '8362' },
  { name: 'Affeltrangen', canton: 'TG', postalCode: '9556' },
  { name: 'Altdorf', canton: 'TG', postalCode: '8262' },
  { name: 'Amriswil', canton: 'TG', postalCode: '8580' },
  { name: 'Arbon', canton: 'TG', postalCode: '9320' },
  { name: 'Basadingen', canton: 'TG', postalCode: '8254' },
  { name: 'Berg', canton: 'TG', postalCode: '8562' },
  { name: 'Bettwiesen', canton: 'TG', postalCode: '8544' },
  { name: 'Bichelsee', canton: 'TG', postalCode: '8363' },
  { name: 'Bischofszell', canton: 'TG', postalCode: '9220' },
  { name: 'Bommern', canton: 'TG', postalCode: '8572' },
  { name: 'Braunau', canton: 'TG', postalCode: '8562' },
  { name: 'Bürglen', canton: 'TG', postalCode: '9545' },
  { name: 'Bussnang', canton: 'TG', postalCode: '8220' },
  { name: 'Degersheim', canton: 'TG', postalCode: '9114' },
  { name: 'Dorf', canton: 'TG', postalCode: '8466' },
  { name: 'Egnach', canton: 'TG', postalCode: '9322' },
  { name: 'Eschlikon', canton: 'TG', postalCode: '9604' },
  { name: 'Felben-Wellhausen', canton: 'TG', postalCode: '8552' },
  { name: 'Fischingen', canton: 'TG', postalCode: '9555' },
  { name: 'Frauenfeld', canton: 'TG', postalCode: '8500' },
  { name: 'Gachnang', canton: 'TG', postalCode: '8547' },
  { name: 'Gottlieben', canton: 'TG', postalCode: '8594' },
  { name: 'Güttingen', canton: 'TG', postalCode: '8592' },
  { name: 'Hagenwil', canton: 'TG', postalCode: '9306' },
  { name: 'Hohentannen', canton: 'TG', postalCode: '9133' },
  { name: 'Horn', canton: 'TG', postalCode: '9326' },
  { name: 'Hugelshofen', canton: 'TG', postalCode: '9315' },
  { name: 'Hummelberg', canton: 'TG', postalCode: '9316' },
  { name: 'Kradolf', canton: 'TG', postalCode: '9214' },
  { name: 'Kreuzlingen', canton: 'TG', postalCode: '8280' },
  { name: 'Langrickenbach', canton: 'TG', postalCode: '9313' },
  { name: 'Lengwil', canton: 'TG', postalCode: '8274' },
  { name: 'Lommis', canton: 'TG', postalCode: '9314' },
  { name: 'Märstetten', canton: 'TG', postalCode: '8555' },
  { name: 'Matzingen', canton: 'TG', postalCode: '9548' },
  { name: 'Müllheim', canton: 'TG', postalCode: '8554' },
  { name: 'Münchwilen', canton: 'TG', postalCode: '9572' },
  { name: 'Neunforn', canton: 'TG', postalCode: '8507' },
  { name: 'Oberaach', canton: 'TG', postalCode: '8585' },
  { name: 'Pfyn', canton: 'TG', postalCode: '8505' },
  { name: 'Raperswilen', canton: 'TG', postalCode: '8588' },
  { name: 'Rickenbach', canton: 'TG', postalCode: '9316' },
  { name: 'Romanshorn', canton: 'TG', postalCode: '8590' },
  { name: 'Salmsach', canton: 'TG', postalCode: '8593' },
  { name: 'Schönholzerswilen', canton: 'TG', postalCode: '9312' },
  { name: 'Sirsdorf', canton: 'TG', postalCode: '9116' },
  { name: 'Sommeri', canton: 'TG', postalCode: '8582' },
  { name: 'Sonterswil', canton: 'TG', postalCode: '9317' },
  { name: 'Steckborn', canton: 'TG', postalCode: '8266' },
  { name: 'Stettfurt', canton: 'TG', postalCode: '9547' },
  { name: 'Sulgen', canton: 'TG', postalCode: '9554' },
  { name: 'Tägerwilen', canton: 'TG', postalCode: '8274' },
  { name: 'Thundorf', canton: 'TG', postalCode: '8512' },
  { name: 'Tobel', canton: 'TG', postalCode: '9555' },
  { name: 'Tägerwilen', canton: 'TG', postalCode: '8274' },
  { name: 'Uesslingen-Buch', canton: 'TG', postalCode: '8505' },
  { name: 'Wagenhausen', canton: 'TG', postalCode: '8252' },
  { name: 'Wäldi', canton: 'TG', postalCode: '8584' },
  { name: 'Weinfelden', canton: 'TG', postalCode: '8570' },
  { name: 'Wigoltingen', canton: 'TG', postalCode: '9554' },
  { name: 'Wilen', canton: 'TG', postalCode: '9545' },
  { name: 'Wuppenau', canton: 'TG', postalCode: '9552' },
  { name: 'Zihlschlacht', canton: 'TG', postalCode: '8575' },

  // Additional ZH municipalities
  { name: 'Adliswil', canton: 'ZH', postalCode: '8134' },
  { name: 'Aeugst am Albis', canton: 'ZH', postalCode: '8914' },
  { name: 'Affoltern am Albis', canton: 'ZH', postalCode: '8910' },
  { name: 'Bonstetten', canton: 'ZH', postalCode: '8906' },
  { name: 'Bubikon', canton: 'ZH', postalCode: '8608' },
  { name: 'Dürnten', canton: 'ZH', postalCode: '8614' },
  { name: 'Egg', canton: 'ZH', postalCode: '8132' },
  { name: 'Gossau', canton: 'ZH', postalCode: '8623' },
  { name: 'Hausen am Albis', canton: 'ZH', postalCode: '8915' },
  { name: 'Hedingen', canton: 'ZH', postalCode: '8908' },
  { name: 'Hinwil', canton: 'ZH', postalCode: '8340' },
  { name: 'Hittnau', canton: 'ZH', postalCode: '8335' },
  { name: 'Knonau', canton: 'ZH', postalCode: '8934' },
  { name: 'Langnau am Albis', canton: 'ZH', postalCode: '8135' },
  { name: 'Maur', canton: 'ZH', postalCode: '8124' },
  { name: 'Mönchaltorf', canton: 'ZH', postalCode: '8617' },
  { name: 'Oberrieden', canton: 'ZH', postalCode: '8942' },
  { name: 'Rifferswil', canton: 'ZH', postalCode: '8911' },
  { name: 'Rüti', canton: 'ZH', postalCode: '8630' },
  { name: 'Schönenberg', canton: 'ZH', postalCode: '8805' },
  { name: 'Stäfa', canton: 'ZH', postalCode: '8712' },
  { name: 'Uetikon am See', canton: 'ZH', postalCode: '8707' },
  { name: 'Wald', canton: 'ZH', postalCode: '8638' },
  { name: 'Wädenswil', canton: 'ZH', postalCode: '8820' },
  { name: 'Wangen-Brüttisellen', canton: 'ZH', postalCode: '8306' },
  { name: 'Wetzikon', canton: 'ZH', postalCode: '8620' },
  { name: 'Zumikon', canton: 'ZH', postalCode: '8126' },
  { name: 'Zwillikon', canton: 'ZH', postalCode: '8910' },

  // Additional LU municipalities
  { name: 'Adligenswil', canton: 'LU', postalCode: '6043' },
  { name: 'Aesch', canton: 'LU', postalCode: '6204' },
  { name: 'Altdorf', canton: 'LU', postalCode: '6035' },
  { name: 'Altishofen', canton: 'LU', postalCode: '6037' },
  { name: 'Ballwil', canton: 'LU', postalCode: '6275' },
  { name: 'Beromünster', canton: 'LU', postalCode: '6215' },
  { name: 'Buchrain', canton: 'LU', postalCode: '6033' },
  { name: 'Buchsee', canton: 'LU', postalCode: '6113' },
  { name: 'Büttikon', canton: 'LU', postalCode: '5616' },
  { name: 'Buttisholz', canton: 'LU', postalCode: '6018' },
  { name: 'Dagmersellen', canton: 'LU', postalCode: '6252' },
  { name: 'Dierikon', canton: 'LU', postalCode: '6036' },
  { name: 'Doppleschwand', canton: 'LU', postalCode: '6173' },
  { name: 'Ebikon', canton: 'LU', postalCode: '6030' },
  { name: 'Egolzwil', canton: 'LU', postalCode: '6242' },
  { name: 'Eich', canton: 'LU', postalCode: '6205' },
  { name: 'Entlebuch', canton: 'LU', postalCode: '6162' },
  { name: 'Ettiswil', canton: 'LU', postalCode: '6242' },
  { name: 'Fischbach', canton: 'LU', postalCode: '6147' },
  { name: 'Flühli', canton: 'LU', postalCode: '6174' },
  { name: 'Gettnau', canton: 'LU', postalCode: '6143' },
  { name: 'Grossdietwil', canton: 'LU', postalCode: '6143' },
  { name: 'Grosswangen', canton: 'LU', postalCode: '6023' },
  { name: 'Hasle', canton: 'LU', postalCode: '6166' },
  { name: 'Hergiswil', canton: 'LU', postalCode: '6018' },
  { name: 'Hildisrieden', canton: 'LU', postalCode: '6018' },
  { name: 'Hitzkirch', canton: 'LU', postalCode: '6284' },
  { name: 'Hochdorf', canton: 'LU', postalCode: '6280' },
  { name: 'Hohenrain', canton: 'LU', postalCode: '6276' },
  { name: 'Horw', canton: 'LU', postalCode: '6048' },
  { name: 'Inwil', canton: 'LU', postalCode: '6033' },
  { name: 'Kriens', canton: 'LU', postalCode: '6010' },
  { name: 'Luthern', canton: 'LU', postalCode: '6156' },
  { name: 'Malters', canton: 'LU', postalCode: '6101' },
  { name: 'Mauensee', canton: 'LU', postalCode: '6212' },
  { name: 'Meggen', canton: 'LU', postalCode: '6045' },
  { name: 'Menznau', canton: 'LU', postalCode: '6122' },
  { name: 'Neuenkirch', canton: 'LU', postalCode: '6206' },
  { name: 'Nottwil', canton: 'LU', postalCode: '6207' },
  { name: 'Oberägeri', canton: 'LU', postalCode: '6315' },
  { name: 'Pfaffnau', canton: 'LU', postalCode: '6262' },
  { name: 'Reiden', canton: 'LU', postalCode: '6262' },
  { name: 'Rickenbach', canton: 'LU', postalCode: '6133' },
  { name: 'Roggliswil', canton: 'LU', postalCode: '6262' },
  { name: 'Römerswil', canton: 'LU', postalCode: '6023' },
  { name: 'Ruswil', canton: 'LU', postalCode: '6017' },
  { name: 'Schüpfheim', canton: 'LU', postalCode: '6162' },
  { name: 'Schwarzenberg', canton: 'LU', postalCode: '6105' },
  { name: 'Sempach', canton: 'LU', postalCode: '6204' },
  { name: 'Sursee', canton: 'LU', postalCode: '6210' },
  { name: 'Trachselwald', canton: 'LU', postalCode: '3458' },
  { name: 'Triengen', canton: 'LU', postalCode: '6234' },
  { name: 'Udligenswil', canton: 'LU', postalCode: '6044' },
  { name: 'Vitznau', canton: 'LU', postalCode: '6354' },
  { name: 'Wauwil', canton: 'LU', postalCode: '6242' },
  { name: 'Weggis', canton: 'LU', postalCode: '6353' },
  { name: 'Wikon', canton: 'LU', postalCode: '6252' },
  { name: 'Willisau', canton: 'LU', postalCode: '6130' },
  { name: 'Wolhusen', canton: 'LU', postalCode: '6110' },
  { name: 'Zell', canton: 'LU', postalCode: '6144' },

  // Additional GR municipalities
  { name: 'Ammerswil', canton: 'GR', postalCode: '5600' },
  { name: 'Andeer', canton: 'GR', postalCode: '7440' },
  { name: 'Ardez', canton: 'GR', postalCode: '7546' },
  { name: 'Bonaduz', canton: 'GR', postalCode: '7402' },
  { name: 'Bondno', canton: 'GR', postalCode: '7446' },
  { name: 'Bregaglia', canton: 'GR', postalCode: '7605' },
  { name: 'Breil/Brigels', canton: 'GR', postalCode: '7165' },
  { name: 'Castrisch', canton: 'GR', postalCode: '7128' },
  { name: 'Celerina', canton: 'GR', postalCode: '7505' },
  { name: 'Chur', canton: 'GR', postalCode: '7000' },
  { name: 'Churwalden', canton: 'GR', postalCode: '7075' },
  { name: 'Clugin', canton: 'GR', postalCode: '7412' },
  { name: 'Cumbel', canton: 'GR', postalCode: '7124' },
  { name: 'Davos', canton: 'GR', postalCode: '7270' },
  { name: 'Domat/Ems', canton: 'GR', postalCode: '7013' },
  { name: 'Donat', canton: 'GR', postalCode: '7423' },
  { name: 'Feldis/Veulden', canton: 'GR', postalCode: '7404' },
  { name: 'Flerden', canton: 'GR', postalCode: '7425' },
  { name: 'Flims', canton: 'GR', postalCode: '7018' },
  { name: 'Ftan', canton: 'GR', postalCode: '7551' },
  { name: 'Fideris', canton: 'GR', postalCode: '7421' },
  { name: 'Gandria', canton: 'GR', postalCode: '6978' },
  { name: 'Giornico', canton: 'GR', postalCode: '6745' },
  { name: 'Grono', canton: 'GR', postalCode: '6537' },
  { name: 'Guarda', canton: 'GR', postalCode: '7545' },
  { name: 'Ilanz', canton: 'GR', postalCode: '7130' },
  { name: 'Jenaz', canton: 'GR', postalCode: '7423' },
  { name: 'Jens', canton: 'GR', postalCode: '2564' },
  { name: 'Klosters', canton: 'GR', postalCode: '7250' },
  { name: 'Laax', canton: 'GR', postalCode: '7031' },
  { name: 'Ladir', canton: 'GR', postalCode: '7132' },
  { name: 'Lumnezia', canton: 'GR', postalCode: '7142' },
  { name: 'Luzein', canton: 'GR', postalCode: '7243' },
  { name: 'Madulain', canton: 'GR', postalCode: '7523' },
  { name: 'Malans', canton: 'GR', postalCode: '7212' },
  { name: 'Medels im Rheinwald', canton: 'GR', postalCode: '7448' },
  { name: 'Mesocco', canton: 'GR', postalCode: '7444' },
  { name: 'Mulegns', canton: 'GR', postalCode: '7452' },
  { name: 'Obersaxen', canton: 'GR', postalCode: '7134' },
  { name: 'Pany', canton: 'GR', postalCode: '7242' },
  { name: 'Pignia', canton: 'GR', postalCode: '7424' },
  { name: 'Pontresina', canton: 'GR', postalCode: '7504' },
  { name: 'Poschiavo', canton: 'GR', postalCode: '7742' },
  { name: 'Ramosch', canton: 'GR', postalCode: '7542' },
  { name: 'Roveredo', canton: 'GR', postalCode: '6535' },
  { name: 'Ruschein', canton: 'GR', postalCode: '7135' },
  { name: 'Sagliain', canton: 'GR', postalCode: '7424' },
  { name: 'St. Moritz', canton: 'GR', postalCode: '7500' },
  { name: 'Santa Maria im Münstertal', canton: 'GR', postalCode: '7543' },
  { name: 'Savognin', canton: 'GR', postalCode: '7430' },
  { name: 'Schluein', canton: 'GR', postalCode: '7131' },
  { name: 'Schmitten', canton: 'GR', postalCode: '7411' },
  { name: 'Sedrun', canton: 'GR', postalCode: '7188' },
  { name: 'Sogn Gion', canton: 'GR', postalCode: '7422' },
  { name: 'Splügen', canton: 'GR', postalCode: '7435' },
  { name: 'Stampa', canton: 'GR', postalCode: '7605' },
  { name: 'Sumvitg', canton: 'GR', postalCode: '7166' },
  { name: 'Tarasp', canton: 'GR', postalCode: '7553' },
  { name: 'Tenna', canton: 'GR', postalCode: '7127' },
  { name: 'Trin', canton: 'GR', postalCode: '7014' },
  { name: 'Tschappina', canton: 'GR', postalCode: '7427' },
  { name: 'Tschiertschen', canton: 'GR', postalCode: '7022' },
  { name: 'Tujetsch', canton: 'GR', postalCode: '7188' },
  { name: 'Urmein', canton: 'GR', postalCode: '7411' },
  { name: 'Valendas', canton: 'GR', postalCode: '7124' },
  { name: 'Vals', canton: 'GR', postalCode: '7132' },
  { name: 'Vaz/Obervaz', canton: 'GR', postalCode: '7082' },
  { name: 'Versam', canton: 'GR', postalCode: '7126' },
  { name: 'Vrin', canton: 'GR', postalCode: '7138' },
  { name: 'Zernez', canton: 'GR', postalCode: '7537' },
  { name: 'Zillis', canton: 'GR', postalCode: '7442' },
  { name: 'Zuoz', canton: 'GR', postalCode: '7524' },

  // Additional TI municipalities
  { name: 'Airolo', canton: 'TI', postalCode: '6780' },
  { name: 'Aranno', canton: 'TI', postalCode: '6982' },
  { name: 'Arogno', canton: 'TI', postalCode: '6823' },
  { name: 'Arosio', canton: 'TI', postalCode: '6981' },
  { name: 'Astano', canton: 'TI', postalCode: '6999' },
  { name: 'Biasca', canton: 'TI', postalCode: '6710' },
  { name: 'Breggia', canton: 'TI', postalCode: '6838' },
  { name: 'Breno', canton: 'TI', postalCode: '6936' },
  { name: 'Brione', canton: 'TI', postalCode: '6583' },
  { name: 'Brissago', canton: 'TI', postalCode: '6614' },
  { name: 'Campo', canton: 'TI', postalCode: '6538' },
  { name: 'Canobbio', canton: 'TI', postalCode: '6952' },
  { name: 'Capriasca', canton: 'TI', postalCode: '6957' },
  { name: 'Carabietta', canton: 'TI', postalCode: '6933' },
  { name: 'Caslano', canton: 'TI', postalCode: '6987' },
  { name: 'Castel San Pietro', canton: 'TI', postalCode: '6825' },
  { name: 'Cavigliano', canton: 'TI', postalCode: '6622' },
  { name: 'Cerentino', canton: 'TI', postalCode: '6683' },
  { name: 'Certara', canton: 'TI', postalCode: '6804' },
  { name: 'Cevio', canton: 'TI', postalCode: '6683' },
  { name: 'Chiasso', canton: 'TI', postalCode: '6830' },
  { name: 'Collina d\'Oro', canton: 'TI', postalCode: '6924' },
  { name: 'Corippo', canton: 'TI', postalCode: '6596' },
  { name: 'Cugnasco-Gerra', canton: 'TI', postalCode: '6529' },
  { name: 'Faido', canton: 'TI', postalCode: '6760' },
  { name: 'Giornico', canton: 'TI', postalCode: '6745' },
  { name: 'Giubiasco', canton: 'TI', postalCode: '6512' },
  { name: 'Gordola', canton: 'TI', postalCode: '6595' },
  { name: 'Gorduno', canton: 'TI', postalCode: '6525' },
  { name: 'Lavertezzo', canton: 'TI', postalCode: '6621' },
  { name: 'Lavizzara', canton: 'TI', postalCode: '6693' },
  { name: 'Locarno', canton: 'TI', postalCode: '6600' },
  { name: 'Lodrino', canton: 'TI', postalCode: '6527' },
  { name: 'Lugano', canton: 'TI', postalCode: '6900' },
  { name: 'Malcantone', canton: 'TI', postalCode: '6982' },
  { name: 'Manno', canton: 'TI', postalCode: '6938' },
  { name: 'Mendrisio', canton: 'TI', postalCode: '6850' },
  { name: 'Meride', canton: 'TI', postalCode: '6866' },
  { name: 'Miglieglia', canton: 'TI', postalCode: '6983' },
  { name: 'Minusio', canton: 'TI', postalCode: '6648' },
  { name: 'Monteggio', canton: 'TI', postalCode: '6995' },
  { name: 'Morbio Inferiore', canton: 'TI', postalCode: '6834' },
  { name: 'Morcote', canton: 'TI', postalCode: '6922' },
  { name: 'Moscia', canton: 'TI', postalCode: '6653' },
  { name: 'Muggio', canton: 'TI', postalCode: '6835' },
  { name: 'Novazzano', canton: 'TI', postalCode: '6883' },
  { name: 'Olivone', canton: 'TI', postalCode: '6716' },
  { name: 'Onsernone', canton: 'TI', postalCode: '6662' },
  { name: 'Orselina', canton: 'TI', postalCode: '6622' },
  { name: 'Pollegio', canton: 'TI', postalCode: '6742' },
  { name: 'Ponte Capriasca', canton: 'TI', postalCode: '6957' },
  { name: 'Pregassona', canton: 'TI', postalCode: '6963' },
  { name: 'Pura', canton: 'TI', postalCode: '6984' },
  { name: 'Quinto', canton: 'TI', postalCode: '6775' },
  { name: 'Riazzino', canton: 'TI', postalCode: '6595' },
  { name: 'Riva San Vitale', canton: 'TI', postalCode: '6826' },
  { name: 'Riviera', canton: 'TI', postalCode: '6702' },
  { name: 'Rono', canton: 'TI', postalCode: '6537' },
  { name: 'Sagno', canton: 'TI', postalCode: '6838' },
  { name: 'Sala Capriasca', canton: 'TI', postalCode: '6957' },
  { name: 'Sambuco', canton: 'TI', postalCode: '6682' },
  { name: 'Sant\'Abbondio', canton: 'TI', postalCode: '6805' },
  { name: 'Savosa', canton: 'TI', postalCode: '6942' },
  { name: 'Sementina', canton: 'TI', postalCode: '6514' },
  { name: 'Serravalle', canton: 'TI', postalCode: '6703' },
  { name: 'Sessa', canton: 'TI', postalCode: '6991' },
  { name: 'Sonogn', canton: 'TI', postalCode: '6996' },
  { name: 'Tegna', canton: 'TI', postalCode: '6573' },
  { name: 'Tenero-Contra', canton: 'TI', postalCode: '6593' },
  { name: 'Termen', canton: 'TI', postalCode: '6661' },
  { name: 'Terre di Pedemonte', canton: 'TI', postalCode: '6645' },
  { name: 'Torre', canton: 'TI', postalCode: '6717' },
  { name: 'Vira', canton: 'TI', postalCode: '6573' },
  { name: 'Vogorno', canton: 'TI', postalCode: '6621' },

  // Additional VS municipalities
  { name: 'Agarn', canton: 'VS', postalCode: '3951' },
  { name: 'Albinen', canton: 'VS', postalCode: '3954' },
  { name: 'Anniviers', canton: 'VS', postalCode: '3961' },
  { name: 'Ardon', canton: 'VS', postalCode: '1957' },
  { name: 'Bagnes', canton: 'VS', postalCode: '1934' },
  { name: 'Baltschieder', canton: 'VS', postalCode: '3903' },
  { name: 'Bellwald', canton: 'VS', postalCode: '3997' },
  { name: 'Bettmeralp', canton: 'VS', postalCode: '3992' },
  { name: 'Bister', canton: 'VS', postalCode: '3983' },
  { name: 'Bitsch', canton: 'VS', postalCode: '3985' },
  { name: 'Blatten', canton: 'VS', postalCode: '3919' },
  { name: 'Bourg-Saint-Pierre', canton: 'VS', postalCode: '1946' },
  { name: 'Bramois', canton: 'VS', postalCode: '1966' },
  { name: 'Brig', canton: 'VS', postalCode: '3900' },
  { name: 'Bürchen', canton: 'VS', postalCode: '3942' },
  { name: 'Chalais', canton: 'VS', postalCode: '3966' },
  { name: 'Chamoson', canton: 'VS', postalCode: '1958' },
  { name: 'Chandolin', canton: 'VS', postalCode: '3961' },
  { name: 'Charrat', canton: 'VS', postalCode: '1912' },
  { name: 'Chemilion', canton: 'VS', postalCode: '1972' },
  { name: 'Chippis', canton: 'VS', postalCode: '3982' },
  { name: 'Collombey-Muraz', canton: 'VS', postalCode: '1868' },
  { name: 'Conthey', canton: 'VS', postalCode: '1964' },
  { name: 'Dorénaz', canton: 'VS', postalCode: '1872' },
  { name: 'Eggerberg', canton: 'VS', postalCode: '3952' },
  { name: 'Eisten', canton: 'VS', postalCode: '3920' },
  { name: 'Evolène', canton: 'VS', postalCode: '1984' },
  { name: 'Ferden', canton: 'VS', postalCode: '3918' },
  { name: 'Fully', canton: 'VS', postalCode: '1926' },
  { name: 'Gampel', canton: 'VS', postalCode: '3945' },
  { name: 'Grächen', canton: 'VS', postalCode: '3925' },
  { name: 'Grengiols', canton: 'VS', postalCode: '3996' },
  { name: 'Grimsel', canton: 'VS', postalCode: '3999' },
  { name: 'Grône', canton: 'VS', postalCode: '3979' },
  { name: 'Guttet-Feschel', canton: 'VS', postalCode: '3948' },
  { name: 'Hérémence', canton: 'VS', postalCode: '1983' },
  { name: 'Icogne', canton: 'VS', postalCode: '1976' },
  { name: 'Inden', canton: 'VS', postalCode: '3951' },
  { name: 'Lalden', canton: 'VS', postalCode: '3922' },
  { name: 'Lax', canton: 'VS', postalCode: '3995' },
  { name: 'Leuk', canton: 'VS', postalCode: '3953' },
  { name: 'Leukerbad', canton: 'VS', postalCode: '3954' },
  { name: 'Liddes', canton: 'VS', postalCode: '1945' },
  { name: 'Martigny', canton: 'VS', postalCode: '1920' },
  { name: 'Massongex', canton: 'VS', postalCode: '1869' },
  { name: 'Miège', canton: 'VS', postalCode: '3973' },
  { name: 'Mollens', canton: 'VS', postalCode: '3973' },
  { name: 'Monthey', canton: 'VS', postalCode: '1870' },
  { name: 'Morge', canton: 'VS', postalCode: '1905' },
  { name: 'Mund', canton: 'VS', postalCode: '3997' },
  { name: 'Naters', canton: 'VS', postalCode: '3904' },
  { name: 'Nendaz', canton: 'VS', postalCode: '1993' },
  { name: 'Neville', canton: 'VS', postalCode: '1962' },
  { name: 'Oberems', canton: 'VS', postalCode: '3943' },
  { name: 'Orsières', canton: 'VS', postalCode: '1938' },
  { name: 'Port-Valais', canton: 'VS', postalCode: '1896' },
  { name: 'Randogne', canton: 'VS', postalCode: '3975' },
  { name: 'Raron', canton: 'VS', postalCode: '3942' },
  { name: 'Riddes', canton: 'VS', postalCode: '1908' },
  { name: 'Riederalp', canton: 'VS', postalCode: '3986' },
  { name: 'Ried-Brig', canton: 'VS', postalCode: '3902' },
  { name: 'Saas-Almagell', canton: 'VS', postalCode: '3905' },
  { name: 'Saas-Balen', canton: 'VS', postalCode: '3905' },
  { name: 'Saas-Fee', canton: 'VS', postalCode: '3906' },
  { name: 'Saas-Grund', canton: 'VS', postalCode: '3910' },
  { name: 'Saint-Léonard', canton: 'VS', postalCode: '1958' },
  { name: 'Saint-Maurice', canton: 'VS', postalCode: '1890' },
  { name: 'Salgesch', canton: 'VS', postalCode: '3970' },
  { name: 'Saxon', canton: 'VS', postalCode: '1907' },
  { name: 'Sembrancher', canton: 'VS', postalCode: '1933' },
  { name: 'Sierre', canton: 'VS', postalCode: '3960' },
  { name: 'Sion', canton: 'VS', postalCode: '1950' },
  { name: 'Stalden', canton: 'VS', postalCode: '3922' },
  { name: 'Staldenried', canton: 'VS', postalCode: '3922' },
  { name: 'Steg', canton: 'VS', postalCode: '3948' },
  { name: 'Törbel', canton: 'VS', postalCode: '3927' },
  { name: 'Trient', canton: 'VS', postalCode: '1927' },
  { name: 'Troistorrents', canton: 'VS', postalCode: '1873' },
  { name: 'Unterbäch', canton: 'VS', postalCode: '3944' },
  { name: 'Venthône', canton: 'VS', postalCode: '3974' },
  { name: 'Vérossaz', canton: 'VS', postalCode: '1864' },
  { name: 'Vétroz', canton: 'VS', postalCode: '1963' },
  { name: 'Veyras', canton: 'VS', postalCode: '3968' },
  { name: 'Veysonnaz', canton: 'VS', postalCode: '1992' },
  { name: 'Vionnaz', canton: 'VS', postalCode: '1895' },
  { name: 'Visp', canton: 'VS', postalCode: '3930' },
  { name: 'Vissoie', canton: 'VS', postalCode: '3961' },
  { name: 'Vollèges', canton: 'VS', postalCode: '1948' },
  { name: 'Vouvry', canton: 'VS', postalCode: '1896' },
  { name: 'Wiler', canton: 'VS', postalCode: '3948' },
  { name: 'Zeneggen', canton: 'VS', postalCode: '3937' },
  { name: 'Zermatt', canton: 'VS', postalCode: '3920' },
  { name: 'Zwischbergen', canton: 'VS', postalCode: '3905' },

  // Additional NE municipalities
  { name: 'Boudry', canton: 'NE', postalCode: '2017' },
  { name: 'Brot-Dessous', canton: 'NE', postalCode: '2016' },
  { name: 'Brot-Plamboz', canton: 'NE', postalCode: '2016' },
  { name: 'Cerlier', canton: 'NE', postalCode: '2072' },
  { name: 'Cernier', canton: 'NE', postalCode: '2330' },
  { name: 'Chézard-Saint-Martin', canton: 'NE', postalCode: '2053' },
  { name: 'Coffrane', canton: 'NE', postalCode: '2052' },
  { name: 'Corcelles-Cormondrèche', canton: 'NE', postalCode: '2034' },
  { name: 'Corgémont', canton: 'NE', postalCode: '2607' },
  { name: 'Cortaillod', canton: 'NE', postalCode: '2016' },
  { name: 'Couvet', canton: 'NE', postalCode: '2104' },
  { name: 'Dombresson', canton: 'NE', postalCode: '2055' },
  { name: 'Enges', canton: 'NE', postalCode: '2046' },
  { name: 'Fleurier', canton: 'NE', postalCode: '2114' },
  { name: 'Fontainemelon', canton: 'NE', postalCode: '2105' },
  { name: 'Fontaines', canton: 'NE', postalCode: '2022' },
  { name: 'Frenières', canton: 'NE', postalCode: '2023' },
  { name: 'Gorgier', canton: 'NE', postalCode: '2025' },
  { name: 'Grandevent', canton: 'NE', postalCode: '1344' },
  { name: 'Hauterive', canton: 'NE', postalCode: '2068' },
  { name: 'La Chaux-de-Fonds', canton: 'NE', postalCode: '2300' },
  { name: 'La Côte-aux-Fées', canton: 'NE', postalCode: '2107' },
  { name: 'La Sagne', canton: 'NE', postalCode: '2314' },
  { name: 'Le Landeron', canton: 'NE', postalCode: '2519' },
  { name: 'Le Locle', canton: 'NE', postalCode: '2400' },
  { name: 'Les Bayards', canton: 'NE', postalCode: '2106' },
  { name: 'Les Brenets', canton: 'NE', postalCode: '2412' },
  { name: 'Les Ponts-de-Martel', canton: 'NE', postalCode: '2316' },
  { name: 'Le Pâquier', canton: 'NE', postalCode: '2053' },
  { name: 'Lignières', canton: 'NE', postalCode: '2073' },
  { name: 'Maîche', canton: 'NE', postalCode: '25120' },
  { name: 'Marin-Epagnier', canton: 'NE', postalCode: '2072' },
  { name: 'Montalchez', canton: 'NE', postalCode: '2028' },
  { name: 'Montmollin', canton: 'NE', postalCode: '2052' },
  { name: 'Môtiers', canton: 'NE', postalCode: '2112' },
  { name: 'Neuchâtel', canton: 'NE', postalCode: '2000' },
  { name: 'Noiraigue', canton: 'NE', postalCode: '2113' },
  { name: 'Peseux', canton: 'NE', postalCode: '2035' },
  { name: 'Rochefort', canton: 'NE', postalCode: '2023' },
  { name: 'Saint-Aubin', canton: 'NE', postalCode: '2024' },
  { name: 'Saint-Blaise', canton: 'NE', postalCode: '2072' },
  { name: 'Savagnier', canton: 'NE', postalCode: '2054' },
  { name: 'Travers', canton: 'NE', postalCode: '2115' },
  { name: 'Valangin', canton: 'NE', postalCode: '2043' },
  { name: 'Val-de-Ruz', canton: 'NE', postalCode: '2054' },
  { name: 'Val-de-Travers', canton: 'NE', postalCode: '2114' },
  { name: 'Vaumarcus', canton: 'NE', postalCode: '2027' },

  // Additional FR municipalities
  { name: 'Alterswil', canton: 'FR', postalCode: '1716' },
  { name: 'Arconciel', canton: 'FR', postalCode: '1725' },
  { name: 'Aubonne', canton: 'FR', postalCode: '1170' },
  { name: 'Autafond', canton: 'FR', postalCode: '1721' },
  { name: 'Autavaux', canton: 'FR', postalCode: '1524' },
  { name: 'Avry', canton: 'FR', postalCode: '1754' },
  { name: 'Bas-Intyamon', canton: 'FR', postalCode: '1663' },
  { name: 'Belfaux', canton: 'FR', postalCode: '1782' },
  { name: 'Billens', canton: 'FR', postalCode: '1682' },
  { name: 'Boltigen', canton: 'FR', postalCode: '3760' },
  { name: 'Bossonnens', canton: 'FR', postalCode: '1617' },
  { name: 'Bouloz', canton: 'FR', postalCode: '1677' },
  { name: 'Bourg', canton: 'FR', postalCode: '1948' },
  { name: 'Bulle', canton: 'FR', postalCode: '1630' },
  { name: 'Cerniat', canton: 'FR', postalCode: '1648' },
  { name: 'Châtel-Saint-Denis', canton: 'FR', postalCode: '1618' },
  { name: 'Châtonnaye', canton: 'FR', postalCode: '1682' },
  { name: 'Cheiry', canton: 'FR', postalCode: '1533' },
  { name: 'Chevroux', canton: 'FR', postalCode: '1534' },
  { name: 'Charmey', canton: 'FR', postalCode: '1637' },
  { name: 'Chénens', canton: 'FR', postalCode: '1742' },
  { name: 'Corpataux-Magnedens', canton: 'FR', postalCode: '1693' },
  { name: 'Correvon', canton: 'FR', postalCode: '1413' },
  { name: 'Cottens', canton: 'FR', postalCode: '1723' },
  { name: 'Crésuz', canton: 'FR', postalCode: '1637' },
  { name: 'Cudrefin', canton: 'FR', postalCode: '1528' },
  { name: 'Dompierre', canton: 'FR', postalCode: '1542' },
  { name: 'Düdingen', canton: 'FR', postalCode: '3186' },
  { name: 'Echarlens', canton: 'FR', postalCode: '1646' },
  { name: 'Ecuvillens', canton: 'FR', postalCode: '1725' },
  { name: 'Ependes', canton: 'FR', postalCode: '1725' },
  { name: 'Estavayer', canton: 'FR', postalCode: '1470' },
  { name: 'Farvagny', canton: 'FR', postalCode: '1687' },
  { name: 'Fétigny', canton: 'FR', postalCode: '1544' },
  { name: 'Font', canton: 'FR', postalCode: '1606' },
  { name: 'Fribourg', canton: 'FR', postalCode: '1700' },
  { name: 'Gibloux', canton: 'FR', postalCode: '1724' },
  { name: 'Gletterens', canton: 'FR', postalCode: '1542' },
  { name: 'Grandvillard', canton: 'FR', postalCode: '1663' },
  { name: 'Granges', canton: 'FR', postalCode: '1753' },
  { name: 'Gruyères', canton: 'FR', postalCode: '1663' },
  { name: 'Guin', canton: 'FR', postalCode: '1742' },
  { name: 'Haut-Intyamon', canton: 'FR', postalCode: '1663' },
  { name: 'Heitenried', canton: 'FR', postalCode: '1717' },
  { name: 'Henniez', canton: 'FR', postalCode: '1533' },
  { name: 'La Roche', canton: 'FR', postalCode: '1638' },
  { name: 'Le Flon', canton: 'FR', postalCode: '1677' },
  { name: 'Lully', canton: 'FR', postalCode: '1522' },
  { name: 'Matran', canton: 'FR', postalCode: '1753' },
  { name: 'Mézières', canton: 'FR', postalCode: '1682' },
  { name: 'Molondin', canton: 'FR', postalCode: '1433' },
  { name: 'Morlon', canton: 'FR', postalCode: '1637' },
  { name: 'Murten', canton: 'FR', postalCode: '3280' },
  { name: 'Neyruz', canton: 'FR', postalCode: '1744' },
  { name: 'Pierrafortscha', canton: 'FR', postalCode: '1723' },
  { name: 'Plaffeien', canton: 'FR', postalCode: '1716' },
  { name: 'Plasselb', canton: 'FR', postalCode: '1737' },
  { name: 'Portalban', canton: 'FR', postalCode: '1525' },
  { name: 'Praroman', canton: 'FR', postalCode: '1742' },
  { name: 'Prez-vers-Noréaz', canton: 'FR', postalCode: '1742' },
  { name: 'Riaz', canton: 'FR', postalCode: '1637' },
  { name: 'Romont', canton: 'FR', postalCode: '1680' },
  { name: 'Rueyres-les-Prés', canton: 'FR', postalCode: '1545' },
  { name: 'Sâles', canton: 'FR', postalCode: '1670' },
  { name: 'Schmitten', canton: 'FR', postalCode: '1737' },
  { name: 'Siviriez', canton: 'FR', postalCode: '1682' },
  { name: 'Sorens', canton: 'FR', postalCode: '1678' },
  { name: 'St. Silvester', canton: 'FR', postalCode: '1742' },
  { name: 'St. Ursen', canton: 'FR', postalCode: '1718' },
  { name: 'Tafers', canton: 'FR', postalCode: '1715' },
  { name: 'Treyvaux', canton: 'FR', postalCode: '1733' },
  { name: 'Ursy', canton: 'FR', postalCode: '1682' },
  { name: 'Vallon', canton: 'FR', postalCode: '1533' },
  { name: 'Val-de-Charmey', canton: 'FR', postalCode: '1637' },
  { name: 'Villarbeney', canton: 'FR', postalCode: '1654' },
  { name: 'Villarlod', canton: 'FR', postalCode: '1677' },
  { name: 'Villars-sur-Glâne', canton: 'FR', postalCode: '1752' },
  { name: 'Villarvolard', canton: 'FR', postalCode: '1637' },
  { name: 'Villaz', canton: 'FR', postalCode: '1755' },
  { name: 'Villorsonnens', canton: 'FR', postalCode: '1682' },
  { name: 'Vuadens', canton: 'FR', postalCode: '1628' },
  { name: 'Vuisternens-devant-Romont', canton: 'FR', postalCode: '1674' },
  { name: 'Wollerau', canton: 'FR', postalCode: '1618' },

  // Additional SZ municipalities
  { name: 'Alpthal', canton: 'SZ', postalCode: '8846' },
  { name: 'Altendorf', canton: 'SZ', postalCode: '8852' },
  { name: 'Arth', canton: 'SZ', postalCode: '6414' },
  { name: 'Einsiedeln', canton: 'SZ', postalCode: '8840' },
  { name: 'Feusisberg', canton: 'SZ', postalCode: '8835' },
  { name: 'Freienbach', canton: 'SZ', postalCode: '8807' },
  { name: 'Galgenen', canton: 'SZ', postalCode: '8854' },
  { name: 'Hoch-Ybrig', canton: 'SZ', postalCode: '8846' },
  { name: 'Hurden', canton: 'SZ', postalCode: '8842' },
  { name: 'Illgau', canton: 'SZ', postalCode: '8844' },
  { name: 'Innerthal', canton: 'SZ', postalCode: '8858' },
  { name: 'Lauerz', canton: 'SZ', postalCode: '6444' },
  { name: 'Morschach', canton: 'SZ', postalCode: '6443' },
  { name: 'Muotathal', canton: 'SZ', postalCode: '6436' },
  { name: 'Oberiberg', canton: 'SZ', postalCode: '8844' },
  { name: 'Pfäffikon', canton: 'SZ', postalCode: '8808' },
  { name: 'Richterswil', canton: 'SZ', postalCode: '8805' },
  { name: 'Rothenthurm', canton: 'SZ', postalCode: '6418' },
  { name: 'Sattel', canton: 'SZ', postalCode: '6414' },
  { name: 'Schübelbach', canton: 'SZ', postalCode: '8854' },
  { name: 'Schwyz', canton: 'SZ', postalCode: '6430' },
  { name: 'Steinen', canton: 'SZ', postalCode: '6422' },
  { name: 'Steisteg', canton: 'SZ', postalCode: '8836' },
  { name: 'Unterägeri', canton: 'SZ', postalCode: '6314' },
  { name: 'Uznach', canton: 'SZ', postalCode: '8730' },
  { name: 'Vorderthal', canton: 'SZ', postalCode: '8858' },
  { name: 'Wollerau', canton: 'SZ', postalCode: '8832' },
  { name: 'Wangen', canton: 'SZ', postalCode: '8856' },

  // Additional NW municipalities
  { name: 'Beckenried', canton: 'NW', postalCode: '6375' },
  { name: 'Buochs', canton: 'NW', postalCode: '6374' },
  { name: 'Dallenwil', canton: 'NW', postalCode: '6383' },
  { name: 'Ennetbürgen', canton: 'NW', postalCode: '6373' },
  { name: 'Ennetmoos', canton: 'NW', postalCode: '6372' },
  { name: 'Hergiswil', canton: 'NW', postalCode: '6018' },
  { name: 'Oberdorf', canton: 'NW', postalCode: '6370' },
  { name: 'Stans', canton: 'NW', postalCode: '6370' },
  { name: 'Stansstad', canton: 'NW', postalCode: '6372' },
  { name: 'Wolfenschiessen', canton: 'NW', postalCode: '6386' },

  // Additional OW municipalities
  { name: 'Alpnach', canton: 'OW', postalCode: '6052' },
  { name: 'Engelberg', canton: 'OW', postalCode: '6390' },
  { name: 'Giswil', canton: 'OW', postalCode: '6074' },
  { name: 'Kerns', canton: 'OW', postalCode: '6064' },
  { name: 'Lungern', canton: 'OW', postalCode: '6078' },
  { name: 'Sachseln', canton: 'OW', postalCode: '6072' },
  { name: 'Sarnen', canton: 'OW', postalCode: '6060' },
  { name: 'Wilen bei Sarnen', canton: 'OW', postalCode: '6061' },

  // Additional GL municipalities
  { name: 'Betschwanden', canton: 'GL', postalCode: '8773' },
  { name: 'Braunwald', canton: 'GL', postalCode: '8777' },
  { name: 'Elm', canton: 'GL', postalCode: '8767' },
  { name: 'Engi', canton: 'GL', postalCode: '8765' },
  { name: 'Glarus', canton: 'GL', postalCode: '8750' },
  { name: 'Linthal', canton: 'GL', postalCode: '8775' },
  { name: 'Luchsingen', canton: 'GL', postalCode: '8774' },
  { name: 'Matt', canton: 'GL', postalCode: '8766' },
  { name: 'Mitlödi', canton: 'GL', postalCode: '8772' },
  { name: 'Näfels', canton: 'GL', postalCode: '8752' },
  { name: 'Netstal', canton: 'GL', postalCode: '8754' },
  { name: 'Niederurnen', canton: 'GL', postalCode: '8756' },
  { name: 'Oberurnen', canton: 'GL', postalCode: '8757' },
  { name: 'Riedern', canton: 'GL', postalCode: '8756' },
  { name: 'Rüti', canton: 'GL', postalCode: '8763' },
  { name: 'Schwanden', canton: 'GL', postalCode: '8762' },
  { name: 'Schännis', canton: 'GL', postalCode: '8762' },

  // Additional ZG municipalities
  { name: 'Baar', canton: 'ZG', postalCode: '6340' },
  { name: 'Cham', canton: 'ZG', postalCode: '6331' },
  { name: 'Hünenberg', canton: 'ZG', postalCode: '6331' },
  { name: 'Menzingen', canton: 'ZG', postalCode: '6313' },
  { name: 'Neuheim', canton: 'ZG', postalCode: '6345' },
  { name: 'Oberägeri', canton: 'ZG', postalCode: '6315' },
  { name: 'Risch', canton: 'ZG', postalCode: '6343' },
  { name: 'Steinhausen', canton: 'ZG', postalCode: '6312' },
  { name: 'Unterägeri', canton: 'ZG', postalCode: '6314' },
  { name: 'Walchwil', canton: 'ZG', postalCode: '6318' },
  { name: 'Zug', canton: 'ZG', postalCode: '6300' },

  // Additional UR municipalities
  { name: 'Altdorf', canton: 'UR', postalCode: '6460' },
  { name: 'Andermatt', canton: 'UR', postalCode: '6490' },
  { name: 'Attinghausen', canton: 'UR', postalCode: '6468' },
  { name: 'Bauen', canton: 'UR', postalCode: '6467' },
  { name: 'Bürglen', canton: 'UR', postalCode: '6463' },
  { name: 'Flüelen', canton: 'UR', postalCode: '6454' },
  { name: 'Göschenen', canton: 'UR', postalCode: '6487' },
  { name: 'Gurtnellen', canton: 'UR', postalCode: '6482' },
  { name: 'Hospental', canton: 'UR', postalCode: '6491' },
  { name: 'Isenthal', canton: 'UR', postalCode: '6462' },
  { name: 'Realp', canton: 'UR', postalCode: '6492' },
  { name: 'Schattdorf', canton: 'UR', postalCode: '6467' },
  { name: 'Seedorf', canton: 'UR', postalCode: '6462' },
  { name: 'Seelisberg', canton: 'UR', postalCode: '6462' },
  { name: 'Silenen', canton: 'UR', postalCode: '6473' },
  { name: 'Sisikon', canton: 'UR', postalCode: '6467' },
  { name: 'Spiringen', canton: 'UR', postalCode: '6464' },
  { name: 'Wassen', canton: 'UR', postalCode: '6483' },

  // Additional SH municipalities
  { name: 'Beringen', canton: 'SH', postalCode: '8222' },
  { name: 'Buch', canton: 'SH', postalCode: '8224' },
  { name: 'Buchberg', canton: 'SH', postalCode: '8456' },
  { name: 'Büttenhardt', canton: 'SH', postalCode: '8225' },
  { name: 'Dörflingen', canton: 'SH', postalCode: '8248' },
  { name: 'Gächlingen', canton: 'SH', postalCode: '8214' },
  { name: 'Hallau', canton: 'SH', postalCode: '8213' },
  { name: 'Hemishofen', canton: 'SH', postalCode: '8261' },
  { name: 'Herblingen', canton: 'SH', postalCode: '8212' },
  { name: 'Löhningen', canton: 'SH', postalCode: '8224' },
  { name: 'Lohn', canton: 'SH', postalCode: '8222' },
  { name: 'Merishausen', canton: 'SH', postalCode: '8232' },
  { name: 'Neuhausen am Rheinfall', canton: 'SH', postalCode: '8212' },
  { name: 'Neunkirch', canton: 'SH', postalCode: '8216' },
  { name: 'Oberhallau', canton: 'SH', postalCode: '8215' },
  { name: 'Rüdlingen', canton: 'SH', postalCode: '8463' },
  { name: 'Schaffhausen', canton: 'SH', postalCode: '8200' },
  { name: 'Schleitheim', canton: 'SH', postalCode: '8226' },
  { name: 'Siblingen', canton: 'SH', postalCode: '8226' },
  { name: 'Stein am Rhein', canton: 'SH', postalCode: '8260' },
  { name: 'Stetten', canton: 'SH', postalCode: '8213' },
  { name: 'Thayngen', canton: 'SH', postalCode: '8240' },
  { name: 'Trasadingen', canton: 'SH', postalCode: '8217' },
  { name: 'Trüllikon', canton: 'SH', postalCode: '8465' },
  { name: 'Truttingen', canton: 'SH', postalCode: '8465' },
  { name: 'Wilchingen', canton: 'SH', postalCode: '8217' },
  { name: 'Wilen', canton: 'SH', postalCode: '8459' },

  // Additional AR municipalities
  { name: 'Bühler', canton: 'AR', postalCode: '9055' },
  { name: 'Gonten', canton: 'AR', postalCode: '9104' },
  { name: 'Heiden', canton: 'AR', postalCode: '9410' },
  { name: 'Herisau', canton: 'AR', postalCode: '9100' },
  { name: 'Hundwil', canton: 'AR', postalCode: '9064' },
  { name: 'Rehetobel', canton: 'AR', postalCode: '9038' },
  { name: 'Schönengrund', canton: 'AR', postalCode: '9105' },
  { name: 'Schwellbrunn', canton: 'AR', postalCode: '9107' },
  { name: 'Speicher', canton: 'AR', postalCode: '9042' },
  { name: 'Stein', canton: 'AR', postalCode: '9063' },
  { name: 'Teufen', canton: 'AR', postalCode: '9053' },
  { name: 'Trogen', canton: 'AR', postalCode: '9043' },
  { name: 'Urnäsch', canton: 'AR', postalCode: '9102' },
  { name: 'Wald', canton: 'AR', postalCode: '9063' },
  { name: 'Waldstatt', canton: 'AR', postalCode: '9106' },
  { name: 'Uzwil', canton: 'AR', postalCode: '9240' },

  // Additional AI municipalities
  { name: 'Appenzell', canton: 'AI', postalCode: '9050' },
  { name: 'Gonten', canton: 'AI', postalCode: '9104' },
  { name: 'Schlatt-Haslen', canton: 'AI', postalCode: '9055' },
  { name: 'Schwende', canton: 'AI', postalCode: '9055' },
  { name: 'Weissbad', canton: 'AI', postalCode: '9057' },
  { name: 'Winkel', canton: 'AI', postalCode: '9058' },

  // Additional JU municipalities
  { name: 'Alle', canton: 'JU', postalCode: '2942' },
  { name: 'Bassecourt', canton: 'JU', postalCode: '2854' },
  { name: 'Beurnevésin', canton: 'JU', postalCode: '2944' },
  { name: 'Boningen', canton: 'JU', postalCode: '4627' },
  { name: 'Bonfol', canton: 'JU', postalCode: '2944' },
  { name: 'Bressaucourt', canton: 'JU', postalCode: '2900' },
  { name: 'Bure', canton: 'JU', postalCode: '2913' },
  { name: 'Charmoille', canton: 'JU', postalCode: '2921' },
  { name: 'Chevenez', canton: 'JU', postalCode: '2900' },
  { name: 'Coeuve', canton: 'JU', postalCode: '2924' },
  { name: 'Cornol', canton: 'JU', postalCode: '2912' },
  { name: 'Courgenay', canton: 'JU', postalCode: '2900' },
  { name: 'Courrendlin', canton: 'JU', postalCode: '2830' },
  { name: 'Courtételle', canton: 'JU', postalCode: '2852' },
  { name: 'Damphreux', canton: 'JU', postalCode: '2943' },
  { name: 'Delémont', canton: 'JU', postalCode: '2800' },
  { name: 'Develier', canton: 'JU', postalCode: '2802' },
  { name: 'Ederswiler', canton: 'JU', postalCode: '2827' },
  { name: 'Fahy', canton: 'JU', postalCode: '2914' },
  { name: 'Fontenais', canton: 'JU', postalCode: '2900' },
  { name: 'Glovelier', canton: 'JU', postalCode: '2855' },
  { name: 'Grandfontaine', canton: 'JU', postalCode: '2900' },
  { name: 'Haute-Sorne', canton: 'JU', postalCode: '2853' },
  { name: 'Lajoux', canton: 'JU', postalCode: '2853' },
  { name: 'Le Bémont', canton: 'JU', postalCode: '2853' },
  { name: 'Le Noirmont', canton: 'JU', postalCode: '2350' },
  { name: 'Les Bois', canton: 'JU', postalCode: '2332' },
  { name: 'Les Breuleux', canton: 'JU', postalCode: '2345' },
  { name: 'Montfaucon', canton: 'JU', postalCode: '2854' },
  { name: 'Montsevelier', canton: 'JU', postalCode: '2825' },
  { name: 'Movelier', canton: 'JU', postalCode: '2833' },
  { name: 'Pleigne', canton: 'JU', postalCode: '2833' },
  { name: 'Porrentruy', canton: 'JU', postalCode: '2900' },
  { name: 'Rebeuvelier', canton: 'JU', postalCode: '2824' },
  { name: 'Rossemaison', canton: 'JU', postalCode: '2824' },
  { name: 'Saignelégier', canton: 'JU', postalCode: '2350' },
  { name: 'Saint-Brais', canton: 'JU', postalCode: '2825' },
  { name: 'Saint-Ursanne', canton: 'JU', postalCode: '2882' },
  { name: 'Soulce', canton: 'JU', postalCode: '2825' },
  { name: 'Vermes', canton: 'JU', postalCode: '2824' },
  { name: 'Vendlincourt', canton: 'JU', postalCode: '2924' },
  { name: 'Vermes', canton: 'JU', postalCode: '2830' },

  // Additional GE municipalities
  { name: 'Anières', canton: 'GE', postalCode: '1247' },
  { name: 'Avully', canton: 'GE', postalCode: '1233' },
  { name: 'Avusy', canton: 'GE', postalCode: '1225' },
  { name: 'Bardonnex', canton: 'GE', postalCode: '1256' },
  { name: 'Bellevue', canton: 'GE', postalCode: '1258' },
  { name: 'Bernex', canton: 'GE', postalCode: '1233' },
  { name: 'Carouge', canton: 'GE', postalCode: '1227' },
  { name: 'Cartigny', canton: 'GE', postalCode: '1236' },
  { name: 'Celigny', canton: 'GE', postalCode: '1298' },
  { name: 'Chancy', canton: 'GE', postalCode: '1284' },
  { name: 'Chêne-Bougeries', canton: 'GE', postalCode: '1224' },
  { name: 'Chêne-Bourg', canton: 'GE', postalCode: '1225' },
  { name: 'Collex-Bossy', canton: 'GE', postalCode: '1239' },
  { name: 'Collonge-Bellerive', canton: 'GE', postalCode: '1245' },
  { name: 'Cologny', canton: 'GE', postalCode: '1223' },
  { name: 'Confignon', canton: 'GE', postalCode: '1232' },
  { name: 'Corsier', canton: 'GE', postalCode: '1246' },
  { name: 'Dardagny', canton: 'GE', postalCode: '1283' },
  { name: 'Genthod', canton: 'GE', postalCode: '1251' },
  { name: 'Grand-Saconnex', canton: 'GE', postalCode: '1218' },
  { name: 'Hermance', canton: 'GE', postalCode: '1248' },
  { name: 'Jussy', canton: 'GE', postalCode: '1253' },
  { name: 'Laconnex', canton: 'GE', postalCode: '1261' },
  { name: 'Lancy', canton: 'GE', postalCode: '1212' },
  { name: 'Meinier', canton: 'GE', postalCode: '1252' },
  { name: 'Meyrin', canton: 'GE', postalCode: '1217' },
  { name: 'Onex', canton: 'GE', postalCode: '1213' },
  { name: 'Perly-Certoux', canton: 'GE', postalCode: '1258' },
  { name: 'Plan-les-Ouates', canton: 'GE', postalCode: '1228' },
  { name: 'Pregny-Chambésy', canton: 'GE', postalCode: '1218' },
  { name: 'Puplinge', canton: 'GE', postalCode: '1241' },
  { name: 'Russin', canton: 'GE', postalCode: '1283' },
  { name: 'Satigny', canton: 'GE', postalCode: '1242' },
  { name: 'Soral', canton: 'GE', postalCode: '1285' },
  { name: 'Thônex', canton: 'GE', postalCode: '1226' },
  { name: 'Troinex', canton: 'GE', postalCode: '1256' },
  { name: 'Vandoeuvres', canton: 'GE', postalCode: '1253' },
  { name: 'Vernier', canton: 'GE', postalCode: '1214' },
  { name: 'Versoix', canton: 'GE', postalCode: '1290' },
  { name: 'Veyrier', canton: 'GE', postalCode: '1255' },
]

function createSlug(name: string, canton: string): string {
  return name
    .toLowerCase()
    .replace(/[àáâäæãåā]/g, 'a')
    .replace(/[èéêëēėę]/g, 'e')
    .replace(/[îïíīįì]/g, 'i')
    .replace(/[ôöòóœøōõ]/g, 'o')
    .replace(/[ûüùúū]/g, 'u')
    .replace(/[çćč]/g, 'c')
    .replace(/[ß]/g, 'ss')
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .trim() + '-' + canton.toLowerCase()
}

async function main() {
  console.log('🌍 Agregando municipios adicionales...')
  console.log('='.repeat(60))
  
  let added = 0
  let updated = 0
  let skipped = 0
  
  for (const municipality of additionalMunicipalities) {
    const canton = await prisma.canton.findUnique({
      where: { code: municipality.canton }
    })
    
    if (!canton) {
      skipped++
      continue
    }
    
    const slug = createSlug(municipality.name, municipality.canton)
    
    const existing = await prisma.city.findFirst({
      where: {
        name: municipality.name,
        cantonId: canton.id
      }
    })
    
    if (existing) {
      // Update postal code if needed
      if (municipality.postalCode && existing.postalCode !== municipality.postalCode) {
        try {
          await prisma.city.update({
            where: { id: existing.id },
            data: { 
              postalCode: municipality.postalCode,
              updatedAt: new Date()
            }
          })
          updated++
        } catch (e) {
          // Skip if error
        }
      }
      continue
    }
    
    try {
      await prisma.city.create({
        data: {
          id: `city_${Date.now()}_${Math.random().toString(36).substring(7)}`,
          name: municipality.name,
          slug: slug,
          postalCode: municipality.postalCode,
          cantonId: canton.id,
          updatedAt: new Date()
        }
      })
      added++
      if (added % 50 === 0) {
        console.log(`📊 Progreso: ${added} municipios agregados...`)
      }
    } catch (e) {
      skipped++
    }
  }
  
  console.log('')
  console.log('='.repeat(60))
  console.log('✅ SEED COMPLETADO!')
  console.log('='.repeat(60))
  console.log(`📊 Municipios agregados: ${added}`)
  console.log(`📊 Municipios actualizados: ${updated}`)
  console.log(`📊 Omitidos: ${skipped}`)
  
  const totalCount = await prisma.city.count()
  console.log(`\n📈 Total de ciudades en base de datos: ${totalCount}`)
}

main()
  .catch((e) => {
    console.error('❌ Error:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
