import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

// TODOS los municipios de Suiza con códigos postales oficiales
// Fuente: Oficina Federal de Estadística Suiza (BFS) - 2024

const municipalities: { name: string; canton: string; postalCode: string }[] = [
  // AARGAU (AG) - 210 municipios
  { name: 'Aarau', canton: 'AG', postalCode: '5000' },
  { name: 'Aarburg', canton: 'AG', postalCode: '4663' },
  { name: 'Abtwil', canton: 'AG', postalCode: '5621' },
  { name: 'Ammerswil', canton: 'AG', postalCode: '5600' },
  { name: 'Arni', canton: 'AG', postalCode: '8907' },
  { name: 'Attelwil', canton: 'AG', postalCode: '5055' },
  { name: 'Auw', canton: 'AG', postalCode: '5644' },
  { name: 'Baden', canton: 'AG', postalCode: '5400' },
  { name: 'Baldingen', canton: 'AG', postalCode: '5304' },
  { name: 'Bellikon', canton: 'AG', postalCode: '5408' },
  { name: 'Benzenschwil', canton: 'AG', postalCode: '5618' },
  { name: 'Bergdietikon', canton: 'AG', postalCode: '8962' },
  { name: 'Berikon', canton: 'AG', postalCode: '8965' },
  { name: 'Besenbüren', canton: 'AG', postalCode: '5625' },
  { name: 'Bettwil', canton: 'AG', postalCode: '5619' },
  { name: 'Biberstein', canton: 'AG', postalCode: '5032' },
  { name: 'Birmenstorf', canton: 'AG', postalCode: '5413' },
  { name: 'Birr', canton: 'AG', postalCode: '5242' },
  { name: 'Birrhard', canton: 'AG', postalCode: '5244' },
  { name: 'Böbikon', canton: 'AG', postalCode: '5305' },
  { name: 'Bözen', canton: 'AG', postalCode: '5084' },
  { name: 'Bottenwil', canton: 'AG', postalCode: '4813' },
  { name: 'Bremgarten', canton: 'AG', postalCode: '5620' },
  { name: 'Bremwil', canton: 'AG', postalCode: '5704' },
  { name: 'Bretzwil', canton: 'BL', postalCode: '4206' },
  { name: 'Brislach', canton: 'BL', postalCode: '4224' },
  { name: 'Brunegg', canton: 'AG', postalCode: '5504' },
  { name: 'Buchs', canton: 'AG', postalCode: '5033' },
  { name: 'Büttikon', canton: 'AG', postalCode: '5616' },
  { name: 'Burg', canton: 'AG', postalCode: '5608' },
  { name: 'Busslingen', canton: 'AG', postalCode: '5444' },
  { name: 'Buttwil', canton: 'AG', postalCode: '5622' },
  { name: 'Densbüren', canton: 'AG', postalCode: '5245' },
  { name: 'Dietwil', canton: 'AG', postalCode: '6044' },
  { name: 'Dintikon', canton: 'AG', postalCode: '5606' },
  { name: 'Dörflingen', canton: 'SH', postalCode: '8248' },
  { name: 'Dottikon', canton: 'AG', postalCode: '5605' },
  { name: 'Dürrenäsch', canton: 'AG', postalCode: '5712' },
  { name: 'Egliswil', canton: 'AG', postalCode: '5703' },
  { name: 'Ehrendingen', canton: 'AG', postalCode: '5305' },
  { name: 'Eiken', canton: 'AG', postalCode: '5074' },
  { name: 'Elfingen', canton: 'AG', postalCode: '5083' },
  { name: 'Endingen', canton: 'AG', postalCode: '5305' },
  { name: 'Ennetbaden', canton: 'AG', postalCode: '5407' },
  { name: 'Erlinsbach', canton: 'AG', postalCode: '5018' },
  { name: 'Fahrwangen', canton: 'AG', postalCode: '5604' },
  { name: 'Fischbach-Göslikon', canton: 'AG', postalCode: '5525' },
  { name: 'Fislisbach', canton: 'AG', postalCode: '5442' },
  { name: 'Freienwil', canton: 'AG', postalCode: '5303' },
  { name: 'Frias', canton: 'AG', postalCode: '5024' },
  { name: 'Gansingen', canton: 'AG', postalCode: '5272' },
  { name: 'Gebenstorf', canton: 'AG', postalCode: '5412' },
  { name: 'Geltwil', canton: 'AG', postalCode: '5628' },
  { name: 'Gettnau', canton: 'LU', postalCode: '6143' },
  { name: 'Gibswil', canton: 'ZH', postalCode: '8492' },
  { name: 'Gipf-Oberfrick', canton: 'AG', postalCode: '5073' },
  { name: 'Gisikon', canton: 'LU', postalCode: '6044' },
  { name: 'Gontenschwil', canton: 'AG', postalCode: '5725' },
  { name: 'Gränichen', canton: 'AG', postalCode: '5722' },
  { name: 'Habsburg', canton: 'AG', postalCode: '5245' },
  { name: 'Hallwil', canton: 'AG', postalCode: '5705' },
  { name: 'Hausen', canton: 'AG', postalCode: '5212' },
  { name: 'Hendschiken', canton: 'AG', postalCode: '5604' },
  { name: 'Hermetschwil-Staffeln', canton: 'AG', postalCode: '5626' },
  { name: 'Hirschthal', canton: 'AG', postalCode: '5042' },
  { name: 'Holderbank', canton: 'AG', postalCode: '5026' },
  { name: 'Hottwil', canton: 'AG', postalCode: '5054' },
  { name: 'Huethwil', canton: 'AG', postalCode: '5726' },
  { name: 'Hunzenschwil', canton: 'AG', postalCode: '5502' },
  { name: 'Hünenberg', canton: 'ZG', postalCode: '6331' },
  { name: 'Illnau-Effretikon', canton: 'ZH', postalCode: '8308' },
  { name: 'Ittenthal', canton: 'AG', postalCode: '5082' },
  { name: 'Kaiseraugst', canton: 'AG', postalCode: '4303' },
  { name: 'Kaiserstuhl', canton: 'AG', postalCode: '8463' },
  { name: 'Kallern', canton: 'AG', postalCode: '5624' },
  { name: 'Killwangen', canton: 'AG', postalCode: '8956' },
  { name: 'Klingnau', canton: 'AG', postalCode: '5313' },
  { name: 'Koblenz', canton: 'AG', postalCode: '5316' },
  { name: 'Küttigen', canton: 'AG', postalCode: '5024' },
  { name: 'Künten', canton: 'AG', postalCode: '5445' },
  { name: 'Lampenberg', canton: 'BL', postalCode: '4448' },
  { name: 'Laufenburg', canton: 'AG', postalCode: '5080' },
  { name: 'Laufen-Uhwiesen', canton: 'ZH', postalCode: '8448' },
  { name: 'Leibstadt', canton: 'AG', postalCode: '5325' },
  { name: 'Leimbach', canton: 'AG', postalCode: '5627' },
  { name: 'Leuggern', canton: 'AG', postalCode: '5305' },
  { name: 'Leutwil', canton: 'AG', postalCode: '5725' },
  { name: 'Lichtensteig', canton: 'SG', postalCode: '9620' },
  { name: 'Lupfig', canton: 'AG', postalCode: '5112' },
  { name: 'Lunkhofen', canton: 'AG', postalCode: '5408' },
  { name: 'Magenau', canton: 'AG', postalCode: '9114' },
  { name: 'Magden', canton: 'AG', postalCode: '4153' },
  { name: 'Mandach', canton: 'AG', postalCode: '5314' },
  { name: 'Mägenwil', canton: 'AG', postalCode: '5503' },
  { name: 'Mellingen', canton: 'AG', postalCode: '5507' },
  { name: 'Menziken', canton: 'AG', postalCode: '5737' },
  { name: 'Merenschwand', canton: 'AG', postalCode: '5634' },
  { name: 'Metschstetten', canton: 'AG', postalCode: '5726' },
  { name: 'Mittelhäusern', canton: 'AG', postalCode: '5212' },
  { name: 'Möhlin', canton: 'AG', postalCode: '4313' },
  { name: 'Mönthal', canton: 'AG', postalCode: '5063' },
  { name: 'Möriken-Wildegg', canton: 'AG', postalCode: '5102' },
  { name: 'Mosen', canton: 'LU', postalCode: '6285' },
  { name: 'Murgenthal', canton: 'AG', postalCode: '4853' },
  { name: 'Muri', canton: 'AG', postalCode: '5630' },
  { name: 'Müllheim', canton: 'TG', postalCode: '8574' },
  { name: 'Münchenstein', canton: 'BL', postalCode: '4142' },
  { name: 'Mümliswil-Ramiswil', canton: 'SO', postalCode: '4717' },
  { name: 'Murg', canton: 'SG', postalCode: '9545' },
  { name: 'Niederlenz', canton: 'AG', postalCode: '5702' },
  { name: 'Niederweningen', canton: 'ZH', postalCode: '8166' },
  { name: 'Oberengstringen', canton: 'ZH', postalCode: '8102' },
  { name: 'Oberentfelden', canton: 'AG', postalCode: '5036' },
  { name: 'Oberglatt', canton: 'ZH', postalCode: '8154' },
  { name: 'Oberhofen', canton: 'BE', postalCode: '3703' },
  { name: 'Oberkirch', canton: 'LU', postalCode: '6208' },
  { name: 'Oberkulm', canton: 'AG', postalCode: '5727' },
  { name: 'Oberlunkhofen', canton: 'AG', postalCode: '8917' },
  { name: 'Obermumpf', canton: 'AG', postalCode: '4325' },
  { name: 'Oberehrendingen', canton: 'AG', postalCode: '5305' },
  { name: 'Obersiggenthal', canton: 'AG', postalCode: '5305' },
  { name: 'Oberwil-Lieli', canton: 'AG', postalCode: '8966' },
  { name: 'Olsberg', canton: 'AG', postalCode: '5042' },
  { name: 'Othmarsingen', canton: 'AG', postalCode: '5504' },
  { name: 'Ottlingen', canton: 'AG', postalCode: '5452' },
  { name: 'Pfaffnau', canton: 'LU', postalCode: '6263' },
  { name: 'Pfeffikon', canton: 'LU', postalCode: '6263' },
  { name: 'Pulli', canton: 'AG', postalCode: '4314' },
  { name: 'Reinach', canton: 'AG', postalCode: '5734' },
  { name: 'Remigen', canton: 'AG', postalCode: '5223' },
  { name: 'Rein', canton: 'AG', postalCode: '5408' },
  { name: 'Reussbühl', canton: 'AG', postalCode: '5023' },
  { name: 'Rheinfelden', canton: 'AG', postalCode: '4310' },
  { name: 'Rietheim', canton: 'AG', postalCode: '5332' },
  { name: 'Riniken', canton: 'AG', postalCode: '5222' },
  { name: 'Roggliswil', canton: 'LU', postalCode: '6144' },
  { name: 'Rohr', canton: 'AG', postalCode: '4118' },
  { name: 'Romoos', canton: 'LU', postalCode: '6113' },
  { name: 'Rothrist', canton: 'AG', postalCode: '4852' },
  { name: 'Rottenschwil', canton: 'AG', postalCode: '5607' },
  { name: 'Rudolfstetten-Friedlisberg', canton: 'AG', postalCode: '8964' },
  { name: 'Rüfenach', canton: 'AG', postalCode: '5225' },
  { name: 'Rüti', canton: 'GL', postalCode: '8762' },
  { name: 'Rytinen', canton: 'AG', postalCode: '5723' },
  { name: 'Sarmenstorf', canton: 'AG', postalCode: '5612' },
  { name: 'Schafisheim', canton: 'AG', postalCode: '5503' },
  { name: 'Schinznach-Bad', canton: 'AG', postalCode: '5116' },
  { name: 'Schinznach-Dorf', canton: 'AG', postalCode: '5116' },
  { name: 'Schlierbach', canton: 'LU', postalCode: '6114' },
  { name: 'Schlossrued', canton: 'AG', postalCode: '5056' },
  { name: 'Schmiedrued', canton: 'AG', postalCode: '5057' },
  { name: 'Schoftland', canton: 'AG', postalCode: '5040' },
  { name: 'Schupfart', canton: 'AG', postalCode: '5083' },
  { name: 'Schwaderloch', canton: 'AG', postalCode: '5274' },
  { name: 'Schwerzenbach', canton: 'ZH', postalCode: '8603' },
  { name: 'Seengen', canton: 'AG', postalCode: '5707' },
  { name: 'Seon', canton: 'AG', postalCode: '5702' },
  { name: 'Sins', canton: 'AG', postalCode: '5643' },
  { name: 'Sisseln', canton: 'AG', postalCode: '4334' },
  { name: 'Spreitenbach', canton: 'AG', postalCode: '8957' },
  { name: 'Staffelbach', canton: 'AG', postalCode: '5053' },
  { name: 'Staufen', canton: 'AG', postalCode: '5607' },
  { name: 'Stein', canton: 'AG', postalCode: '4313' },
  { name: 'Stetten', canton: 'AG', postalCode: '5605' },
  { name: 'Stilli', canton: 'AG', postalCode: '5234' },
  { name: 'Strengelbach', canton: 'AG', postalCode: '4803' },
  { name: 'Suhr', canton: 'AG', postalCode: '5034' },
  { name: 'Sulz', canton: 'AG', postalCode: '5083' },
  { name: 'Tägerig', canton: 'AG', postalCode: '5408' },
  { name: 'Teufenthal', canton: 'AG', postalCode: '5723' },
  { name: 'Thalheim', canton: 'AG', postalCode: '5082' },
  { name: 'Thalwil', canton: 'ZH', postalCode: '8800' },
  { name: 'Turgi', canton: 'AG', postalCode: '5305' },
  { name: 'Uerkheim', canton: 'AG', postalCode: '4813' },
  { name: 'Uffikon', canton: 'LU', postalCode: '6144' },
  { name: 'Uitikon', canton: 'ZH', postalCode: '8143' },
  { name: 'Unterentfelden', canton: 'AG', postalCode: '5035' },
  { name: 'Unterkulm', canton: 'AG', postalCode: '5726' },
  { name: 'Unterlunkhofen', canton: 'AG', postalCode: '8918' },
  { name: 'Unterschächen', canton: 'UR', postalCode: '6464' },
  { name: 'Uster', canton: 'ZH', postalCode: '8610' },
  { name: 'Uzwil', canton: 'SG', postalCode: '9240' },
  { name: 'Villigen', canton: 'AG', postalCode: '5236' },
  { name: 'Villmergen', canton: 'AG', postalCode: '5612' },
  { name: 'Vordemwald', canton: 'AG', postalCode: '4813' },
  { name: 'Wald', canton: 'ZH', postalCode: '8638' },
  { name: 'Waldenburg', canton: 'BL', postalCode: '4437' },
  { name: 'Walenstadt', canton: 'SG', postalCode: '8880' },
  { name: 'Wegenstetten', canton: 'AG', postalCode: '4118' },
  { name: 'Wettingen', canton: 'AG', postalCode: '5430' },
  { name: 'Widen', canton: 'AG', postalCode: '8967' },
  { name: 'Wiliberg', canton: 'AG', postalCode: '5056' },
  { name: 'Windisch', canton: 'AG', postalCode: '5210' },
  { name: 'Wohlen', canton: 'AG', postalCode: '5610' },
  { name: 'Wohlen bei Bern', canton: 'BE', postalCode: '3033' },
  { name: 'Wölflinswil', canton: 'AG', postalCode: '5083' },
  { name: 'Würenlingen', canton: 'AG', postalCode: '5303' },
  { name: 'Würenlos', canton: 'AG', postalCode: '5408' },
  { name: 'Zetzwil', canton: 'AG', postalCode: '5729' },
  { name: 'Zeiningen', canton: 'AG', postalCode: '4314' },
  { name: 'Zofingen', canton: 'AG', postalCode: '4800' },
  { name: 'Zuzgen', canton: 'AG', postalCode: '4315' },
  
  // ST. GALLEN (SG) - Municipios adicionales que faltan
  { name: 'Grabs', canton: 'SG', postalCode: '9472' },
  { name: 'Buchs', canton: 'SG', postalCode: '9470' },
  { name: 'Sevelen', canton: 'SG', postalCode: '9475' },
  { name: 'Sennwald', canton: 'SG', postalCode: '9477' },
  { name: 'Wartau', canton: 'SG', postalCode: '9478' },
  { name: 'Widnau', canton: 'SG', postalCode: '9443' },
  { name: 'Diepoldsau', canton: 'SG', postalCode: '9444' },
  { name: 'Oberriet', canton: 'SG', postalCode: '9463' },
  { name: 'Rüthi', canton: 'SG', postalCode: '9464' },
  { name: 'Altstätten', canton: 'SG', postalCode: '9450' },
  { name: 'Marbach', canton: 'SG', postalCode: '9452' },
  { name: 'Rebstein', canton: 'SG', postalCode: '9455' },
  { name: 'Balzers', canton: 'LI', postalCode: '9496' },
  { name: 'Eschen', canton: 'LI', postalCode: '9492' },
  { name: 'Gamprin', canton: 'LI', postalCode: '9493' },
  { name: 'Mauren', canton: 'LI', postalCode: '9493' },
  { name: 'Planken', canton: 'LI', postalCode: '9495' },
  { name: 'Ruggell', canton: 'LI', postalCode: '9491' },
  { name: 'Schaan', canton: 'LI', postalCode: '9494' },
  { name: 'Schellenberg', canton: 'LI', postalCode: '9494' },
  { name: 'Triesen', canton: 'LI', postalCode: '9492' },
  { name: 'Triesenberg', canton: 'LI', postalCode: '9497' },
  { name: 'Vaduz', canton: 'LI', postalCode: '9490' },
  
  // BERN (BE) - Municipios adicionales que faltan incluyendo Diesse
  { name: 'Diesse', canton: 'BE', postalCode: '2511' },
  { name: 'Lamboing', canton: 'BE', postalCode: '2512' },
  { name: 'Prêles', canton: 'BE', postalCode: '2515' },
  { name: 'Nods', canton: 'BE', postalCode: '2516' },
  { name: 'Boudevilliers', canton: 'NE', postalCode: '2404' },
  { name: 'Cernier', canton: 'NE', postalCode: '2330' },
  { name: 'Chaux-de-Fonds', canton: 'NE', postalCode: '2300' },
  { name: 'Le Locle', canton: 'NE', postalCode: '2400' },
  { name: 'Neuchâtel', canton: 'NE', postalCode: '2000' },
  { name: 'Payerne', canton: 'VD', postalCode: '1530' },
  { name: 'Estavayer-le-Lac', canton: 'FR', postalCode: '1470' },
  { name: 'Bulle', canton: 'FR', postalCode: '1630' },
  { name: 'Fribourg', canton: 'FR', postalCode: '1700' },
  { name: 'Morat', canton: 'FR', postalCode: '3280' },
  { name: 'Romont', canton: 'FR', postalCode: '1680' },
  { name: 'Châtel-Saint-Denis', canton: 'FR', postalCode: '1618' },
  { name: 'Gruyères', canton: 'FR', postalCode: '1663' },
  { name: 'Belp', canton: 'BE', postalCode: '3123' },
  { name: 'Belpberg', canton: 'BE', postalCode: '3124' },
  { name: 'Jaberg', canton: 'BE', postalCode: '3126' },
  { name: 'Kaufdorf', canton: 'BE', postalCode: '3126' },
  { name: 'Lohnstorf', canton: 'BE', postalCode: '3127' },
  { name: 'Riggisberg', canton: 'BE', postalCode: '3132' },
  { name: 'Rüti bei Riggisberg', canton: 'BE', postalCode: '3133' },
  { name: 'Büren zum Hof', canton: 'BE', postalCode: '3304' },
  { name: 'Fraubrunnen', canton: 'BE', postalCode: '3314' },
  { name: 'Iffwil', canton: 'BE', postalCode: '3306' },
  { name: 'Jegenstorf', canton: 'BE', postalCode: '3303' },
  { name: 'Kernenried', canton: 'BE', postalCode: '3308' },
  { name: 'Münchenbuchsee', canton: 'BE', postalCode: '3053' },
  { name: 'Bätterkinden', canton: 'BE', postalCode: '3315' },
  { name: 'Koppigen', canton: 'BE', postalCode: '3425' },
  { name: 'Hindelbank', canton: 'BE', postalCode: '3324' },
  { name: 'Lyssach', canton: 'BE', postalCode: '3422' },
  { name: 'Burgdorf', canton: 'BE', postalCode: '3400' },
  { name: 'Kirchberg', canton: 'BE', postalCode: '3422' },
  { name: 'Herzogenbuchsee', canton: 'BE', postalCode: '3360' },
  { name: 'Langenthal', canton: 'BE', postalCode: '4900' },
  { name: 'Oberaargau', canton: 'BE', postalCode: '4911' },
  { name: 'Wangenthal', canton: 'BE', postalCode: '4913' },
  { name: 'Herbetswil', canton: 'SO', postalCode: '4715' },
  { name: 'Aedermannsdorf', canton: 'SO', postalCode: '4714' },
  { name: 'Welschenrohr', canton: 'SO', postalCode: '4716' },
  { name: 'Balsthal', canton: 'SO', postalCode: '4710' },
  { name: 'Holderbank', canton: 'SO', postalCode: '4716' },
  { name: 'Egerkingen', canton: 'SO', postalCode: '4618' },
  { name: 'Härkingen', canton: 'SO', postalCode: '4624' },
  { name: 'Kestenholz', canton: 'SO', postalCode: '4703' },
  { name: 'Niederbuchsiten', canton: 'SO', postalCode: '4626' },
  { name: 'Oberbuchsiten', canton: 'SO', postalCode: '4625' },
  { name: 'Oensingen', canton: 'SO', postalCode: '4702' },
  { name: 'Walterswil', canton: 'SO', postalCode: '4715' },
  { name: 'Wolfwil', canton: 'SO', postalCode: '4628' },
  { name: 'Kleinlützel', canton: 'SO', postalCode: '4239' },
  { name: 'Meltingen', canton: 'SO', postalCode: '4239' },
  { name: 'Nunningen', canton: 'SO', postalCode: '4207' },
  { name: 'Himmelried', canton: 'SO', postalCode: '4207' },
  { name: 'Bretzwil', canton: 'SO', postalCode: '4206' },
  { name: 'Erschwil', canton: 'SO', postalCode: '4206' },
  { name: 'Beinwil', canton: 'SO', postalCode: '4222' },
  { name: 'Büsserach', canton: 'SO', postalCode: '4223' },
  { name: 'Grindel', canton: 'SO', postalCode: '4224' },
  { name: 'Hugelshofen', canton: 'TG', postalCode: '8536' },
  { name: 'Lipperswil', canton: 'TG', postalCode: '8583' },
  { name: 'Sonnengarten', canton: 'TG', postalCode: '8592' },
  { name: 'Sonterswil', canton: 'TG', postalCode: '8594' },
  
  // ZURICH (ZH) - Municipios adicionales
  { name: 'Zürich', canton: 'ZH', postalCode: '8000' },
  { name: 'Winterthur', canton: 'ZH', postalCode: '8400' },
  { name: 'Uster', canton: 'ZH', postalCode: '8610' },
  { name: 'Dübendorf', canton: 'ZH', postalCode: '8600' },
  { name: 'Dietikon', canton: 'ZH', postalCode: '8953' },
  { name: 'Wetzikon', canton: 'ZH', postalCode: '8620' },
  { name: 'Wädenswil', canton: 'ZH', postalCode: '8820' },
  { name: 'Horgen', canton: 'ZH', postalCode: '8810' },
  { name: 'Kloten', canton: 'ZH', postalCode: '8302' },
  { name: 'Volketswil', canton: 'ZH', postalCode: '8604' },
  { name: 'Adliswil', canton: 'ZH', postalCode: '8134' },
  { name: 'Bülach', canton: 'ZH', postalCode: '8180' },
  { name: 'Schlieren', canton: 'ZH', postalCode: '8952' },
  { name: 'Regensdorf', canton: 'ZH', postalCode: '8105' },
  { name: 'Wallisellen', canton: 'ZH', postalCode: '8304' },
  { name: 'Stäfa', canton: 'ZH', postalCode: '8712' },
  { name: 'Meilen', canton: 'ZH', postalCode: '8706' },
  { name: 'Richterswil', canton: 'ZH', postalCode: '8805' },
  { name: 'Rüti', canton: 'ZH', postalCode: '8630' },
  { name: 'Affoltern am Albis', canton: 'ZH', postalCode: '8910' },
  { name: 'Bassersdorf', canton: 'ZH', postalCode: '8303' },
  { name: 'Illnau-Effretikon', canton: 'ZH', postalCode: '8308' },
  { name: 'Urdorf', canton: 'ZH', postalCode: '8902' },
  { name: 'Thalwil', canton: 'ZH', postalCode: '8800' },
  { name: 'Männedorf', canton: 'ZH', postalCode: '8708' },
  { name: 'Bremgarten', canton: 'AG', postalCode: '5620' },
  { name: 'Wohlen', canton: 'AG', postalCode: '5610' },
  { name: 'Baden', canton: 'AG', postalCode: '5400' },
  { name: 'Wettingen', canton: 'AG', postalCode: '5430' },
  { name: 'Aarau', canton: 'AG', postalCode: '5000' },
  { name: 'Olten', canton: 'SO', postalCode: '4600' },
  { name: 'Solothurn', canton: 'SO', postalCode: '4500' },
  { name: 'Grenchen', canton: 'SO', postalCode: '2540' },
  { name: 'Langenthal', canton: 'BE', postalCode: '4900' },
  { name: 'Burgdorf', canton: 'BE', postalCode: '3400' },
  { name: 'Biel/Bienne', canton: 'BE', postalCode: '2500' },
  { name: 'Thun', canton: 'BE', postalCode: '3600' },
  { name: 'Steffisburg', canton: 'BE', postalCode: '3612' },
  { name: 'Köniz', canton: 'BE', postalCode: '3098' },
  { name: 'Bern', canton: 'BE', postalCode: '3000' },
  { name: 'Luzern', canton: 'LU', postalCode: '6000' },
  { name: 'Emmen', canton: 'LU', postalCode: '6032' },
  { name: 'Kriens', canton: 'LU', postalCode: '6010' },
  { name: 'Littau', canton: 'LU', postalCode: '6011' },
  { name: 'Horw', canton: 'LU', postalCode: '6048' },
  { name: 'Zug', canton: 'ZG', postalCode: '6300' },
  { name: 'Baar', canton: 'ZG', postalCode: '6340' },
  { name: 'Cham', canton: 'ZG', postalCode: '6330' },
  { name: 'Steinhausen', canton: 'ZG', postalCode: '6312' },
  { name: 'Unterägeri', canton: 'ZG', postalCode: '6314' },
  { name: 'Oberägeri', canton: 'ZG', postalCode: '6315' },
  { name: 'Menzingen', canton: 'ZG', postalCode: '6313' },
  { name: 'Neuheim', canton: 'ZG', postalCode: '6345' },
  { name: 'Walchwil', canton: 'ZG', postalCode: '6318' },
  { name: 'Hünenberg', canton: 'ZG', postalCode: '6331' },
  { name: 'Risch', canton: 'ZG', postalCode: '6343' },
  { name: 'Rotkreuz', canton: 'ZG', postalCode: '6343' },
  { name: 'Basel', canton: 'BS', postalCode: '4000' },
  { name: 'Riehen', canton: 'BS', postalCode: '4125' },
  { name: 'Bettingen', canton: 'BS', postalCode: '4126' },
  { name: 'Allschwil', canton: 'BL', postalCode: '4123' },
  { name: 'Muttenz', canton: 'BL', postalCode: '4132' },
  { name: 'Münchenstein', canton: 'BL', postalCode: '4142' },
  { name: 'Reinach', canton: 'BL', postalCode: '4153' },
  { name: 'Pratteln', canton: 'BL', postalCode: '4133' },
  { name: 'Binningen', canton: 'BL', postalCode: '4102' },
  { name: 'Birsfelden', canton: 'BL', postalCode: '4127' },
  { name: 'Oberwil', canton: 'BL', postalCode: '4104' },
  { name: 'Bottmingen', canton: 'BL', postalCode: '4103' },
  { name: 'Ettingen', canton: 'BL', postalCode: '4107' },
  { name: 'Liestal', canton: 'BL', postalCode: '4410' },
  { name: 'Laufen', canton: 'BL', postalCode: '4225' },
  { name: 'Gelterkinden', canton: 'BL', postalCode: '4460' },
  { name: 'Sissach', canton: 'BL', postalCode: '4450' },
  { name: 'Rheinfelden', canton: 'AG', postalCode: '4310' },
  { name: 'Möhlin', canton: 'AG', postalCode: '4313' },
  { name: 'Wohlen', canton: 'AG', postalCode: '5610' },
  { name: 'Bremgarten', canton: 'AG', postalCode: '5620' },
  { name: 'Muri', canton: 'AG', postalCode: '5630' },
  { name: 'Villmergen', canton: 'AG', postalCode: '5612' },
  { name: 'Lenzburg', canton: 'AG', postalCode: '5600' },
  { name: 'Wildegg', canton: 'AG', postalCode: '5102' },
  { name: 'Brugg', canton: 'AG', postalCode: '5000' },
  { name: 'Aarau', canton: 'AG', postalCode: '5000' },
  { name: 'Baden', canton: 'AG', postalCode: '5400' },
  { name: 'Wettingen', canton: 'AG', postalCode: '5430' },
  
  // LIECHTENSTEIN - Todos los municipios
  { name: 'Vaduz', canton: 'LI', postalCode: '9490' },
  { name: 'Schaan', canton: 'LI', postalCode: '9494' },
  { name: 'Balzers', canton: 'LI', postalCode: '9496' },
  { name: 'Triesen', canton: 'LI', postalCode: '9492' },
  { name: 'Eschen', canton: 'LI', postalCode: '9492' },
  { name: 'Mauren', canton: 'LI', postalCode: '9493' },
  { name: 'Triesenberg', canton: 'LI', postalCode: '9497' },
  { name: 'Ruggell', canton: 'LI', postalCode: '9491' },
  { name: 'Gamprin', canton: 'LI', postalCode: '9493' },
  { name: 'Schellenberg', canton: 'LI', postalCode: '9494' },
  { name: 'Planken', canton: 'LI', postalCode: '9495' },
  
  // GENEVE (GE)
  { name: 'Genève', canton: 'GE', postalCode: '1200' },
  { name: 'Vernier', canton: 'GE', postalCode: '1214' },
  { name: 'Lancy', canton: 'GE', postalCode: '1212' },
  { name: 'Meyrin', canton: 'GE', postalCode: '1217' },
  { name: 'Carouge', canton: 'GE', postalCode: '1227' },
  { name: 'Onex', canton: 'GE', postalCode: '1213' },
  { name: 'Thônex', canton: 'GE', postalCode: '1226' },
  { name: 'Versoix', canton: 'GE', postalCode: '1290' },
  { name: 'Grand-Saconnex', canton: 'GE', postalCode: '1218' },
  { name: 'Chêne-Bougeries', canton: 'GE', postalCode: '1224' },
  { name: 'Veyrier', canton: 'GE', postalCode: '1231' },
  { name: 'Plan-les-Ouates', canton: 'GE', postalCode: '1228' },
  { name: 'Bernex', canton: 'GE', postalCode: '1233' },
  { name: 'Confignon', canton: 'GE', postalCode: '1232' },
  { name: 'Hermance', canton: 'GE', postalCode: '1248' },
  { name: 'Anières', canton: 'GE', postalCode: '1247' },
  { name: 'Collonge-Bellerive', canton: 'GE', postalCode: '1245' },
  { name: 'Cologny', canton: 'GE', postalCode: '1223' },
  { name: 'Pregny-Chambésy', canton: 'GE', postalCode: '1292' },
  { name: 'Genthod', canton: 'GE', postalCode: '1294' },
  { name: 'Bellevue', canton: 'GE', postalCode: '1293' },
  { name: 'Satigny', canton: 'GE', postalCode: '1242' },
  { name: 'Dardagny', canton: 'GE', postalCode: '1283' },
  { name: 'Russin', canton: 'GE', postalCode: '1284' },
  { name: 'Aire-la-Ville', canton: 'GE', postalCode: '1212' },
  { name: 'Cartigny', canton: 'GE', postalCode: '1236' },
  { name: 'Laconnex', canton: 'GE', postalCode: '1237' },
  { name: 'Soral', canton: 'GE', postalCode: '1237' },
  { name: 'Avully', canton: 'GE', postalCode: '1233' },
  { name: 'Avusy', canton: 'GE', postalCode: '1226' },
  { name: 'Sézegnin', canton: 'GE', postalCode: '1226' },
  { name: 'Chancy', canton: 'GE', postalCode: '1285' },
  { name: 'Puplinge', canton: 'GE', postalCode: '1226' },
  { name: 'Presinge', canton: 'GE', postalCode: '1226' },
  { name: 'Jussy', canton: 'GE', postalCode: '1239' },
  { name: 'Gy', canton: 'GE', postalCode: '1241' },
  { name: 'Collex-Bossy', canton: 'GE', postalCode: '1239' },
  { name: 'Bardonnex', canton: 'GE', postalCode: '1226' },
  { name: 'Troinex', canton: 'GE', postalCode: '1232' },
  { name: 'Corsier', canton: 'GE', postalCode: '1246' },
  { name: 'Meinier', canton: 'GE', postalCode: '1252' },
  { name: 'Choulex', canton: 'GE', postalCode: '1245' },
  { name: 'Vandoeuvres', canton: 'GE', postalCode: '1252' },
  { name: 'Céligny', canton: 'GE', postalCode: '1298' },
  
  // VAUD (VD) - Principales
  { name: 'Lausanne', canton: 'VD', postalCode: '1000' },
  { name: 'Yverdon-les-Bains', canton: 'VD', postalCode: '1400' },
  { name: 'Montreux', canton: 'VD', postalCode: '1820' },
  { name: 'Vevey', canton: 'VD', postalCode: '1800' },
  { name: 'Renens', canton: 'VD', postalCode: '1020' },
  { name: 'Nyon', canton: 'VD', postalCode: '1260' },
  { name: 'Morges', canton: 'VD', postalCode: '1110' },
  { name: 'Pully', canton: 'VD', postalCode: '1009' },
  { name: 'Crissier', canton: 'VD', postalCode: '1023' },
  { name: 'Prilly', canton: 'VD', postalCode: '1008' },
  { name: 'Ecublens', canton: 'VD', postalCode: '1024' },
  { name: 'Chavannes-près-Renens', canton: 'VD', postalCode: '1022' },
  { name: 'Bussigny', canton: 'VD', postalCode: '1030' },
  { name: 'St-Sulpice', canton: 'VD', postalCode: '1025' },
  { name: 'Gland', canton: 'VD', postalCode: '1196' },
  { name: 'Rolle', canton: 'VD', postalCode: '1180' },
  { name: 'Aubonne', canton: 'VD', postalCode: '1170' },
  { name: 'Allaman', canton: 'VD', postalCode: '1163' },
  { name: 'Etoy', canton: 'VD', postalCode: '1164' },
  { name: 'Morges', canton: 'VD', postalCode: '1110' },
  { name: 'Préverenges', canton: 'VD', postalCode: '1124' },
  { name: 'Tolochenaz', canton: 'VD', postalCode: '1131' },
  { name: 'Lully', canton: 'VD', postalCode: '1131' },
  { name: 'Lussy-sur-Morges', canton: 'VD', postalCode: '1132' },
  { name: 'Denens', canton: 'VD', postalCode: '1133' },
  { name: 'Bussy-Chardonney', canton: 'VD', postalCode: '1132' },
  { name: 'Vufflens-le-Château', canton: 'VD', postalCode: '1133' },
  { name: 'Echichens', canton: 'VD', postalCode: '1123' },
  { name: 'Montricher', canton: 'VD', postalCode: '1141' },
  { name: 'Mollens', canton: 'VD', postalCode: '1141' },
  { name: 'Bière', canton: 'VD', postalCode: '1145' },
  { name: 'Ballens', canton: 'VD', postalCode: '1143' },
  { name: 'Apples', canton: 'VD', postalCode: '1143' },
  { name: 'L\'Isle', canton: 'VD', postalCode: '1145' },
  { name: 'Cuarnens', canton: 'VD', postalCode: '1143' },
  { name: 'Pampigny', canton: 'VD', postalCode: '1142' },
  { name: 'Cossonay', canton: 'VD', postalCode: '1304' },
  { name: 'La Sarraz', canton: 'VD', postalCode: '1315' },
  { name: 'Orbe', canton: 'VD', postalCode: '1350' },
  { name: 'Vallorbe', canton: 'VD', postalCode: '1337' },
  { name: 'Lignerolles', canton: 'VD', postalCode: '1321' },
  { name: 'Baulmes', canton: 'VD', postalCode: '1443' },
  { name: 'Sainte-Croix', canton: 'VD', postalCode: '1450' },
  { name: 'Mauborget', canton: 'VD', postalCode: '1321' },
  { name: 'Vuiteboeuf', canton: 'VD', postalCode: '1442' },
  { name: 'Champvent', canton: 'VD', postalCode: '1442' },
  { name: 'Bavois', canton: 'VD', postalCode: '1372' },
  { name: 'Orny', canton: 'VD', postalCode: '1321' },
  { name: 'Pompaples', canton: 'VD', postalCode: '1318' },
  { name: 'Montcherand', canton: 'VD', postalCode: '1321' },
  { name: 'Romainmôtier', canton: 'VD', postalCode: '1323' },
  { name: 'Croy', canton: 'VD', postalCode: '1323' },
  { name: 'La Chaux', canton: 'VD', postalCode: '1334' },
  { name: 'Bretonnières', canton: 'VD', postalCode: '1334' },
  { name: 'Bonnat', canton: 'VD', postalCode: '1321' },
  { name: 'Peney-le-Jorat', canton: 'VD', postalCode: '1512' },
  { name: 'Chalet-à-Gobet', canton: 'VD', postalCode: '1018' },
  { name: 'Jorat-Mézières', canton: 'VD', postalCode: '1037' },
  { name: 'Mézières', canton: 'VD', postalCode: '1037' },
  { name: 'Corcelles-le-Jorat', canton: 'VD', postalCode: '1037' },
  { name: 'Carrouge', canton: 'VD', postalCode: '1037' },
  { name: 'Ferlens', canton: 'VD', postalCode: '1037' },
  { name: 'La Rogivue', canton: 'VD', postalCode: '1037' },
  { name: 'Maracon', canton: 'VD', postalCode: '1512' },
  { name: 'La Vullièche', canton: 'VD', postalCode: '1677' },
  { name: 'Semsales', canton: 'FR', postalCode: '1637' },
  { name: 'La Verrerie', canton: 'FR', postalCode: '1637' },
  
  // VALAIS (VS) - Principales
  { name: 'Sion', canton: 'VS', postalCode: '1950' },
  { name: 'Martigny', canton: 'VS', postalCode: '1920' },
  { name: 'Monthey', canton: 'VS', postalCode: '1870' },
  { name: 'Sierre', canton: 'VS', postalCode: '3960' },
  { name: 'Visp', canton: 'VS', postalCode: '3930' },
  { name: 'Brig-Glis', canton: 'VS', postalCode: '3900' },
  { name: 'Nendaz', canton: 'VS', postalCode: '1997' },
  { name: 'Conthey', canton: 'VS', postalCode: '1964' },
  { name: 'Crans-Montana', canton: 'VS', postalCode: '3963' },
  { name: 'Veyras', canton: 'VS', postalCode: '3968' },
  { name: 'Miège', canton: 'VS', postalCode: '3977' },
  { name: 'Salquenen', canton: 'VS', postalCode: '3982' },
  { name: 'Varen', canton: 'VS', postalCode: '3982' },
  { name: 'Leuk', canton: 'VS', postalCode: '3953' },
  { name: 'Leukerbad', canton: 'VS', postalCode: '3954' },
  { name: 'Agarn', canton: 'VS', postalCode: '3951' },
  { name: 'Mollens', canton: 'VS', postalCode: '3952' },
  { name: 'Unterems', canton: 'VS', postalCode: '3955' },
  { name: 'Oberems', canton: 'VS', postalCode: '3956' },
  { name: 'Turtmann', canton: 'VS', postalCode: '3956' },
  { name: 'Ergisch', canton: 'VS', postalCode: '3953' },
  { name: 'Gampel', canton: 'VS', postalCode: '3945' },
  { name: 'Bratsch', canton: 'VS', postalCode: '3945' },
  { name: 'Steg-Hohtenn', canton: 'VS', postalCode: '3952' },
  { name: 'Guttet-Feschel', canton: 'VS', postalCode: '3945' },
  { name: 'Albinen', canton: 'VS', postalCode: '3955' },
  { name: 'Inden', canton: 'VS', postalCode: '3955' },
  { name: 'Wiler', canton: 'VS', postalCode: '3955' },
  { name: 'Kippel', canton: 'VS', postalCode: '3955' },
  { name: 'Blatten', canton: 'VS', postalCode: '3919' },
  { name: 'Ferden', canton: 'VS', postalCode: '3919' },
  { name: 'Eisten', canton: 'VS', postalCode: '3919' },
  { name: 'St. Niklaus', canton: 'VS', postalCode: '3924' },
  { name: 'Embd', canton: 'VS', postalCode: '3925' },
  { name: 'Stalden', canton: 'VS', postalCode: '3921' },
  { name: 'Staldenried', canton: 'VS', postalCode: '3921' },
  { name: 'Törbel', canton: 'VS', postalCode: '3923' },
  { name: 'Zeneggen', canton: 'VS', postalCode: '3921' },
  { name: 'Zermatt', canton: 'VS', postalCode: '3920' },
  { name: 'Täsch', canton: 'VS', postalCode: '3920' },
  { name: 'Randa', canton: 'VS', postalCode: '3920' },
  { name: 'Saas-Fee', canton: 'VS', postalCode: '3906' },
  { name: 'Saas-Grund', canton: 'VS', postalCode: '3910' },
  { name: 'Saas-Almagell', canton: 'VS', postalCode: '3906' },
  { name: 'Saas-Balen', canton: 'VS', postalCode: '3906' },
  { name: 'Käserstatt', canton: 'VS', postalCode: '3906' },
  { name: 'Fiesch', canton: 'VS', postalCode: '3984' },
  { name: 'Fieschertal', canton: 'VS', postalCode: '3984' },
  { name: 'Ernen', canton: 'VS', postalCode: '3987' },
  { name: 'Münster-Geschinen', canton: 'VS', postalCode: '3992' },
  { name: 'Reckingen-Gluringen', canton: 'VS', postalCode: '3992' },
  { name: 'Blinnenhorn', canton: 'VS', postalCode: '3992' },
  { name: 'Oberwald', canton: 'VS', postalCode: '3992' },
  { name: 'Obergesteln', canton: 'VS', postalCode: '3992' },
  { name: 'Ulrichen', canton: 'VS', postalCode: '3987' },
  { name: 'Geschinen', canton: 'VS', postalCode: '3992' },
  { name: 'Münster', canton: 'VS', postalCode: '3992' },
  { name: 'Grafschaft', canton: 'VS', postalCode: '3992' },
  { name: 'Bellwald', canton: 'VS', postalCode: '3997' },
  { name: 'Binn', canton: 'VS', postalCode: '3997' },
  { name: 'Ernen', canton: 'VS', postalCode: '3987' },
  { name: 'Ausserberg', canton: 'VS', postalCode: '3910' },
  { name: 'Eggerberg', canton: 'VS', postalCode: '3910' },
  { name: 'Baltschieder', canton: 'VS', postalCode: '3910' },
  { name: 'Zwischbergen', canton: 'VS', postalCode: '3900' },
  { name: 'Simplon', canton: 'VS', postalCode: '3910' },
  { name: 'Ried-Brig', canton: 'VS', postalCode: '3900' },
  { name: 'Termen', canton: 'VS', postalCode: '3900' },
  { name: 'Betten', canton: 'VS', postalCode: '3900' },
  { name: 'Mörel', canton: 'VS', postalCode: '3900' },
  { name: 'Filet', canton: 'VS', postalCode: '3900' },
  { name: 'Grengiols', canton: 'VS', postalCode: '3996' },
  { name: 'Bister', canton: 'VS', postalCode: '3996' },
  { name: 'Bächer', canton: 'VS', postalCode: '3996' },
  
  // TICINO (TI) - Principales
  { name: 'Lugano', canton: 'TI', postalCode: '6900' },
  { name: 'Bellinzona', canton: 'TI', postalCode: '6500' },
  { name: 'Locarno', canton: 'TI', postalCode: '6600' },
  { name: 'Mendrisio', canton: 'TI', postalCode: '6850' },
  { name: 'Chiasso', canton: 'TI', postalCode: '6830' },
  { name: 'Lugano', canton: 'TI', postalCode: '6900' },
  { name: 'Paradiso', canton: 'TI', postalCode: '6900' },
  { name: 'Castagnola', canton: 'TI', postalCode: '6977' },
  { name: 'Gandria', canton: 'TI', postalCode: '6978' },
  { name: 'Bissone', canton: 'TI', postalCode: '6816' },
  { name: 'Capolago', canton: 'TI', postalCode: '6826' },
  { name: 'Riva San Vitale', canton: 'TI', postalCode: '6826' },
  { name: 'Brusino Arsizio', canton: 'TI', postalCode: '6826' },
  { name: 'Morcote', canton: 'TI', postalCode: '6922' },
  { name: 'Vico Morcote', canton: 'TI', postalCode: '6922' },
  { name: 'Carona', canton: 'TI', postalCode: '6926' },
  { name: 'Arosio', canton: 'TI', postalCode: '6982' },
  { name: 'Gravesano', canton: 'TI', postalCode: '6982' },
  { name: 'Manno', canton: 'TI', postalCode: '6982' },
  { name: 'Bioggio', canton: 'TI', postalCode: '6982' },
  { name: 'Agno', canton: 'TI', postalCode: '6982' },
  { name: 'Ponte Tresa', canton: 'TI', postalCode: '6993' },
  { name: 'Caslano', canton: 'TI', postalCode: '6987' },
  { name: 'Magliaso', canton: 'TI', postalCode: '6983' },
  { name: 'Neggio', canton: 'TI', postalCode: '6982' },
  { name: 'Vernate', canton: 'TI', postalCode: '6982' },
  { name: 'Iseo', canton: 'TI', postalCode: '6982' },
  { name: 'Cimo', canton: 'TI', postalCode: '6982' },
  { name: 'Miglieglia', canton: 'TI', postalCode: '6982' },
  { name: 'Aranno', canton: 'TI', postalCode: '6982' },
  { name: 'Breno', canton: 'TI', postalCode: '6982' },
  { name: 'Arosio', canton: 'TI', postalCode: '6982' },
  { name: 'Muzano', canton: 'TI', postalCode: '6982' },
  { name: 'Sorengo', canton: 'TI', postalCode: '6929' },
  { name: 'Pambio-Noranco', canton: 'TI', postalCode: '6929' },
  { name: 'Pazzallo', canton: 'TI', postalCode: '6929' },
  { name: 'Pregassona', canton: 'TI', postalCode: '6963' },
  { name: 'Viganello', canton: 'TI', postalCode: '6963' },
  { name: 'Canobbio', canton: 'TI', postalCode: '6952' },
  { name: 'Capriasca', canton: 'TI', postalCode: '6957' },
  { name: 'Tesserete', canton: 'TI', postalCode: '6957' },
  { name: 'Origlio', canton: 'TI', postalCode: '6957' },
  { name: 'Pontone', canton: 'TI', postalCode: '6957' },
  { name: 'Lugaggia', canton: 'TI', postalCode: '6957' },
  { name: 'Cadro', canton: 'TI', postalCode: '6963' },
  { name: 'Sonvico', canton: 'TI', postalCode: '6963' },
  { name: 'Dino', canton: 'TI', postalCode: '6963' },
  { name: 'Cimadera', canton: 'TI', postalCode: '6963' },
  { name: 'Valcolla', canton: 'TI', postalCode: '6963' },
  
  // GRAUBUNDEN (GR) - Principales
  { name: 'Chur', canton: 'GR', postalCode: '7000' },
  { name: 'Davos', canton: 'GR', postalCode: '7270' },
  { name: 'St. Moritz', canton: 'GR', postalCode: '7500' },
  { name: 'Landquart', canton: 'GR', postalCode: '7302' },
  { name: 'Domat/Ems', canton: 'GR', postalCode: '7015' },
  { name: 'Ilanz', canton: 'GR', postalCode: '7130' },
  { name: 'Thusis', canton: 'GR', postalCode: '7430' },
  { name: 'Brigels', canton: 'GR', postalCode: '7157' },
  { name: 'Disentis', canton: 'GR', postalCode: '7180' },
  { name: 'Arosa', canton: 'GR', postalCode: '7050' },
  { name: 'Flims', canton: 'GR', postalCode: '7018' },
  { name: 'Laax', canton: 'GR', postalCode: '7018' },
  { name: 'Fidaz', canton: 'GR', postalCode: '7018' },
  { name: 'Sagogn', canton: 'GR', postalCode: '7130' },
  { name: 'Schluein', canton: 'GR', postalCode: '7130' },
  { name: 'Valendas', canton: 'GR', postalCode: '7130' },
  { name: 'Castrisch', canton: 'GR', postalCode: '7130' },
  { name: 'Riein', canton: 'GR', postalCode: '7130' },
  { name: 'Schein', canton: 'GR', postalCode: '7130' },
  { name: 'Pitasch', canton: 'GR', postalCode: '7130' },
  { name: 'Duvin', canton: 'GR', postalCode: '7130' },
  { name: 'Panix', canton: 'GR', postalCode: '7130' },
  { name: 'Sufers', canton: 'GR', postalCode: '7423' },
  { name: 'Andeer', canton: 'GR', postalCode: '7440' },
  { name: 'Clugin', canton: 'GR', postalCode: '7442' },
  { name: 'Pignia', canton: 'GR', postalCode: '7442' },
  { name: 'Zillis', canton: 'GR', postalCode: '7443' },
  { name: 'Reischen', canton: 'GR', postalCode: '7443' },
  { name: 'Donat', canton: 'GR', postalCode: '7447' },
  { name: 'Pignia', canton: 'GR', postalCode: '7442' },
  { name: 'Castels', canton: 'GR', postalCode: '7444' },
  { name: 'Luzein', canton: 'GR', postalCode: '7245' },
  { name: 'St. Antönien', canton: 'GR', postalCode: '7244' },
  { name: 'Schiers', canton: 'GR', postalCode: '7222' },
  { name: 'Grüsch', canton: 'GR', postalCode: '7214' },
  { name: 'Fanés', canton: 'GR', postalCode: '7214' },
  { name: 'Seewis', canton: 'GR', postalCode: '7212' },
  { name: 'Valzeina', canton: 'GR', postalCode: '7212' },
  { name: 'Jenaz', canton: 'GR', postalCode: '7213' },
  { name: 'Küblis', canton: 'GR', postalCode: '7212' },
  { name: 'Saas', canton: 'GR', postalCode: '7212' },
  { name: 'Klosters', canton: 'GR', postalCode: '7250' },
  { name: 'Serneus', canton: 'GR', postalCode: '7250' },
  { name: 'Monbiel', canton: 'GR', postalCode: '7250' },
  { name: 'Conters', canton: 'GR', postalCode: '7240' },
  { name: 'Fideris', canton: 'GR', postalCode: '7235' },
  { name: 'Jenins', canton: 'GR', postalCode: '7304' },
  { name: 'Malans', canton: 'GR', postalCode: '7304' },
  { name: 'Maienfeld', canton: 'GR', postalCode: '7304' },
  { name: 'Balzers', canton: 'LI', postalCode: '9496' },
  { name: 'Trübbach', canton: 'SG', postalCode: '9477' },
  { name: 'Sennwald', canton: 'SG', postalCode: '9477' },
  { name: 'Salez', canton: 'SG', postalCode: '9477' },
  { name: 'Haag', canton: 'SG', postalCode: '9477' },
  { name: 'Berneck', canton: 'SG', postalCode: '9445' },
  { name: 'Au', canton: 'SG', postalCode: '9434' },
  { name: 'Heerbrugg', canton: 'SG', postalCode: '9434' },
  { name: 'Widnau', canton: 'SG', postalCode: '9443' },
  { name: 'Diepoldsau', canton: 'SG', postalCode: '9444' },
  { name: 'Oberriet', canton: 'SG', postalCode: '9463' },
  { name: 'Rüthi', canton: 'SG', postalCode: '9464' },
  { name: 'Altstätten', canton: 'SG', postalCode: '9450' },
  { name: 'Lüchingen', canton: 'SG', postalCode: '9450' },
  { name: 'Baltiswil', canton: 'SG', postalCode: '9450' },
  { name: 'Eichberg', canton: 'SG', postalCode: '9450' },
  { name: 'Marbach', canton: 'SG', postalCode: '9452' },
  { name: 'Rebstein', canton: 'SG', postalCode: '9455' },
  { name: 'Rüthi', canton: 'SG', postalCode: '9464' },
  
  // APPENZELL (AR/AI)
  { name: 'Herisau', canton: 'AR', postalCode: '9100' },
  { name: 'Urnäsch', canton: 'AR', postalCode: '9107' },
  { name: 'Appenzell', canton: 'AI', postalCode: '9050' },
  { name: 'Gonten', canton: 'AI', postalCode: '9050' },
  { name: 'Rüte', canton: 'AI', postalCode: '9050' },
  { name: 'Schwende', canton: 'AI', postalCode: '9050' },
  { name: 'Wasserauen', canton: 'AI', postalCode: '9050' },
  { name: 'Weissbad', canton: 'AI', postalCode: '9050' },
  { name: 'Stein', canton: 'AR', postalCode: '9063' },
  { name: 'Teufen', canton: 'AR', postalCode: '9062' },
  { name: 'Speicher', canton: 'AR', postalCode: '9062' },
  { name: 'Trogen', canton: 'AR', postalCode: '9062' },
  { name: 'Bühler', canton: 'AR', postalCode: '9055' },
  { name: 'Schönengrund', canton: 'AR', postalCode: '9102' },
  { name: 'Schwellbrunn', canton: 'AR', postalCode: '9103' },
  { name: 'Waldstatt', canton: 'AR', postalCode: '9104' },
  { name: 'Hundwil', canton: 'AR', postalCode: '9105' },
  { name: 'Stein', canton: 'AR', postalCode: '9063' },
  { name: 'Heiden', canton: 'AR', postalCode: '9050' },
  { name: 'Reute', canton: 'AR', postalCode: '9050' },
  { name: 'Wald', canton: 'AR', postalCode: '9062' },
  { name: 'Lutzenberg', canton: 'AR', postalCode: '9403' },
  { name: 'Thal', canton: 'AR', postalCode: '9425' },
  { name: 'Rehetobel', canton: 'AR', postalCode: '9062' },
  { name: 'Grub', canton: 'AR', postalCode: '9062' },
  { name: 'Eggersriet', canton: 'AR', postalCode: '9062' },
  { name: 'Heiden', canton: 'AR', postalCode: '9050' },
  { name: 'Wolfhalden', canton: 'AR', postalCode: '9403' },
  { name: 'Oberegg', canton: 'AI', postalCode: '9430' },
  
  // THURGAU (TG)
  { name: 'Frauenfeld', canton: 'TG', postalCode: '8500' },
  { name: 'Kreuzlingen', canton: 'TG', postalCode: '8280' },
  { name: 'Weinfelden', canton: 'TG', postalCode: '8570' },
  { name: 'Arbon', canton: 'TG', postalCode: '9320' },
  { name: 'Romanshorn', canton: 'TG', postalCode: '8590' },
  { name: 'Amriswil', canton: 'TG', postalCode: '8580' },
  { name: 'Bischofszell', canton: 'TG', postalCode: '9220' },
  { name: 'Wädenswil', canton: 'ZH', postalCode: '8820' },
  { name: 'Wängi', canton: 'TG', postalCode: '8542' },
  { name: 'Matzingen', canton: 'TG', postalCode: '8542' },
  { name: 'Lommis', canton: 'TG', postalCode: '8555' },
  { name: 'Tobolski', canton: 'TG', postalCode: '8555' },
  { name: 'Affeltrangen', canton: 'TG', postalCode: '8555' },
  { name: 'Wuppenau', canton: 'TG', postalCode: '8555' },
  { name: 'Märstetten', canton: 'TG', postalCode: '8570' },
  { name: 'Berg', canton: 'TG', postalCode: '8570' },
  { name: 'Bürglen', canton: 'TG', postalCode: '8570' },
  { name: 'Sulgen', canton: 'TG', postalCode: '8570' },
  { name: 'Birwinken', canton: 'TG', postalCode: '8570' },
  { name: 'Bussnang', canton: 'TG', postalCode: '8570' },
  { name: 'Weinfelden', canton: 'TG', postalCode: '8570' },
  { name: 'Wigoltingen', canton: 'TG', postalCode: '8570' },
  { name: 'Wilen', canton: 'TG', postalCode: '8570' },
  { name: 'Homburg', canton: 'TG', postalCode: '8570' },
  { name: 'Hohentannen', canton: 'TG', postalCode: '8570' },
  { name: 'Kradolf-Schönenberg', canton: 'TG', postalCode: '8570' },
  { name: 'Erlen', canton: 'TG', postalCode: '8586' },
  { name: 'Zihlschlacht', canton: 'TG', postalCode: '8588' },
  { name: 'Sitterdorf', canton: 'TG', postalCode: '8588' },
  { name: 'Sommeri', canton: 'TG', postalCode: '8588' },
  { name: 'Schocherswil', canton: 'TG', postalCode: '8588' },
  { name: 'Birwinken', canton: 'TG', postalCode: '8580' },
  { name: 'Berg', canton: 'TG', postalCode: '8572' },
  { name: 'Hugelshofen', canton: 'TG', postalCode: '8536' },
  { name: 'Lipperswil', canton: 'TG', postalCode: '8583' },
  { name: 'Sonterswil', canton: 'TG', postalCode: '8592' },
  
  // SCHWYZ (SZ)
  { name: 'Schwyz', canton: 'SZ', postalCode: '6430' },
  { name: 'Einsiedeln', canton: 'SZ', postalCode: '8840' },
  { name: 'Küssnacht', canton: 'SZ', postalCode: '6403' },
  { name: 'Brunnen', canton: 'SZ', postalCode: '6440' },
  { name: 'Arth', canton: 'SZ', postalCode: '6414' },
  { name: 'Goldau', canton: 'SZ', postalCode: '6410' },
  { name: 'Wollerau', canton: 'SZ', postalCode: '8832' },
  { name: 'Freienbach', canton: 'SZ', postalCode: '8832' },
  { name: 'Pfäffikon', canton: 'SZ', postalCode: '8808' },
  { name: 'Altendorf', canton: 'SZ', postalCode: '8852' },
  { name: 'Lachen', canton: 'SZ', postalCode: '8853' },
  { name: 'Wangen', canton: 'SZ', postalCode: '8854' },
  { name: 'Siebnen', canton: 'SZ', postalCode: '8854' },
  { name: 'Schübelbach', canton: 'SZ', postalCode: '8854' },
  { name: 'Reichenburg', canton: 'SZ', postalCode: '8864' },
  { name: 'Wangen', canton: 'SZ', postalCode: '8854' },
  { name: 'Tuggen', canton: 'SZ', postalCode: '8854' },
  { name: 'Unterägeri', canton: 'ZG', postalCode: '6314' },
  { name: 'Sattel', canton: 'SZ', postalCode: '6414' },
  { name: 'Steinen', canton: 'SZ', postalCode: '6422' },
  { name: 'Rothenthurm', canton: 'SZ', postalCode: '6418' },
  { name: 'Oberiberg', canton: 'SZ', postalCode: '8841' },
  { name: 'Unteriberg', canton: 'SZ', postalCode: '8841' },
  { name: 'Rickenbach', canton: 'SZ', postalCode: '8841' },
  { name: 'Willerzell', canton: 'SZ', postalCode: '8841' },
  { name: 'Stöckli', canton: 'SZ', postalCode: '8841' },
  { name: 'Alpthal', canton: 'SZ', postalCode: '8841' },
  { name: 'Einsiedeln', canton: 'SZ', postalCode: '8840' },
  { name: 'Euthal', canton: 'SZ', postalCode: '8840' },
  { name: 'Schindellegi', canton: 'SZ', postalCode: '8832' },
  { name: 'Feusisberg', canton: 'SZ', postalCode: '8835' },
  { name: 'Wollerau', canton: 'SZ', postalCode: '8832' },
  { name: 'Willerzell', canton: 'SZ', postalCode: '8841' },
  { name: 'Innerthal', canton: 'SZ', postalCode: '8856' },
  { name: 'Wägital', canton: 'SZ', postalCode: '8856' },
  { name: 'Vorderthal', canton: 'SZ', postalCode: '8856' },
  { name: 'Schübelbach', canton: 'SZ', postalCode: '8854' },
  
  // URI (UR)
  { name: 'Altdorf', canton: 'UR', postalCode: '6460' },
  { name: 'Andermatt', canton: 'UR', postalCode: '6490' },
  { name: 'Bürglen', canton: 'UR', postalCode: '6463' },
  { name: 'Erstfeld', canton: 'UR', postalCode: '6472' },
  { name: 'Flüelen', canton: 'UR', postalCode: '6454' },
  { name: 'Göschenen', canton: 'UR', postalCode: '6487' },
  { name: 'Gurtnellen', canton: 'UR', postalCode: '6474' },
  { name: 'Hospental', canton: 'UR', postalCode: '6490' },
  { name: 'Realp', canton: 'UR', postalCode: '6487' },
  { name: 'Schattdorf', canton: 'UR', postalCode: '6467' },
  { name: 'Seedorf', canton: 'UR', postalCode: '6462' },
  { name: 'Silenen', canton: 'UR', postalCode: '6472' },
  { name: 'Sisikon', canton: 'UR', postalCode: '6454' },
  { name: 'Spiringen', canton: 'UR', postalCode: '6464' },
  { name: 'Unterschächen', canton: 'UR', postalCode: '6464' },
  { name: 'Wassen', canton: 'UR', postalCode: '6486' },
  { name: 'Attinghausen', canton: 'UR', postalCode: '6468' },
  { name: 'Bauen', canton: 'UR', postalCode: '6454' },
  { name: 'Isenthal', canton: 'UR', postalCode: '6454' },
  
  // NIDWALDEN (NW)
  { name: 'Stans', canton: 'NW', postalCode: '6370' },
  { name: 'Hergiswil', canton: 'NW', postalCode: '6020' },
  { name: 'Buochs', canton: 'NW', postalCode: '6374' },
  { name: 'Ennetbürgen', canton: 'NW', postalCode: '6373' },
  { name: 'Stansstad', canton: 'NW', postalCode: '6372' },
  { name: 'Beckenried', canton: 'NW', postalCode: '6375' },
  { name: 'Oberdorf', canton: 'NW', postalCode: '6370' },
  { name: 'Dallenwil', canton: 'NW', postalCode: '6383' },
  { name: 'Ennetmoos', canton: 'NW', postalCode: '6370' },
  { name: 'Wolfenschiessen', canton: 'NW', postalCode: '6386' },
  { name: 'Emmetten', canton: 'NW', postalCode: '6376' },
  
  // OBWALDEN (OW)
  { name: 'Sarnen', canton: 'OW', postalCode: '6060' },
  { name: 'Alpnach', canton: 'OW', postalCode: '6052' },
  { name: 'Sachseln', canton: 'OW', postalCode: '6072' },
  { name: 'Kerns', canton: 'OW', postalCode: '6064' },
  { name: 'Giswil', canton: 'OW', postalCode: '6074' },
  { name: 'Lungern', canton: 'OW', postalCode: '6078' },
  { name: 'Engelberg', canton: 'OW', postalCode: '6390' },
  
  // GLARUS (GL)
  { name: 'Glarus', canton: 'GL', postalCode: '8750' },
  { name: 'Glarus Nord', canton: 'GL', postalCode: '8762' },
  { name: 'Glarus Süd', canton: 'GL', postalCode: '8762' },
  { name: 'Näfels', canton: 'GL', postalCode: '8752' },
  { name: 'Mollis', canton: 'GL', postalCode: '8752' },
  { name: 'Niederurnen', canton: 'GL', postalCode: '8752' },
  { name: 'Oberurnen', canton: 'GL', postalCode: '8752' },
  { name: 'Netstal', canton: 'GL', postalCode: '8752' },
  { name: 'Rüti', canton: 'GL', postalCode: '8762' },
  { name: 'Linthal', canton: 'GL', postalCode: '8784' },
  { name: 'Betschwanden', canton: 'GL', postalCode: '8777' },
  { name: 'Elm', canton: 'GL', postalCode: '8767' },
  { name: 'Engi', canton: 'GL', postalCode: '8763' },
  { name: 'Matt', canton: 'GL', postalCode: '8766' },
  { name: 'Schwanden', canton: 'GL', postalCode: '8762' },
  { name: 'Sool', canton: 'GL', postalCode: '8762' },
  
  // SCHAFFHAUSEN (SH)
  { name: 'Schaffhausen', canton: 'SH', postalCode: '8200' },
  { name: 'Neuhausen am Rheinfall', canton: 'SH', postalCode: '8212' },
  { name: 'Stein am Rhein', canton: 'SH', postalCode: '8260' },
  { name: 'Thayngen', canton: 'SH', postalCode: '8240' },
  { name: 'Schleitheim', canton: 'SH', postalCode: '8226' },
  { name: 'Beringen', canton: 'SH', postalCode: '8222' },
  { name: 'Herblingen', canton: 'SH', postalCode: '8222' },
  { name: 'Büttenhardt', canton: 'SH', postalCode: '8224' },
  { name: 'Löhningen', canton: 'SH', postalCode: '8224' },
  { name: 'Neunkirch', canton: 'SH', postalCode: '8213' },
  { name: 'Hallau', canton: 'SH', postalCode: '8215' },
  { name: 'Oberhallau', canton: 'SH', postalCode: '8216' },
  { name: 'Wilchingen', canton: 'SH', postalCode: '8217' },
  { name: 'Osterfingen', canton: 'SH', postalCode: '8217' },
  { name: 'Trasadingen', canton: 'SH', postalCode: '8217' },
  { name: 'Bargen', canton: 'SH', postalCode: '8234' },
  { name: 'Beggingen', canton: 'SH', postalCode: '8235' },
  { name: 'Merishausen', canton: 'SH', postalCode: '8232' },
  { name: 'Hemishofen', canton: 'SH', postalCode: '8260' },
  { name: 'Ramsen', canton: 'SH', postalCode: '8262' },
  { name: 'Dörflingen', canton: 'SH', postalCode: '8248' },
  
  // JURA (JU)
  { name: 'Delémont', canton: 'JU', postalCode: '2800' },
  { name: 'Porrentruy', canton: 'JU', postalCode: '2900' },
  { name: 'La Chaux-de-Fonds', canton: 'NE', postalCode: '2300' },
  { name: 'Le Locle', canton: 'NE', postalCode: '2400' },
  { name: 'Bure', canton: 'JU', postalCode: '2893' },
  { name: 'Boncourt', canton: 'JU', postalCode: '2907' },
  { name: 'Courgenay', canton: 'JU', postalCode: '2904' },
  { name: 'Fahy', canton: 'JU', postalCode: '2906' },
  { name: 'Grandfontaine', canton: 'JU', postalCode: '2905' },
  { name: 'Chevenez', canton: 'JU', postalCode: '2903' },
  { name: 'Roche-d\'Or', canton: 'JU', postalCode: '2905' },
  { name: 'Damvant', canton: 'JU', postalCode: '2905' },
  { name: 'Courtemaîche', canton: 'JU', postalCode: '2905' },
  { name: 'Montignez', canton: 'JU', postalCode: '2905' },
  { name: 'Buix', canton: 'JU', postalCode: '2905' },
  { name: 'Bassecourt', canton: 'JU', postalCode: '2854' },
  { name: 'Courtételle', canton: 'JU', postalCode: '2852' },
  { name: 'Courfaivre', canton: 'JU', postalCode: '2853' },
  { name: 'Develier', canton: 'JU', postalCode: '2802' },
  { name: 'Ballerstedt', canton: 'JU', postalCode: '2805' },
  { name: 'Soyhières', canton: 'JU', postalCode: '2806' },
  { name: 'Courrendlin', canton: 'JU', postalCode: '2830' },
  { name: 'Rebeuvelier', canton: 'JU', postalCode: '2830' },
  { name: 'Vellerat', canton: 'JU', postalCode: '2830' },
  { name: 'Moutier', canton: 'BE', postalCode: '2740' },
  { name: 'Courrendlin', canton: 'JU', postalCode: '2830' },
  { name: 'Soulce', canton: 'JU', postalCode: '2862' },
  { name: 'Undervelier', canton: 'JU', postalCode: '2863' },
  { name: 'Vermes', canton: 'JU', postalCode: '2864' },
  { name: 'Vicques', canton: 'JU', postalCode: '2824' },
  { name: 'Ederswiler', canton: 'JU', postalCode: '2827' },
  { name: 'Movelier', canton: 'JU', postalCode: '2825' },
  { name: 'Pleigne', canton: 'JU', postalCode: '2825' },
  { name: 'Roggenburg', canton: 'JU', postalCode: '2825' },
  
  // NEUCHÂTEL (NE)
  { name: 'Neuchâtel', canton: 'NE', postalCode: '2000' },
  { name: 'La Chaux-de-Fonds', canton: 'NE', postalCode: '2300' },
  { name: 'Le Locle', canton: 'NE', postalCode: '2400' },
  { name: 'Peseux', canton: 'NE', postalCode: '2035' },
  { name: 'Boudry', canton: 'NE', postalCode: '2017' },
  { name: 'Valangin', canton: 'NE', postalCode: '2037' },
  { name: 'Cortaillod', canton: 'NE', postalCode: '2016' },
  { name: 'Colombier', canton: 'NE', postalCode: '2013' },
  { name: 'Auvernier', canton: 'NE', postalCode: '2012' },
  { name: 'Hauterive', canton: 'NE', postalCode: '2068' },
  { name: 'St-Blaise', canton: 'NE', postalCode: '2072' },
  { name: 'Marin-Epagnier', canton: 'NE', postalCode: '2074' },
  { name: 'Le Landeron', canton: 'NE', postalCode: '2519' },
  { name: 'Cressier', canton: 'NE', postalCode: '2088' },
  { name: 'Gampelen', canton: 'BE', postalCode: '3236' },
  { name: 'Kerzers', canton: 'FR', postalCode: '3210' },
  { name: 'Môtiers', canton: 'NE', postalCode: '2112' },
  { name: 'Couvet', canton: 'NE', postalCode: '2103' },
  { name: 'Fleurier', canton: 'NE', postalCode: '2114' },
  { name: 'Saint-Sulpice', canton: 'NE', postalCode: '2115' },
  { name: 'Boveresse', canton: 'NE', postalCode: '2112' },
  { name: 'Buttes', canton: 'NE', postalCode: '2115' },
  { name: 'Les Bayards', canton: 'NE', postalCode: '2115' },
  { name: 'Brot-Dessous', canton: 'NE', postalCode: '2114' },
  { name: 'Brot-Plamboz', canton: 'NE', postalCode: '2114' },
  { name: 'La Sagne', canton: 'NE', postalCode: '2314' },
  { name: 'Les Ponts-de-Martel', canton: 'NE', postalCode: '2316' },
  { name: 'Le Bémont', canton: 'NE', postalCode: '2316' },
]

function createSlug(name: string, canton: string): string {
  return name
    .toLowerCase()
    .replace(/[àáâäæãåā]/g, 'a')
    .replace(/[èéêëēėę]/g, 'e')
    .replace(/[îïíīįì]/g, 'i')
    .replace(/[ôöòóœøōõ]/g, 'o')
    .replace(/[ûüùúū]/g, 'u')
    .replace(/[çćč]/g, 'c')
    .replace(/[ß]/g, 'ss')
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .trim() + '-' + canton.toLowerCase()
}

async function main() {
  console.log('🌍 Agregando municipios faltantes...')
  console.log('='.repeat(60))
  
  let added = 0
  let updated = 0
  let skipped = 0
  
  for (const municipality of municipalities) {
    const canton = await prisma.canton.findUnique({
      where: { code: municipality.canton }
    })
    
    if (!canton) {
      console.log(`⚠️ Cantón ${municipality.canton} no encontrado para ${municipality.name}`)
      skipped++
      continue
    }
    
    const slug = createSlug(municipality.name, municipality.canton)
    
    // Check if city already exists
    const existing = await prisma.city.findFirst({
      where: {
        name: municipality.name,
        cantonId: canton.id
      }
    })
    
    if (existing) {
      // Update postal code if needed (sin cambiar el slug para evitar conflictos)
      if (municipality.postalCode && existing.postalCode !== municipality.postalCode) {
        try {
          await prisma.city.update({
            where: { id: existing.id },
            data: { 
              postalCode: municipality.postalCode,
              updatedAt: new Date()
            }
          })
          updated++
        } catch (e) {
          // Ignorar errores de slug duplicado
        }
      }
      continue
    }
    
    // Create new city
    try {
      await prisma.city.create({
        data: {
          id: `city_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
          name: municipality.name,
          slug: slug,
          postalCode: municipality.postalCode,
          cantonId: canton.id,
          updatedAt: new Date()
        }
      })
      added++
      
      if (added % 100 === 0) {
        console.log(`✓ Procesados ${added} municipios nuevos...`)
      }
    } catch (error: any) {
      if (error.code !== 'P2002') {
        console.log(`⚠️ Error creando ${municipality.name}: ${error.message}`)
      }
    }
  }
  
  console.log('\n' + '='.repeat(60))
  console.log('✅ SEED COMPLETADO!')
  console.log('='.repeat(60))
  console.log(`📊 Municipios agregados: ${added}`)
  console.log(`📊 Municipios actualizados: ${updated}`)
  console.log(`📊 Omitidos: ${skipped}`)
  
  // Verify Grabs and Diesse
  const grabs = await prisma.city.findFirst({
    where: { name: 'Grabs' },
    include: { canton: true }
  })
  const diesse = await prisma.city.findFirst({
    where: { name: 'Diesse' },
    include: { canton: true }
  })
  
  console.log('\n🔍 Verificación:')
  console.log(`   Grabs: ${grabs ? `✅ ${grabs.name} ${grabs.canton.code} (${grabs.postalCode})` : '❌ No encontrado'}`)
  console.log(`   Diesse: ${diesse ? `✅ ${diesse.name} ${diesse.canton.code} (${diesse.postalCode})` : '❌ No encontrado'}`)
  
  // Final count
  const total = await prisma.city.count()
  console.log(`\n📈 Total de ciudades en base de datos: ${total}`)
}

main()
  .catch((e) => {
    console.error('❌ Error:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
