import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

// Municipios faltantes - lista completa adicional
const additionalMunicipalities: { name: string; canton: string; postalCode: string }[] = [
  // BERN (BE) - Más municipios
  { name: 'Aarberg', canton: 'BE', postalCode: '3270' },
  { name: 'Aarwangen', canton: 'BE', postalCode: '4912' },
  { name: 'Adelboden', canton: 'BE', postalCode: '3700' },
  { name: 'Aefligen', canton: 'BE', postalCode: '3474' },
  { name: 'Aegerten', canton: 'BE', postalCode: '2558' },
  { name: 'Aeschi bei Spiez', canton: 'BE', postalCode: '3704' },
  { name: 'Affoltern im Emmental', canton: 'BE', postalCode: '3416' },
  { name: 'Alchenstorf', canton: 'BE', postalCode: '3323' },
  { name: 'Allmendingen', canton: 'BE', postalCode: '3116' },
  { name: 'Arni', canton: 'BE', postalCode: '3506' },
  { name: 'Attiswil', canton: 'BE', postalCode: '4536' },
  { name: 'Auswil', canton: 'BE', postalCode: '4944' },
  { name: 'Bärau', canton: 'BE', postalCode: '3552' },
  { name: 'Bätterkinden', canton: 'BE', postalCode: '3315' },
  { name: 'Belpberg', canton: 'BE', postalCode: '3124' },
  { name: 'Biken', canton: 'BE', postalCode: '3417' },
  { name: 'Bollodingen', canton: 'BE', postalCode: '3362' },
  { name: 'Bönigen', canton: 'BE', postalCode: '3806' },
  { name: 'Brienz', canton: 'BE', postalCode: '3855' },
  { name: 'Brienzwiler', canton: 'BE', postalCode: '3856' },
  { name: 'Brügg', canton: 'BE', postalCode: '2555' },
  { name: 'Buchselen', canton: 'BE', postalCode: '3257' },
  { name: 'Büren an der Aare', canton: 'BE', postalCode: '3295' },
  { name: 'Büren zum Hof', canton: 'BE', postalCode: '3304' },
  { name: 'Busswil bei Büren', canton: 'BE', postalCode: '3293' },
  { name: 'Büttiken', canton: 'BE', postalCode: '3274' },
  { name: 'Corgémont', canton: 'BE', postalCode: '2607' },
  { name: 'Court', canton: 'BE', postalCode: '2853' },
  { name: 'Courtelary', canton: 'BE', postalCode: '2608' },
  { name: 'Crémines', canton: 'BE', postalCode: '2714' },
  { name: 'Dammersynn', canton: 'BE', postalCode: '3454' },
  { name: 'Diemerswil', canton: 'BE', postalCode: '3054' },
  { name: 'Eggiwil', canton: 'BE', postalCode: '3537' },
  { name: 'Erlach', canton: 'BE', postalCode: '3235' },
  { name: 'Eriz', canton: 'BE', postalCode: '3624' },
  { name: 'Eschi', canton: 'BE', postalCode: '3618' },
  { name: 'Ersigen', canton: 'BE', postalCode: '3423' },
  { name: 'Eriswil', canton: 'BE', postalCode: '4952' },
  { name: 'Evilard', canton: 'BE', postalCode: '4125' },
  { name: 'Ferenbalm', canton: 'BE', postalCode: '3203' },
  { name: 'Flamatt', canton: 'BE', postalCode: '3175' },
  { name: 'Flühli', canton: 'BE', postalCode: '6174' },
  { name: 'Frauenkappelen', canton: 'BE', postalCode: '3205' },
  { name: 'Frutigen', canton: 'BE', postalCode: '3714' },
  { name: 'Gampelen', canton: 'BE', postalCode: '3236' },
  { name: 'Gerzensee', canton: 'BE', postalCode: '3115' },
  { name: 'Gondiswil', canton: 'BE', postalCode: '4955' },
  { name: 'Grandval', canton: 'BE', postalCode: '2715' },
  { name: 'Guggisberg', canton: 'BE', postalCode: '3158' },
  { name: 'Gurzelen', canton: 'BE', postalCode: '3662' },
  { name: 'Habkern', canton: 'BE', postalCode: '3706' },
  { name: 'Hagneck', canton: 'BE', postalCode: '2557' },
  { name: 'Hasle bei Burgdorf', canton: 'BE', postalCode: '3415' },
  { name: 'Heimenhausen', canton: 'BE', postalCode: '3473' },
  { name: 'Hellsau', canton: 'BE', postalCode: '3423' },
  { name: 'Herbetswil', canton: 'BE', postalCode: '4417' },
  { name: 'Herbligen', canton: 'BE', postalCode: '3672' },
  { name: 'Hermiswil', canton: 'BE', postalCode: '3367' },
  { name: 'Hofen', canton: 'BE', postalCode: '4228' },
  { name: 'Hofstetten bei Brienz', canton: 'BE', postalCode: '3858' },
  { name: 'Hofstetten-Flüh', canton: 'BE', postalCode: '4108' },
  { name: 'Horrenbach-Buchen', canton: 'BE', postalCode: '3626' },
  { name: 'Hüttlingen', canton: 'BE', postalCode: '4914' },
  { name: 'Iffwil', canton: 'BE', postalCode: '3306' },
  { name: 'Inkwil', canton: 'BE', postalCode: '4535' },
  { name: 'Interlaken', canton: 'BE', postalCode: '3800' },
  { name: 'Iseltwald', canton: 'BE', postalCode: '3807' },
  { name: 'Ittigen', canton: 'BE', postalCode: '3063' },
  { name: 'Jaberg', canton: 'BE', postalCode: '3126' },
  { name: 'Jegenstorf', canton: 'BE', postalCode: '3303' },
  { name: 'Jens', canton: 'BE', postalCode: '2564' },
  { name: 'Kallnach', canton: 'BE', postalCode: '3283' },
  { name: 'Kappelen', canton: 'BE', postalCode: '3272' },
  { name: 'Kehrsatz', canton: 'BE', postalCode: '3122' },
  { name: 'Kernenried', canton: 'BE', postalCode: '3308' },
  { name: 'Kirchlindach', canton: 'BE', postalCode: '3035' },
  { name: 'Kiesen', canton: 'BE', postalCode: '3622' },
  { name: 'Köniz', canton: 'BE', postalCode: '3098' },
  { name: 'Koppigen', canton: 'BE', postalCode: '3425' },
  { name: 'Krattigen', canton: 'BE', postalCode: '3706' },
  { name: 'Kriechenwil', canton: 'BE', postalCode: '3034' },
  { name: 'La Heutte', canton: 'BE', postalCode: '2606' },
  { name: 'La Neuveville', canton: 'BE', postalCode: '2520' },
  { name: 'Lamboing', canton: 'BE', postalCode: '2512' },
  { name: 'Landiswil', canton: 'BE', postalCode: '3535' },
  { name: 'Langnau im Emmental', canton: 'BE', postalCode: '3550' },
  { name: 'Laupen', canton: 'BE', postalCode: '3177' },
  { name: 'Lauperswil', canton: 'BE', postalCode: '3438' },
  { name: 'Lengnau', canton: 'BE', postalCode: '3273' },
  { name: 'Linden', canton: 'BE', postalCode: '3538' },
  { name: 'Lobsigen', canton: 'BE', postalCode: '3270' },
  { name: 'Lotzwil', canton: 'BE', postalCode: '4932' },
  { name: 'Lüderbüch', canton: 'BE', postalCode: '4919' },
  { name: 'Lützelflüh', canton: 'BE', postalCode: '3435' },
  { name: 'Lyss', canton: 'BE', postalCode: '3250' },
  { name: 'Madiswil', canton: 'BE', postalCode: '4934' },
  { name: 'Matten bei Interlaken', canton: 'BE', postalCode: '3804' },
  { name: 'Mattstetten', canton: 'BE', postalCode: '3326' },
  { name: 'Meikirch', canton: 'BE', postalCode: '3038' },
  { name: 'Melchnau', canton: 'BE', postalCode: '4935' },
  { name: 'Merzligen', canton: 'BE', postalCode: '3285' },
  { name: 'Mirchel', canton: 'BE', postalCode: '3534' },
  { name: 'Moosseedorf', canton: 'BE', postalCode: '3312' },
  { name: 'Morens', canton: 'BE', postalCode: '3285' },
  { name: 'Mötschwil', canton: 'BE', postalCode: '3423' },
  { name: 'Moutier', canton: 'BE', postalCode: '2740' },
  { name: 'Mühleberg', canton: 'BE', postalCode: '3205' },
  { name: 'Mühlethurnen', canton: 'BE', postalCode: '3127' },
  { name: 'Münchenbuchsee', canton: 'BE', postalCode: '3053' },
  { name: 'Müntschemier', canton: 'BE', postalCode: '3226' },
  { name: 'Muri bei Bern', canton: 'BE', postalCode: '3075' },
  { name: 'Nidau', canton: 'BE', postalCode: '2560' },
  { name: 'Niederbipp', canton: 'BE', postalCode: '4702' },
  { name: 'Niedermuhlern', canton: 'BE', postalCode: '3094' },
  { name: 'Niederösch', canton: 'BE', postalCode: '3424' },
  { name: 'Noflen', canton: 'BE', postalCode: '3205' },
  { name: 'Oberbipp', canton: 'BE', postalCode: '4538' },
  { name: 'Oberdiessbach', canton: 'BE', postalCode: '3672' },
  { name: 'Oberhünigen', canton: 'BE', postalCode: '3672' },
  { name: 'Oberburg', canton: 'BE', postalCode: '3636' },
  { name: 'Oberlangenegg', canton: 'BE', postalCode: '3618' },
  { name: 'Oberried am Brienzersee', canton: 'BE', postalCode: '3858' },
  { name: 'Oberösch', canton: 'BE', postalCode: '3424' },
  { name: 'Oberwil bei Büren', canton: 'BE', postalCode: '3294' },
  { name: 'Oberwil im Simmental', canton: 'BE', postalCode: '3765' },
  { name: 'Ochlenberg', canton: 'BE', postalCode: '3374' },
  { name: 'Oppligen', canton: 'BE', postalCode: '3524' },
  { name: 'Orpund', canton: 'BE', postalCode: '2555' },
  { name: 'Pieterlen', canton: 'BE', postalCode: '2542' },
  { name: 'Plagne', canton: 'BE', postalCode: '2605' },
  { name: 'Prêles', canton: 'BE', postalCode: '2515' },
  { name: 'Péry', canton: 'BE', postalCode: '2606' },
  { name: 'Riggisberg', canton: 'BE', postalCode: '3132' },
  { name: 'Rindegg', canton: 'BE', postalCode: '3296' },
  { name: 'Rohrbach', canton: 'BE', postalCode: '4938' },
  { name: 'Rohrbachgraben', canton: 'BE', postalCode: '4938' },
  { name: 'Rosshäusern', canton: 'BE', postalCode: '3205' },
  { name: 'Rüderswil', canton: 'BE', postalCode: '3536' },
  { name: 'Rüegsau', canton: 'BE', postalCode: '3417' },
  { name: 'Rüeggisberg', canton: 'BE', postalCode: '3096' },
  { name: 'Rumendingen', canton: 'BE', postalCode: '3472' },
  { name: 'Ruppoldsried', canton: 'BE', postalCode: '3293' },
  { name: 'Rüti bei Büren', canton: 'BE', postalCode: '3298' },
  { name: 'Saint-Imier', canton: 'BE', postalCode: '2610' },
  { name: 'Sankt Stephan', canton: 'BE', postalCode: '3772' },
  { name: 'Scheunen', canton: 'BE', postalCode: '3315' },
  { name: 'Schangnau', canton: 'BE', postalCode: '6197' },
  { name: 'Schattenhalb', canton: 'BE', postalCode: '3764' },
  { name: 'Schlosswil', canton: 'BE', postalCode: '3086' },
  { name: 'Schüpfen', canton: 'BE', postalCode: '3054' },
  { name: 'Schwadernau', canton: 'BE', postalCode: '3275' },
  { name: 'Schwarzenburg', canton: 'BE', postalCode: '3150' },
  { name: 'Seedorf', canton: 'BE', postalCode: '3087' },
  { name: 'Signau', canton: 'BE', postalCode: '3534' },
  { name: 'Siselen', canton: 'BE', postalCode: '3225' },
  { name: 'Sonceboz-Sombeval', canton: 'BE', postalCode: '2605' },
  { name: 'Soriswil', canton: 'BE', postalCode: '3622' },
  { name: 'Spiez', canton: 'BE', postalCode: '3700' },
  { name: 'Stalden im Emmental', canton: 'BE', postalCode: '3561' },
  { name: 'Steffisburg', canton: 'BE', postalCode: '3612' },
  { name: 'Stettlen', canton: 'BE', postalCode: '3072' },
  { name: 'Studen', canton: 'BE', postalCode: '2557' },
  { name: 'Sumiswald', canton: 'BE', postalCode: '3454' },
  { name: 'Thörigen', canton: 'BE', postalCode: '3366' },
  { name: 'Thun', canton: 'BE', postalCode: '3600' },
  { name: 'Thunstetten', canton: 'BE', postalCode: '4922' },
  { name: 'Tüscherz-Alfermée', canton: 'BE', postalCode: '2525' },
  { name: 'Twann', canton: 'BE', postalCode: '2513' },
  { name: 'Uetendorf', canton: 'BE', postalCode: '3661' },
  { name: 'Ursenbach', canton: 'BE', postalCode: '3453' },
  { name: 'Vahlern', canton: 'BE', postalCode: '3618' },
  { name: 'Vilari', canton: 'BE', postalCode: '3423' },
  { name: 'Vinelz', canton: 'BE', postalCode: '2523' },
  { name: 'Wachseldorn', canton: 'BE', postalCode: '3618' },
  { name: 'Wangen an der Aare', canton: 'BE', postalCode: '3383' },
  { name: 'Wangenried', canton: 'BE', postalCode: '4577' },
  { name: 'Wengi', canton: 'BE', postalCode: '3295' },
  { name: 'Wichtrach', canton: 'BE', postalCode: '3114' },
  { name: 'Wiedlisbach', canton: 'BE', postalCode: '4537' },
  { name: 'Wileroltigen', canton: 'BE', postalCode: '3205' },
  { name: 'Willadingen', canton: 'BE', postalCode: '3315' },
  { name: 'Wiler bei Ursenbach', canton: 'BE', postalCode: '3452' },
  { name: 'Worb', canton: 'BE', postalCode: '3076' },
  { name: 'Wynau', canton: 'BE', postalCode: '4924' },
  { name: 'Wynigen', canton: 'BE', postalCode: '3473' },
  { name: 'Zollbrück', canton: 'BE', postalCode: '3422' },
  { name: 'Zweisimmen', canton: 'BE', postalCode: '3770' },
  { name: 'Twann-Tüscherz', canton: 'BE', postalCode: '2513' },
  { name: 'Nods', canton: 'BE', postalCode: '2516' },
  { name: 'Tavannes', canton: 'BE', postalCode: '2710' },
  { name: 'Tramelan', canton: 'BE', postalCode: '2720' },
  { name: 'Reconvilier', canton: 'BE', postalCode: '2732' },
  { name: 'Mont-Tramelan', canton: 'BE', postalCode: '2720' },
  { name: 'Sonceboz', canton: 'BE', postalCode: '2605' },
  { name: 'Sombeval', canton: 'BE', postalCode: '2605' },
  { name: 'Vauffelin', canton: 'BE', postalCode: '2605' },
  { name: 'Franges', canton: 'BE', postalCode: '2715' },
  { name: 'Grandval', canton: 'BE', postalCode: '2715' },
  { name: 'Monible', canton: 'BE', postalCode: '2715' },
  { name: 'Châtelat', canton: 'BE', postalCode: '2715' },
  { name: 'Souboz', canton: 'BE', postalCode: '2715' },
  { name: 'Sauge', canton: 'BE', postalCode: '3232' },
  { name: 'Rondchâtel', canton: 'BE', postalCode: '3232' },
  { name: 'La Heutte', canton: 'BE', postalCode: '2606' },
  { name: 'Péry-La Heutte', canton: 'BE', postalCode: '2606' },
  
  // VAUD (VD) - Más municipios
  { name: 'Aclens', canton: 'VD', postalCode: '1125' },
  { name: 'Aigle', canton: 'VD', postalCode: '1860' },
  { name: 'Ballaigues', canton: 'VD', postalCode: '1338' },
  { name: 'Bassins', canton: 'VD', postalCode: '1149' },
  { name: 'Baulmes', canton: 'VD', postalCode: '1443' },
  { name: 'Bavois', canton: 'VD', postalCode: '1372' },
  { name: 'Begnins', canton: 'VD', postalCode: '1268' },
  { name: 'Belmont-sur-Lausanne', canton: 'VD', postalCode: '1092' },
  { name: 'Berolle', canton: 'VD', postalCode: '1143' },
  { name: 'Bière', canton: 'VD', postalCode: '1145' },
  { name: 'Blonay', canton: 'VD', postalCode: '1807' },
  { name: 'Bogis-Bossey', canton: 'VD', postalCode: '1273' },
  { name: 'Bofflens', canton: 'VD', postalCode: '1318' },
  { name: 'Bonvillars', canton: 'VD', postalCode: '1426' },
  { name: 'Borex', canton: 'VD', postalCode: '1279' },
  { name: 'Boussens', canton: 'VD', postalCode: '1035' },
  { name: 'Bremblens', canton: 'VD', postalCode: '1040' },
  { name: 'Bretigny', canton: 'VD', postalCode: '1453' },
  { name: 'Buchillon', canton: 'VD', postalCode: '1169' },
  { name: 'Bursinel', canton: 'VD', postalCode: '1185' },
  { name: 'Bursins', canton: 'VD', postalCode: '1185' },
  { name: 'Chaméry', canton: 'VD', postalCode: '1067' },
  { name: 'Champigny', canton: 'VD', postalCode: '1037' },
  { name: 'Chardonne', canton: 'VD', postalCode: '1807' },
  { name: 'Chavannes-le-Chêne', canton: 'VD', postalCode: '1405' },
  { name: 'Chavornay', canton: 'VD', postalCode: '1373' },
  { name: 'Chessel', canton: 'VD', postalCode: '1845' },
  { name: 'Chevroux', canton: 'VD', postalCode: '1534' },
  { name: 'Chexbres', canton: 'VD', postalCode: '1071' },
  { name: 'Concise', canton: 'VD', postalCode: '1429' },
  { name: 'Corcelles-Chavornay', canton: 'VD', postalCode: '1373' },
  { name: 'Corcelles-le-Jorat', canton: 'VD', postalCode: '1054' },
  { name: 'Corcelles-près-Concise', canton: 'VD', postalCode: '1428' },
  { name: 'Cossonay', canton: 'VD', postalCode: '1304' },
  { name: 'Crassier', canton: 'VD', postalCode: '1262' },
  { name: 'Croy', canton: 'VD', postalCode: '1323' },
  { name: 'Cuarnens', canton: 'VD', postalCode: '1143' },
  { name: 'Denges', canton: 'VD', postalCode: '1027' },
  { name: 'Denens', canton: 'VD', postalCode: '1133' },
  { name: 'Dizy', canton: 'VD', postalCode: '1114' },
  { name: 'Dommartin', canton: 'VD', postalCode: '1053' },
  { name: 'Donneloye', canton: 'VD', postalCode: '1353' },
  { name: 'Duillier', canton: 'VD', postalCode: '1267' },
  { name: 'Dully', canton: 'VD', postalCode: '1185' },
  { name: 'Echallens', canton: 'VD', postalCode: '1040' },
  { name: 'Echandens', canton: 'VD', postalCode: '1026' },
  { name: 'Echichens', canton: 'VD', postalCode: '1123' },
  { name: 'Eclépens', canton: 'VD', postalCode: '1315' },
  { name: 'Ecoteaux', canton: 'VD', postalCode: '1413' },
  { name: 'Egrenolles', canton: 'VD', postalCode: '1278' },
  { name: 'Epenex', canton: 'VD', postalCode: '1032' },
  { name: 'Epalinges', canton: 'VD', postalCode: '1062' },
  { name: 'Etoy', canton: 'VD', postalCode: '1164' },
  { name: 'Faucex', canton: 'VD', postalCode: '1376' },
  { name: 'Fechy', canton: 'VD', postalCode: '1187' },
  { name: 'Ferlens', canton: 'VD', postalCode: '1083' },
  { name: 'Fontanezier', canton: 'VD', postalCode: '1429' },
  { name: 'Forel', canton: 'VD', postalCode: '1098' },
  { name: 'Founex', canton: 'VD', postalCode: '1297' },
  { name: 'Francillon', canton: 'VD', postalCode: '1053' },
  { name: 'Genolier', canton: 'VD', postalCode: '1272' },
  { name: 'Giez', canton: 'VD', postalCode: '1423' },
  { name: 'Gilly', canton: 'VD', postalCode: '1182' },
  { name: 'Gimel', canton: 'VD', postalCode: '1188' },
  { name: 'Gingins', canton: 'VD', postalCode: '1274' },
  { name: 'Gollion', canton: 'VD', postalCode: '1124' },
  { name: 'Grandcour', canton: 'VD', postalCode: '1523' },
  { name: 'Grandvaux', canton: 'VD', postalCode: '1091' },
  { name: 'Granges', canton: 'VD', postalCode: '1422' },
  { name: 'Gryon', canton: 'VD', postalCode: '1882' },
  { name: 'Hannchen', canton: 'VD', postalCode: '1462' },
  { name: 'Hauterive', canton: 'VD', postalCode: '1113' },
  { name: 'Herens', canton: 'VD', postalCode: '1095' },
  { name: 'Hermenches', canton: 'VD', postalCode: '1081' },
  { name: 'Hieres', canton: 'VD', postalCode: '1376' },
  { name: 'Jongny', canton: 'VD', postalCode: '1805' },
  { name: 'Jouxtens-Mézery', canton: 'VD', postalCode: '1008' },
  { name: 'L\'Abbaye', canton: 'VD', postalCode: '1344' },
  { name: 'La Chaux', canton: 'VD', postalCode: '1334' },
  { name: 'La Rippe', canton: 'VD', postalCode: '1273' },
  { name: 'La Sarraz', canton: 'VD', postalCode: '1315' },
  { name: 'Lavigny', canton: 'VD', postalCode: '1175' },
  { name: 'Le Chenit', canton: 'VD', postalCode: '1342' },
  { name: 'Le Lieu', canton: 'VD', postalCode: '1346' },
  { name: 'Le Mont-Pèlerin', canton: 'VD', postalCode: '1083' },
  { name: 'Le Vaud', canton: 'VD', postalCode: '1186' },
  { name: 'Les Clées', canton: 'VD', postalCode: '1357' },
  { name: 'Lignerolle', canton: 'VD', postalCode: '1317' },
  { name: 'Lussy', canton: 'VD', postalCode: '1132' },
  { name: 'Macherens', canton: 'VD', postalCode: '1523' },
  { name: 'Malapalud', canton: 'VD', postalCode: '1040' },
  { name: 'Marchissy', canton: 'VD', postalCode: '1189' },
  { name: 'Marnand', canton: 'VD', postalCode: '1433' },
  { name: 'Mathod', canton: 'VD', postalCode: '1433' },
  { name: 'Mex', canton: 'VD', postalCode: '1032' },
  { name: 'Mézery-près-Donneloye', canton: 'VD', postalCode: '1353' },
  { name: 'Mies', canton: 'VD', postalCode: '1291' },
  { name: 'Molondin', canton: 'VD', postalCode: '1433' },
  { name: 'Montricher', canton: 'VD', postalCode: '1141' },
  { name: 'Mont-la-Ville', canton: 'VD', postalCode: '1146' },
  { name: 'Montpreveyres', canton: 'VD', postalCode: '1081' },
  { name: 'Morrens', canton: 'VD', postalCode: '1037' },
  { name: 'Moudon', canton: 'VD', postalCode: '1510' },
  { name: 'Mouthier', canton: 'VD', postalCode: '1433' },
  { name: 'Naz', canton: 'VD', postalCode: '1040' },
  { name: 'Ogens', canton: 'VD', postalCode: '1082' },
  { name: 'Onnens', canton: 'VD', postalCode: '1425' },
  { name: 'Orbe', canton: 'VD', postalCode: '1350' },
  { name: 'Orny', canton: 'VD', postalCode: '1321' },
  { name: 'Oron', canton: 'VD', postalCode: '1608' },
  { name: 'Oron-la-Ville', canton: 'VD', postalCode: '1608' },
  { name: 'Oron-le-Châtel', canton: 'VD', postalCode: '1609' },
  { name: 'Oulens-sous-Echallens', canton: 'VD', postalCode: '1040' },
  { name: 'Pampigny', canton: 'VD', postalCode: '1142' },
  { name: 'Penthalaz', canton: 'VD', postalCode: '1305' },
  { name: 'Perroy', canton: 'VD', postalCode: '1189' },
  { name: 'Pizy', canton: 'VD', postalCode: '1149' },
  { name: 'Pompaples', canton: 'VD', postalCode: '1318' },
  { name: 'Prahins', canton: 'VD', postalCode: '1425' },
  { name: 'Premier', canton: 'VD', postalCode: '1321' },
  { name: 'Préverenges', canton: 'VD', postalCode: '1124' },
  { name: 'Pusy', canton: 'VD', postalCode: '1040' },
  { name: 'Rances', canton: 'VD', postalCode: '1353' },
  { name: 'Rivaz', canton: 'VD', postalCode: '1072' },
  { name: 'Roche', canton: 'VD', postalCode: '1845' },
  { name: 'Romainmôtier', canton: 'VD', postalCode: '1323' },
  { name: 'Ropraz', canton: 'VD', postalCode: '1086' },
  { name: 'Rossens', canton: 'VD', postalCode: '1053' },
  { name: 'Rue', canton: 'VD', postalCode: '1543' },
  { name: 'Rueyres', canton: 'VD', postalCode: '1353' },
  { name: 'Saint-George', canton: 'VD', postalCode: '1188' },
  { name: 'Saint-Livres', canton: 'VD', postalCode: '1182' },
  { name: 'Saint-Légier-La Chiésaz', canton: 'VD', postalCode: '1806' },
  { name: 'Saint-Prex', canton: 'VD', postalCode: '1162' },
  { name: 'Saint-Saphorin', canton: 'VD', postalCode: '1073' },
  { name: 'Saint-Sulpice', canton: 'VD', postalCode: '1025' },
  { name: 'Salentse', canton: 'VD', postalCode: '1133' },
  { name: 'Saphoz', canton: 'VD', postalCode: '1189' },
  { name: 'Saugy', canton: 'VD', postalCode: '1073' },
  { name: 'Savigny', canton: 'VD', postalCode: '1073' },
  { name: 'Senarclens', canton: 'VD', postalCode: '1318' },
  { name: 'Servion', canton: 'VD', postalCode: '1086' },
  { name: 'Signy', canton: 'VD', postalCode: '1278' },
  { name: 'Sullens', canton: 'VD', postalCode: '1037' },
  { name: 'Tannay', canton: 'VD', postalCode: '1291' },
  { name: 'Thierrens', canton: 'VD', postalCode: '1514' },
  { name: 'Treycovignens', canton: 'VD', postalCode: '1040' },
  { name: 'Trélex', canton: 'VD', postalCode: '1267' },
  { name: 'Vallorbe', canton: 'VD', postalCode: '1337' },
  { name: 'Valzeille', canton: 'VD', postalCode: '1094' },
  { name: 'Vaux-sur-Morges', canton: 'VD', postalCode: '1114' },
  { name: 'Veigy', canton: 'VD', postalCode: '1245' },
  { name: 'Veytaux', canton: 'VD', postalCode: '1820' },
  { name: 'Vich', canton: 'VD', postalCode: '1867' },
  { name: 'Villars-sous-Yens', canton: 'VD', postalCode: '1169' },
  { name: 'Villeneuve', canton: 'VD', postalCode: '1844' },
  { name: 'Vinzel', canton: 'VD', postalCode: '1189' },
  { name: 'Vuiteboeuf', canton: 'VD', postalCode: '1442' },
  { name: 'Vulbens', canton: 'VD', postalCode: '1133' },
  { name: 'Yens', canton: 'VD', postalCode: '1169' },
  { name: 'Yvonand', canton: 'VD', postalCode: '1462' },
  { name: 'Arnex-sur-Orbe', canton: 'VD', postalCode: '1321' },
  { name: 'Agiez', canton: 'VD', postalCode: '1373' },
  { name: 'Baulmes', canton: 'VD', postalCode: '1443' },
  { name: 'Büsserach', canton: 'SO', postalCode: '4223' },
  { name: 'Bresse', canton: 'VD', postalCode: '1038' },
  { name: 'Bullet', canton: 'VD', postalCode: '1451' },
  { name: 'Champvent', canton: 'VD', postalCode: '1442' },
  { name: 'Clarmont', canton: 'VD', postalCode: '1112' },
  { name: 'Denges', canton: 'VD', postalCode: '1027' },
  { name: 'Eclépens', canton: 'VD', postalCode: '1315' },
  { name: 'Essert-sous-Champvent', canton: 'VD', postalCode: '1442' },
  { name: 'Fiez', canton: 'VD', postalCode: '1429' },
  { name: 'Goumoëns', canton: 'VD', postalCode: '1430' },
  { name: 'Goumoens-la-Ville', canton: 'VD', postalCode: '1430' },
  { name: 'Goumoens-le-Jux', canton: 'VD', postalCode: '1430' },
  { name: 'L\'Isle', canton: 'VD', postalCode: '1145' },
  { name: 'La Chaux', canton: 'VD', postalCode: '1334' },
  { name: 'Lignerolles', canton: 'VD', postalCode: '1317' },
  { name: 'Mauborget', canton: 'VD', postalCode: '1451' },
  { name: 'Montcherand', canton: 'VD', postalCode: '1372' },
  { name: 'Novalles', canton: 'VD', postalCode: '1430' },
  { name: 'Ormont-Dessus', canton: 'VD', postalCode: '1863' },
  { name: 'Ormont-Dessous', canton: 'VD', postalCode: '1862' },
  { name: 'Pailly', canton: 'VD', postalCode: '1038' },
  { name: 'Peney-le-Jorat', canton: 'VD', postalCode: '1082' },
  { name: 'Penthalaz', canton: 'VD', postalCode: '1305' },
  { name: 'Poliez-Pittet', canton: 'VD', postalCode: '1413' },
  { name: 'Provence', canton: 'VD', postalCode: '1451' },
  { name: 'Rances', canton: 'VD', postalCode: '1353' },
  { name: 'Rossenges', canton: 'VD', postalCode: '1082' },
  { name: 'Sainte-Croix', canton: 'VD', postalCode: '1450' },
  { name: 'Sévery', canton: 'VD', postalCode: '1149' },
  { name: 'Suchy', canton: 'VD', postalCode: '1373' },
  { name: 'Suscévaz', canton: 'VD', postalCode: '1430' },
  { name: 'Vallorbe', canton: 'VD', postalCode: '1337' },
  { name: 'Vaulion', canton: 'VD', postalCode: '1328' },
  { name: 'Vugelles-La Mothe', canton: 'VD', postalCode: '1428' },
  { name: 'Vuiteboeuf', canton: 'VD', postalCode: '1442' },
  { name: 'Yverdon-les-Bains', canton: 'VD', postalCode: '1400' },
  { name: 'Yvonand', canton: 'VD', postalCode: '1462' },
  
  // ZURICH (ZH) - Más municipios
  { name: 'Adlikon', canton: 'ZH', postalCode: '8426' },
  { name: 'Aesch', canton: 'ZH', postalCode: '8904' },
  { name: 'Berg am Irchel', canton: 'ZH', postalCode: '8444' },
  { name: 'Birmensdorf', canton: 'ZH', postalCode: '8908' },
  { name: 'Boppelsen', canton: 'ZH', postalCode: '8445' },
  { name: 'Buch am Irchel', canton: 'ZH', postalCode: '8444' },
  { name: 'Dägerlen', canton: 'ZH', postalCode: '8414' },
  { name: 'Dättlikon', canton: 'ZH', postalCode: '8421' },
  { name: 'Dinhard', canton: 'ZH', postalCode: '8422' },
  { name: 'Eglisau', canton: 'ZH', postalCode: '8193' },
  { name: 'Elsau', canton: 'ZH', postalCode: '8352' },
  { name: 'Elgg', canton: 'ZH', postalCode: '8353' },
  { name: 'Embrach', canton: 'ZH', postalCode: '8424' },
  { name: 'Erlenbach', canton: 'ZH', postalCode: '8703' },
  { name: 'Fehren', canton: 'ZH', postalCode: '8468' },
  { name: 'Fischenthal', canton: 'ZH', postalCode: '8497' },
  { name: 'Flaach', canton: 'ZH', postalCode: '8416' },
  { name: 'Freienstein-Teufen', canton: 'ZH', postalCode: '8427' },
  { name: 'Hagenbuch', canton: 'ZH', postalCode: '8525' },
  { name: 'Hausen am Albis', canton: 'ZH', postalCode: '8915' },
  { name: 'Hedingen', canton: 'ZH', postalCode: '8908' },
  { name: 'Henggart', canton: 'ZH', postalCode: '8444' },
  { name: 'Hittnau', canton: 'ZH', postalCode: '8335' },
  { name: 'Hochfelden', canton: 'ZH', postalCode: '8452' },
  { name: 'Hombrechtikon', canton: 'ZH', postalCode: '8676' },
  { name: 'Hummelberg', canton: 'ZH', postalCode: '8355' },
  { name: 'Hüntwangen', canton: 'ZH', postalCode: '8194' },
  { name: 'Knonau', canton: 'ZH', postalCode: '8934' },
  { name: 'Laufen-Uhwiesen', canton: 'ZH', postalCode: '8448' },
  { name: 'Lufingen', canton: 'ZH', postalCode: '8416' },
  { name: 'Männedorf', canton: 'ZH', postalCode: '8708' },
  { name: 'Maur', canton: 'ZH', postalCode: '8714' },
  { name: 'Mettmenstetten', canton: 'ZH', postalCode: '8932' },
  { name: 'Mönchaltorf', canton: 'ZH', postalCode: '8616' },
  { name: 'Neftenbach', canton: 'ZH', postalCode: '8413' },
  { name: 'Niederhasli', canton: 'ZH', postalCode: '8156' },
  { name: 'Niederneunforn', canton: 'ZH', postalCode: '8472' },
  { name: 'Nürensdorf', canton: 'ZH', postalCode: '8309' },
  { name: 'Oberhasli', canton: 'ZH', postalCode: '8156' },
  { name: 'Oberrieden', canton: 'ZH', postalCode: '8926' },
  { name: 'Obfelden', canton: 'ZH', postalCode: '8912' },
  { name: 'Oetwil am See', canton: 'ZH', postalCode: '8607' },
  { name: 'Oetwil an der Limmat', canton: 'ZH', postalCode: '8955' },
  { name: 'Otelfingen', canton: 'ZH', postalCode: '8112' },
  { name: 'Pfäffikon', canton: 'ZH', postalCode: '8330' },
  { name: 'Pfungen', canton: 'ZH', postalCode: '8422' },
  { name: 'Rafz', canton: 'ZH', postalCode: '8197' },
  { name: 'Regensberg', canton: 'ZH', postalCode: '8158' },
  { name: 'Rieden', canton: 'ZH', postalCode: '8619' },
  { name: 'Rifferswil', canton: 'ZH', postalCode: '8908' },
  { name: 'Rorbas', canton: 'ZH', postalCode: '8424' },
  { name: 'Rümlang', canton: 'ZH', postalCode: '8153' },
  { name: 'Russikon', canton: 'ZH', postalCode: '8333' },
  { name: 'Schleinikon', canton: 'ZH', postalCode: '8166' },
  { name: 'Schönenberg', canton: 'ZH', postalCode: '8809' },
  { name: 'Seuzach', canton: 'ZH', postalCode: '8472' },
  { name: 'Singen', canton: 'ZH', postalCode: '8457' },
  { name: 'Stallikon', canton: 'ZH', postalCode: '8908' },
  { name: 'Thalheim', canton: 'ZH', postalCode: '8472' },
  { name: 'Truttikon', canton: 'ZH', postalCode: '8416' },
  { name: 'Uetikon', canton: 'ZH', postalCode: '8707' },
  { name: 'Urdorf', canton: 'ZH', postalCode: '8902' },
  { name: 'Wallisellen', canton: 'ZH', postalCode: '8304' },
  { name: 'Wasterkingen', canton: 'ZH', postalCode: '8446' },
  { name: 'Weiningen', canton: 'ZH', postalCode: '8904' },
  { name: 'Weisslingen', canton: 'ZH', postalCode: '8484' },
  { name: 'Wiesendangen', canton: 'ZH', postalCode: '8526' },
  { name: 'Wila', canton: 'ZH', postalCode: '8492' },
  { name: 'Wildberg', canton: 'ZH', postalCode: '8494' },
  { name: 'Winterthur', canton: 'ZH', postalCode: '8400' },
  { name: 'Wittikon', canton: 'ZH', postalCode: '8342' },
  { name: 'Zell', canton: 'ZH', postalCode: '8617' },
  { name: 'Zürich', canton: 'ZH', postalCode: '8000' },
  { name: 'Zweidlen', canton: 'ZH', postalCode: '8444' },
  
  // SOLOTHURN (SO) - Más municipios
  { name: 'Aedermannsdorf', canton: 'SO', postalCode: '4714' },
  { name: 'Aespi', canton: 'SO', postalCode: '4703' },
  { name: 'Aetingen', canton: 'SO', postalCode: '4577' },
  { name: 'Balm bei Günsberg', canton: 'SO', postalCode: '4718' },
  { name: 'Bellach', canton: 'SO', postalCode: '4512' },
  { name: 'Bettlach', canton: 'SO', postalCode: '5044' },
  { name: 'Biberist', canton: 'SO', postalCode: '4562' },
  { name: 'Boningen', canton: 'SO', postalCode: '4627' },
  { name: 'Buchegg', canton: 'SO', postalCode: '4587' },
  { name: 'Burgäschi', canton: 'SO', postalCode: '4587' },
  { name: 'Derendingen', canton: 'SO', postalCode: '4552' },
  { name: 'Deitingen', canton: 'SO', postalCode: '4573' },
  { name: 'Dornach', canton: 'SO', postalCode: '4143' },
  { name: 'Egerkingen', canton: 'SO', postalCode: '4618' },
  { name: 'Eppenberg-Wöschnau', canton: 'SO', postalCode: '5012' },
  { name: 'Erlinsbach', canton: 'SO', postalCode: '5018' },
  { name: 'Feldbrunnen', canton: 'SO', postalCode: '4503' },
  { name: 'Flumenthal', canton: 'SO', postalCode: '4703' },
  { name: 'Gänsbrunnen', canton: 'SO', postalCode: '4718' },
  { name: 'Gempen', canton: 'SO', postalCode: '4145' },
  { name: 'Grenchen', canton: 'SO', postalCode: '2540' },
  { name: 'Günsberg', canton: 'SO', postalCode: '4718' },
  { name: 'Hauenstein', canton: 'SO', postalCode: '4617' },
  { name: 'Hersiwil', canton: 'SO', postalCode: '4577' },
  { name: 'Hochwald', canton: 'SO', postalCode: '4146' },
  { name: 'Hofstetten', canton: 'SO', postalCode: '4462' },
  { name: 'Kammersrohr', canton: 'SO', postalCode: '4718' },
  { name: 'Kappel', canton: 'SO', postalCode: '4577' },
  { name: 'Kienberg', canton: 'SO', postalCode: '5082' },
  { name: 'Kleinlützel', canton: 'SO', postalCode: '4239' },
  { name: 'Kriegstetten', canton: 'SO', postalCode: '4577' },
  { name: 'Langendorf', canton: 'SO', postalCode: '4513' },
  { name: 'Laupersdorf', canton: 'SO', postalCode: '4710' },
  { name: 'Lommiswil', canton: 'SO', postalCode: '4514' },
  { name: 'Lostorf', canton: 'SO', postalCode: '4666' },
  { name: 'Luterbach', canton: 'SO', postalCode: '4572' },
  { name: 'Matzendorf', canton: 'SO', postalCode: '4716' },
  { name: 'Messen', canton: 'SO', postalCode: '4587' },
  { name: 'Mühledorf', canton: 'SO', postalCode: '4587' },
  { name: 'Mümliswil', canton: 'SO', postalCode: '4717' },
  { name: 'Nennigkofen', canton: 'SO', postalCode: '4587' },
  { name: 'Niederbuchsiten', canton: 'SO', postalCode: '4626' },
  { name: 'Niedergösgen', canton: 'SO', postalCode: '5016' },
  { name: 'Oberbuchsiten', canton: 'SO', postalCode: '4625' },
  { name: 'Oberdorf', canton: 'SO', postalCode: '4718' },
  { name: 'Obergösgen', canton: 'SO', postalCode: '5016' },
  { name: 'Olten', canton: 'SO', postalCode: '4600' },
  { name: 'Riedholz', canton: 'SO', postalCode: '4515' },
  { name: 'Rickenbach', canton: 'SO', postalCode: '4703' },
  { name: 'Rohr', canton: 'SO', postalCode: '4143' },
  { name: 'Schönenwerd', canton: 'SO', postalCode: '5012' },
  { name: 'Selzach', canton: 'SO', postalCode: '2545' },
  { name: 'Solothurn', canton: 'SO', postalCode: '4500' },
  { name: 'Stüsslingen', canton: 'SO', postalCode: '4666' },
  { name: 'Trimbach', canton: 'SO', postalCode: '5026' },
  { name: 'Walterswil', canton: 'SO', postalCode: '4715' },
  { name: 'Wangen', canton: 'SO', postalCode: '4703' },
  { name: 'Welschenrohr', canton: 'SO', postalCode: '4716' },
  { name: 'Winznau', canton: 'SO', postalCode: '4702' },
  { name: 'Wisen', canton: 'SO', postalCode: '4494' },
  { name: 'Zuchwil', canton: 'SO', postalCode: '4531' },
  { name: 'Balsthal', canton: 'SO', postalCode: '4710' },
  { name: 'Welschenrohr-Gänsbrunnen', canton: 'SO', postalCode: '4716' },
  
  // AARGAU (AG) - Más municipios
  { name: 'Aarau', canton: 'AG', postalCode: '5000' },
  { name: 'Aarburg', canton: 'AG', postalCode: '4663' },
  { name: 'Abtwil', canton: 'AG', postalCode: '5621' },
  { name: 'Ammerswil', canton: 'AG', postalCode: '5600' },
  { name: 'Arni', canton: 'AG', postalCode: '8907' },
  { name: 'Attelwil', canton: 'AG', postalCode: '5055' },
  { name: 'Auw', canton: 'AG', postalCode: '5644' },
  { name: 'Baden', canton: 'AG', postalCode: '5400' },
  { name: 'Baldingen', canton: 'AG', postalCode: '5304' },
  { name: 'Bellikon', canton: 'AG', postalCode: '5408' },
  { name: 'Benzenschwil', canton: 'AG', postalCode: '5618' },
  { name: 'Bergdietikon', canton: 'AG', postalCode: '8962' },
  { name: 'Berikon', canton: 'AG', postalCode: '8965' },
  { name: 'Besenbüren', canton: 'AG', postalCode: '5625' },
  { name: 'Bettwil', canton: 'AG', postalCode: '5619' },
  { name: 'Biberstein', canton: 'AG', postalCode: '5032' },
  { name: 'Birmenstorf', canton: 'AG', postalCode: '5413' },
  { name: 'Birr', canton: 'AG', postalCode: '5242' },
  { name: 'Birrhard', canton: 'AG', postalCode: '5244' },
  { name: 'Böbikon', canton: 'AG', postalCode: '5305' },
  { name: 'Bözen', canton: 'AG', postalCode: '5084' },
  { name: 'Bottenwil', canton: 'AG', postalCode: '4813' },
  { name: 'Bremgarten', canton: 'AG', postalCode: '5620' },
  { name: 'Brunegg', canton: 'AG', postalCode: '5504' },
  { name: 'Buchs', canton: 'AG', postalCode: '5033' },
  { name: 'Büttikon', canton: 'AG', postalCode: '5616' },
  { name: 'Burg', canton: 'AG', postalCode: '5608' },
  { name: 'Buttwil', canton: 'AG', postalCode: '5622' },
  { name: 'Densbüren', canton: 'AG', postalCode: '5245' },
  { name: 'Dietwil', canton: 'AG', postalCode: '6044' },
  { name: 'Dintikon', canton: 'AG', postalCode: '5606' },
  { name: 'Dottikon', canton: 'AG', postalCode: '5605' },
  { name: 'Dürrenäsch', canton: 'AG', postalCode: '5712' },
  { name: 'Egliswil', canton: 'AG', postalCode: '5703' },
  { name: 'Ehrendingen', canton: 'AG', postalCode: '5305' },
  { name: 'Eiken', canton: 'AG', postalCode: '5074' },
  { name: 'Elfingen', canton: 'AG', postalCode: '5083' },
  { name: 'Endingen', canton: 'AG', postalCode: '5305' },
  { name: 'Ennetbaden', canton: 'AG', postalCode: '5407' },
  { name: 'Erlinsbach', canton: 'AG', postalCode: '5018' },
  { name: 'Fahrwangen', canton: 'AG', postalCode: '5604' },
  { name: 'Fischbach-Göslikon', canton: 'AG', postalCode: '5525' },
  { name: 'Fislisbach', canton: 'AG', postalCode: '5442' },
  { name: 'Freienwil', canton: 'AG', postalCode: '5303' },
  { name: 'Gansingen', canton: 'AG', postalCode: '5272' },
  { name: 'Gebenstorf', canton: 'AG', postalCode: '5412' },
  { name: 'Geltwil', canton: 'AG', postalCode: '5628' },
  { name: 'Gipf-Oberfrick', canton: 'AG', postalCode: '5073' },
  { name: 'Gontenschwil', canton: 'AG', postalCode: '5725' },
  { name: 'Gränichen', canton: 'AG', postalCode: '5722' },
  { name: 'Habsburg', canton: 'AG', postalCode: '5245' },
  { name: 'Hallwil', canton: 'AG', postalCode: '5705' },
  { name: 'Hausen', canton: 'AG', postalCode: '5212' },
  { name: 'Hendschiken', canton: 'AG', postalCode: '5604' },
  { name: 'Hermetschwil-Staffeln', canton: 'AG', postalCode: '5626' },
  { name: 'Hirschthal', canton: 'AG', postalCode: '5042' },
  { name: 'Holderbank', canton: 'AG', postalCode: '5026' },
  { name: 'Hottwil', canton: 'AG', postalCode: '5054' },
  { name: 'Hunzenschwil', canton: 'AG', postalCode: '5502' },
  { name: 'Ittenthal', canton: 'AG', postalCode: '5082' },
  { name: 'Kaiseraugst', canton: 'AG', postalCode: '4303' },
  { name: 'Kaiserstuhl', canton: 'AG', postalCode: '8463' },
  { name: 'Kallern', canton: 'AG', postalCode: '5624' },
  { name: 'Killwangen', canton: 'AG', postalCode: '8956' },
  { name: 'Klingnau', canton: 'AG', postalCode: '5313' },
  { name: 'Koblenz', canton: 'AG', postalCode: '5316' },
  { name: 'Küttigen', canton: 'AG', postalCode: '5024' },
  { name: 'Künten', canton: 'AG', postalCode: '5445' },
  { name: 'Laufenburg', canton: 'AG', postalCode: '5080' },
  { name: 'Leibstadt', canton: 'AG', postalCode: '5325' },
  { name: 'Leimbach', canton: 'AG', postalCode: '5627' },
  { name: 'Leuggern', canton: 'AG', postalCode: '5305' },
  { name: 'Leutwil', canton: 'AG', postalCode: '5725' },
  { name: 'Lupfig', canton: 'AG', postalCode: '5112' },
  { name: 'Lunkhofen', canton: 'AG', postalCode: '5408' },
  { name: 'Magden', canton: 'AG', postalCode: '4153' },
  { name: 'Mandach', canton: 'AG', postalCode: '5314' },
  { name: 'Mägenwil', canton: 'AG', postalCode: '5503' },
  { name: 'Mellingen', canton: 'AG', postalCode: '5507' },
  { name: 'Menziken', canton: 'AG', postalCode: '5737' },
  { name: 'Merenschwand', canton: 'AG', postalCode: '5634' },
  { name: 'Möhlin', canton: 'AG', postalCode: '4313' },
  { name: 'Mönthal', canton: 'AG', postalCode: '5063' },
  { name: 'Möriken-Wildegg', canton: 'AG', postalCode: '5102' },
  { name: 'Murgenthal', canton: 'AG', postalCode: '4853' },
  { name: 'Muri', canton: 'AG', postalCode: '5630' },
  { name: 'Niederlenz', canton: 'AG', postalCode: '5702' },
  { name: 'Oberentfelden', canton: 'AG', postalCode: '5036' },
  { name: 'Oberkulm', canton: 'AG', postalCode: '5727' },
  { name: 'Oberlunkhofen', canton: 'AG', postalCode: '8917' },
  { name: 'Obermumpf', canton: 'AG', postalCode: '4325' },
  { name: 'Oberehrendingen', canton: 'AG', postalCode: '5305' },
  { name: 'Obersiggenthal', canton: 'AG', postalCode: '5305' },
  { name: 'Oberwil-Lieli', canton: 'AG', postalCode: '8966' },
  { name: 'Olsberg', canton: 'AG', postalCode: '5042' },
  { name: 'Othmarsingen', canton: 'AG', postalCode: '5504' },
  { name: 'Ottlingen', canton: 'AG', postalCode: '5452' },
  { name: 'Remigen', canton: 'AG', postalCode: '5223' },
  { name: 'Rheinfelden', canton: 'AG', postalCode: '4310' },
  { name: 'Rietheim', canton: 'AG', postalCode: '5332' },
  { name: 'Riniken', canton: 'AG', postalCode: '5222' },
  { name: 'Rohr', canton: 'AG', postalCode: '4118' },
  { name: 'Rothrist', canton: 'AG', postalCode: '4852' },
  { name: 'Rottenschwil', canton: 'AG', postalCode: '5607' },
  { name: 'Rudolfstetten-Friedlisberg', canton: 'AG', postalCode: '8964' },
  { name: 'Rüfenach', canton: 'AG', postalCode: '5225' },
  { name: 'Sarmenstorf', canton: 'AG', postalCode: '5612' },
  { name: 'Schafisheim', canton: 'AG', postalCode: '5503' },
  { name: 'Schinznach-Bad', canton: 'AG', postalCode: '5116' },
  { name: 'Schinznach-Dorf', canton: 'AG', postalCode: '5116' },
  { name: 'Schlossrued', canton: 'AG', postalCode: '5056' },
  { name: 'Schmiedrued', canton: 'AG', postalCode: '5057' },
  { name: 'Schoftland', canton: 'AG', postalCode: '5040' },
  { name: 'Schupfart', canton: 'AG', postalCode: '5083' },
  { name: 'Schwaderloch', canton: 'AG', postalCode: '5274' },
  { name: 'Seengen', canton: 'AG', postalCode: '5707' },
  { name: 'Seon', canton: 'AG', postalCode: '5702' },
  { name: 'Sins', canton: 'AG', postalCode: '5643' },
  { name: 'Sisseln', canton: 'AG', postalCode: '4334' },
  { name: 'Spreitenbach', canton: 'AG', postalCode: '8957' },
  { name: 'Staffelbach', canton: 'AG', postalCode: '5053' },
  { name: 'Staufen', canton: 'AG', postalCode: '5607' },
  { name: 'Stein', canton: 'AG', postalCode: '4313' },
  { name: 'Stetten', canton: 'AG', postalCode: '5605' },
  { name: 'Stilli', canton: 'AG', postalCode: '5234' },
  { name: 'Strengelbach', canton: 'AG', postalCode: '4803' },
  { name: 'Suhr', canton: 'AG', postalCode: '5034' },
  { name: 'Sulz', canton: 'AG', postalCode: '5083' },
  { name: 'Tägerig', canton: 'AG', postalCode: '5408' },
  { name: 'Teufenthal', canton: 'AG', postalCode: '5723' },
  { name: 'Thalheim', canton: 'AG', postalCode: '5082' },
  { name: 'Turgi', canton: 'AG', postalCode: '5305' },
  { name: 'Uerkheim', canton: 'AG', postalCode: '4813' },
  { name: 'Unterentfelden', canton: 'AG', postalCode: '5035' },
  { name: 'Unterkulm', canton: 'AG', postalCode: '5726' },
  { name: 'Unterlunkhofen', canton: 'AG', postalCode: '8918' },
  { name: 'Villigen', canton: 'AG', postalCode: '5236' },
  { name: 'Villmergen', canton: 'AG', postalCode: '5612' },
  { name: 'Vordemwald', canton: 'AG', postalCode: '4813' },
  { name: 'Wegenstetten', canton: 'AG', postalCode: '4118' },
  { name: 'Wettingen', canton: 'AG', postalCode: '5430' },
  { name: 'Widen', canton: 'AG', postalCode: '8967' },
  { name: 'Wiliberg', canton: 'AG', postalCode: '5056' },
  { name: 'Windisch', canton: 'AG', postalCode: '5210' },
  { name: 'Wohlen', canton: 'AG', postalCode: '5610' },
  { name: 'Wölflinswil', canton: 'AG', postalCode: '5083' },
  { name: 'Würenlingen', canton: 'AG', postalCode: '5303' },
  { name: 'Würenlos', canton: 'AG', postalCode: '5408' },
  { name: 'Zetzwil', canton: 'AG', postalCode: '5729' },
  { name: 'Zeiningen', canton: 'AG', postalCode: '4314' },
  { name: 'Zofingen', canton: 'AG', postalCode: '4800' },
  { name: 'Zuzgen', canton: 'AG', postalCode: '4315' },
  { name: 'Böbikon', canton: 'AG', postalCode: '5305' },
  { name: 'Bremwil', canton: 'AG', postalCode: '5704' },
  { name: 'Busslingen', canton: 'AG', postalCode: '5444' },
  { name: 'Mittelhäusern', canton: 'AG', postalCode: '5212' },
  
  // BASEL-LANDSCHAFT (BL) - Más municipios
  { name: 'Aesch', canton: 'BL', postalCode: '4147' },
  { name: 'Allschwil', canton: 'BL', postalCode: '4123' },
  { name: 'Anwil', canton: 'BL', postalCode: '4463' },
  { name: 'Arlesheim', canton: 'BL', postalCode: '4144' },
  { name: 'Bennwil', canton: 'BL', postalCode: '4448' },
  { name: 'Binningen', canton: 'BL', postalCode: '4102' },
  { name: 'Birsfelden', canton: 'BL', postalCode: '4127' },
  { name: 'Böckten', canton: 'BL', postalCode: '4461' },
  { name: 'Bottmingen', canton: 'BL', postalCode: '4103' },
  { name: 'Bretzwil', canton: 'BL', postalCode: '4206' },
  { name: 'Bubendorf', canton: 'BL', postalCode: '4416' },
  { name: 'Buckten', canton: 'BL', postalCode: '4449' },
  { name: 'Buus', canton: 'BL', postalCode: '4454' },
  { name: 'Diepflingen', canton: 'BL', postalCode: '4441' },
  { name: 'Diegten', canton: 'BL', postalCode: '4453' },
  { name: 'Duggingen', canton: 'BL', postalCode: '4203' },
  { name: 'Eptingen', canton: 'BL', postalCode: '4458' },
  { name: 'Ettingen', canton: 'BL', postalCode: '4107' },
  { name: 'Frenkendorf', canton: 'BL', postalCode: '4402' },
  { name: 'Füllinsdorf', canton: 'BL', postalCode: '4414' },
  { name: 'Giebenach', canton: 'BL', postalCode: '4305' },
  { name: 'Grellingen', canton: 'BL', postalCode: '4203' },
  { name: 'Hemmiken', canton: 'BL', postalCode: '4462' },
  { name: 'Hölstein', canton: 'BL', postalCode: '4447' },
  { name: 'Itingen', canton: 'BL', postalCode: '4452' },
  { name: 'Känerkinden', canton: 'BL', postalCode: '4461' },
  { name: 'Kilchberg', canton: 'BL', postalCode: '4447' },
  { name: 'Lampenberg', canton: 'BL', postalCode: '4448' },
  { name: 'Langenbruck', canton: 'BL', postalCode: '4438' },
  { name: 'Laufen', canton: 'BL', postalCode: '4225' },
  { name: 'Lausen', canton: 'BL', postalCode: '4415' },
  { name: 'Läufelfingen', canton: 'BL', postalCode: '4448' },
  { name: 'Liedertswil', canton: 'BL', postalCode: '4438' },
  { name: 'Liesberg', canton: 'BL', postalCode: '4226' },
  { name: 'Liestal', canton: 'BL', postalCode: '4410' },
  { name: 'Maisprach', canton: 'BL', postalCode: '4124' },
  { name: 'Münchenstein', canton: 'BL', postalCode: '4142' },
  { name: 'Muttenz', canton: 'BL', postalCode: '4132' },
  { name: 'Nusshof', canton: 'BL', postalCode: '4445' },
  { name: 'Oberdorf', canton: 'BL', postalCode: '4436' },
  { name: 'Oberwil', canton: 'BL', postalCode: '4104' },
  { name: 'Oltingen', canton: 'BL', postalCode: '4454' },
  { name: 'Ormalingen', canton: 'BL', postalCode: '4464' },
  { name: 'Pfeffingen', canton: 'BL', postalCode: '4109' },
  { name: 'Pratteln', canton: 'BL', postalCode: '4133' },
  { name: 'Ramlinsburg', canton: 'BL', postalCode: '4445' },
  { name: 'Reigoldswil', canton: 'BL', postalCode: '4438' },
  { name: 'Reinach', canton: 'BL', postalCode: '4153' },
  { name: 'Rickenbach', canton: 'BL', postalCode: '4457' },
  { name: 'Röschenz', canton: 'BL', postalCode: '4233' },
  { name: 'Rothenfluh', canton: 'BL', postalCode: '4466' },
  { name: 'Rümlingen', canton: 'BL', postalCode: '4458' },
  { name: 'Rünenberg', canton: 'BL', postalCode: '4467' },
  { name: 'Seltisberg', canton: 'BL', postalCode: '4411' },
  { name: 'Sissach', canton: 'BL', postalCode: '4450' },
  { name: 'Tecknau', canton: 'BL', postalCode: '4455' },
  { name: 'Tierstein', canton: 'BL', postalCode: '4226' },
  { name: 'Wahlen', canton: 'BL', postalCode: '4233' },
  { name: 'Waldenburg', canton: 'BL', postalCode: '4437' },
  { name: 'Wenslingen', canton: 'BL', postalCode: '4467' },
  { name: 'Witterswil', canton: 'BL', postalCode: '4108' },
  { name: 'Ziefen', canton: 'BL', postalCode: '4414' },
  { name: 'Zunzgen', canton: 'BL', postalCode: '4447' },
  { name: 'Zeglingen', canton: 'BL', postalCode: '4455' },
  { name: 'Hofstetten-Flüh', canton: 'BL', postalCode: '4108' },
  { name: 'Nenzlingen', canton: 'BL', postalCode: '4224' },
  { name: 'Burg im Leimental', canton: 'BL', postalCode: '4108' },
  { name: 'Blaenstein', canton: 'BL', postalCode: '4242' },
  { name: 'Brugglingen', canton: 'BL', postalCode: '4144' },
]

function createSlug(name: string, canton: string): string {
  return name
    .toLowerCase()
    .replace(/[àáâäæãåā]/g, 'a')
    .replace(/[èéêëēėę]/g, 'e')
    .replace(/[îïíīįì]/g, 'i')
    .replace(/[ôöòóœøōõ]/g, 'o')
    .replace(/[ûüùúū]/g, 'u')
    .replace(/[çćč]/g, 'c')
    .replace(/[ß]/g, 'ss')
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .trim() + '-' + canton.toLowerCase()
}

async function main() {
  console.log('🌍 Agregando municipios adicionales...')
  console.log('='.repeat(60))
  
  let added = 0
  let updated = 0
  let skipped = 0
  
  for (const municipality of additionalMunicipalities) {
    const canton = await prisma.canton.findUnique({
      where: { code: municipality.canton }
    })
    
    if (!canton) {
      skipped++
      continue
    }
    
    const slug = createSlug(municipality.name, municipality.canton)
    
    // Check if city already exists
    const existing = await prisma.city.findFirst({
      where: {
        name: municipality.name,
        cantonId: canton.id
      }
    })
    
    if (existing) {
      // Update postal code if needed
      if (municipality.postalCode && existing.postalCode !== municipality.postalCode) {
        try {
          await prisma.city.update({
            where: { id: existing.id },
            data: { 
              postalCode: municipality.postalCode,
              updatedAt: new Date()
            }
          })
          updated++
        } catch (e) {
          // Ignore errors
        }
      }
      continue
    }
    
    // Create new city
    try {
      await prisma.city.create({
        data: {
          id: `city_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
          name: municipality.name,
          slug: slug,
          postalCode: municipality.postalCode,
          cantonId: canton.id,
          updatedAt: new Date()
        }
      })
      added++
      
      if (added % 100 === 0) {
        console.log(`✓ Procesados ${added} municipios nuevos...`)
      }
    } catch (error: any) {
      if (error.code !== 'P2002') {
        // Ignore duplicate errors
      }
    }
  }
  
  console.log('\n' + '='.repeat(60))
  console.log('✅ SEED COMPLETADO!')
  console.log('='.repeat(60))
  console.log(`📊 Municipios agregados: ${added}`)
  console.log(`📊 Municipios actualizados: ${updated}`)
  console.log(`📊 Omitidos: ${skipped}`)
  
  // Final count
  const total = await prisma.city.count()
  console.log(`\n📈 Total de ciudades en base de datos: ${total}`)
}

main()
  .catch((e) => {
    console.error('❌ Error:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
