import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

// Últimos municipios faltantes con códigos postales OFICIALES
const finalMunicipalities: { name: string; canton: string; postalCode: string }[] = [
  // BERN (BE) - municipios restantes
  { name: 'Aarberg', canton: 'BE', postalCode: '3270' },
  { name: 'Aarwangen', canton: 'BE', postalCode: '4912' },
  { name: 'Adelboden', canton: 'BE', postalCode: '3700' },
  { name: 'Aefligen', canton: 'BE', postalCode: '3474' },
  { name: 'Aegerten', canton: 'BE', postalCode: '2558' },
  { name: 'Aeschi bei Spiez', canton: 'BE', postalCode: '3704' },
  { name: 'Affoltern im Emmental', canton: 'BE', postalCode: '3416' },
  { name: 'Alchenstorf', canton: 'BE', postalCode: '3323' },
  { name: 'Allmendingen', canton: 'BE', postalCode: '3116' },
  { name: 'Arni', canton: 'BE', postalCode: '3506' },
  { name: 'Attiswil', canton: 'BE', postalCode: '4536' },
  { name: 'Auswil', canton: 'BE', postalCode: '4944' },
  { name: 'Bärau', canton: 'BE', postalCode: '3552' },
  { name: 'Belpberg', canton: 'BE', postalCode: '3124' },
  { name: 'Bibern', canton: 'BE', postalCode: '2517' },
  { name: 'Bollodingen', canton: 'BE', postalCode: '3362' },
  { name: 'Brienzwiler', canton: 'BE', postalCode: '3856' },
  { name: 'Büren zum Hof', canton: 'BE', postalCode: '3304' },
  { name: 'Busswil bei Büren', canton: 'BE', postalCode: '3293' },
  { name: 'Büttiken', canton: 'BE', postalCode: '3274' },
  { name: 'Corgémont', canton: 'BE', postalCode: '2607' },
  { name: 'Court', canton: 'BE', postalCode: '2853' },
  { name: 'Courtelary', canton: 'BE', postalCode: '2608' },
  { name: 'Crémines', canton: 'BE', postalCode: '2714' },
  { name: 'Diemerswil', canton: 'BE', postalCode: '3053' },
  { name: 'Eggiwil', canton: 'BE', postalCode: '3537' },
  { name: 'Erlach', canton: 'BE', postalCode: '3235' },
  { name: 'Eriz', canton: 'BE', postalCode: '3624' },
  { name: 'Eschi', canton: 'BE', postalCode: '3618' },
  { name: 'Ersigen', canton: 'BE', postalCode: '3423' },
  { name: 'Eriswil', canton: 'BE', postalCode: '4952' },
  { name: 'Evilard', canton: 'BE', postalCode: '4125' },
  { name: 'Ferenbalm', canton: 'BE', postalCode: '3203' },
  { name: 'Frauenkappelen', canton: 'BE', postalCode: '3205' },
  { name: 'Gerzensee', canton: 'BE', postalCode: '3115' },
  { name: 'Gondiswil', canton: 'BE', postalCode: '4955' },
  { name: 'Grandval', canton: 'BE', postalCode: '2715' },
  { name: 'Guggisberg', canton: 'BE', postalCode: '3158' },
  { name: 'Gurzelen', canton: 'BE', postalCode: '3662' },
  { name: 'Hagneck', canton: 'BE', postalCode: '2557' },
  { name: 'Hasle bei Burgdorf', canton: 'BE', postalCode: '3415' },
  { name: 'Heimenhausen', canton: 'BE', postalCode: '3473' },
  { name: 'Hellsau', canton: 'BE', postalCode: '3423' },
  { name: 'Herbetswil', canton: 'BE', postalCode: '4417' },
  { name: 'Herbligen', canton: 'BE', postalCode: '3672' },
  { name: 'Hermiswil', canton: 'BE', postalCode: '3367' },
  { name: 'Hofen', canton: 'BE', postalCode: '4228' },
  { name: 'Hofstetten bei Brienz', canton: 'BE', postalCode: '3858' },
  { name: 'Horrenbach-Buchen', canton: 'BE', postalCode: '3626' },
  { name: 'Iffwil', canton: 'BE', postalCode: '3306' },
  { name: 'Inkwil', canton: 'BE', postalCode: '4535' },
  { name: 'Iseltwald', canton: 'BE', postalCode: '3807' },
  { name: 'Jaberg', canton: 'BE', postalCode: '3126' },
  { name: 'Jens', canton: 'BE', postalCode: '2564' },
  { name: 'Kallnach', canton: 'BE', postalCode: '3283' },
  { name: 'Kandergrund', canton: 'BE', postalCode: '3717' },
  { name: 'Kandersteg', canton: 'BE', postalCode: '3718' },
  { name: 'Kappelen', canton: 'BE', postalCode: '3272' },
  { name: 'Kernenried', canton: 'BE', postalCode: '3308' },
  { name: 'Kiesen', canton: 'BE', postalCode: '3622' },
  { name: 'Kirchlindach', canton: 'BE', postalCode: '3035' },
  { name: 'Krattigen', canton: 'BE', postalCode: '3707' },
  { name: 'Kriechenwil', canton: 'BE', postalCode: '3034' },
  { name: 'La Heutte', canton: 'BE', postalCode: '2606' },
  { name: 'La Neuveville', canton: 'BE', postalCode: '2520' },
  { name: 'Lamboing', canton: 'BE', postalCode: '2512' },
  { name: 'Landiswil', canton: 'BE', postalCode: '3535' },
  { name: 'Lengnau', canton: 'BE', postalCode: '3273' },
  { name: 'Lenk', canton: 'BE', postalCode: '3775' },
  { name: 'Linden', canton: 'BE', postalCode: '3538' },
  { name: 'Lobsigen', canton: 'BE', postalCode: '3270' },
  { name: 'Lützelflüh', canton: 'BE', postalCode: '3435' },
  { name: 'Madiswil', canton: 'BE', postalCode: '4934' },
  { name: 'Mattstetten', canton: 'BE', postalCode: '3326' },
  { name: 'Meikirch', canton: 'BE', postalCode: '3038' },
  { name: 'Melchnau', canton: 'BE', postalCode: '4935' },
  { name: 'Merzligen', canton: 'BE', postalCode: '3285' },
  { name: 'Mirchel', canton: 'BE', postalCode: '3534' },
  { name: 'Moosseedorf', canton: 'BE', postalCode: '3312' },
  { name: 'Morens', canton: 'BE', postalCode: '3285' },
  { name: 'Mötschwil', canton: 'BE', postalCode: '3423' },
  { name: 'Mühleberg', canton: 'BE', postalCode: '3204' },
  { name: 'Mühlethurnen', canton: 'BE', postalCode: '3127' },
  { name: 'Müntschemier', canton: 'BE', postalCode: '3226' },
  { name: 'Niederbipp', canton: 'BE', postalCode: '4702' },
  { name: 'Niedermuhlern', canton: 'BE', postalCode: '3094' },
  { name: 'Niederösch', canton: 'BE', postalCode: '3424' },
  { name: 'Noflen', canton: 'BE', postalCode: '3205' },
  { name: 'Oberbipp', canton: 'BE', postalCode: '4538' },
  { name: 'Oberhünigen', canton: 'BE', postalCode: '3672' },
  { name: 'Oberburg', canton: 'BE', postalCode: '3636' },
  { name: 'Oberlangenegg', canton: 'BE', postalCode: '3618' },
  { name: 'Oberösch', canton: 'BE', postalCode: '3424' },
  { name: 'Oberwil bei Büren', canton: 'BE', postalCode: '3294' },
  { name: 'Oberwil im Simmental', canton: 'BE', postalCode: '3765' },
  { name: 'Ochlenberg', canton: 'BE', postalCode: '3374' },
  { name: 'Oppligen', canton: 'BE', postalCode: '3524' },
  { name: 'Orpund', canton: 'BE', postalCode: '2555' },
  { name: 'Pieterlen', canton: 'BE', postalCode: '2542' },
  { name: 'Plagne', canton: 'BE', postalCode: '2605' },
  { name: 'Prêles', canton: 'BE', postalCode: '2515' },
  { name: 'Péry', canton: 'BE', postalCode: '2606' },
  { name: 'Riggisberg', canton: 'BE', postalCode: '3132' },
  { name: 'Rohrbach', canton: 'BE', postalCode: '4938' },
  { name: 'Rohrbachgraben', canton: 'BE', postalCode: '4938' },
  { name: 'Rosshäusern', canton: 'BE', postalCode: '3205' },
  { name: 'Rüderswil', canton: 'BE', postalCode: '3536' },
  { name: 'Rüegsau', canton: 'BE', postalCode: '3417' },
  { name: 'Rüeggisberg', canton: 'BE', postalCode: '3096' },
  { name: 'Rumendingen', canton: 'BE', postalCode: '3472' },
  { name: 'Ruppoldsried', canton: 'BE', postalCode: '3293' },
  { name: 'Rüti bei Büren', canton: 'BE', postalCode: '3298' },
  { name: 'Saanen', canton: 'BE', postalCode: '3792' },
  { name: 'Saanenmöser', canton: 'BE', postalCode: '3778' },
  { name: 'Saint-Imier', canton: 'BE', postalCode: '2610' },
  { name: 'Schangnau', canton: 'BE', postalCode: '6197' },
  { name: 'Sankt Stephan', canton: 'BE', postalCode: '3772' },
  { name: 'Scheunen', canton: 'BE', postalCode: '3315' },
  { name: 'Schlosswil', canton: 'BE', postalCode: '3086' },
  { name: 'Schüpfen', canton: 'BE', postalCode: '3054' },
  { name: 'Schwadernau', canton: 'BE', postalCode: '3275' },
  { name: 'Seedorf', canton: 'BE', postalCode: '3087' },
  { name: 'Signau', canton: 'BE', postalCode: '3534' },
  { name: 'Siselen', canton: 'BE', postalCode: '3225' },
  { name: 'Sonceboz-Sombeval', canton: 'BE', postalCode: '2605' },
  { name: 'Soriswil', canton: 'BE', postalCode: '3622' },
  { name: 'Stalden im Emmental', canton: 'BE', postalCode: '3561' },
  { name: 'Stettlen', canton: 'BE', postalCode: '3072' },
  { name: 'Studen', canton: 'BE', postalCode: '2557' },
  { name: 'Sumiswald', canton: 'BE', postalCode: '3454' },
  { name: 'Tavannes', canton: 'BE', postalCode: '2710' },
  { name: 'Thörigen', canton: 'BE', postalCode: '3366' },
  { name: 'Thunstetten', canton: 'BE', postalCode: '4922' },
  { name: 'Tramelan', canton: 'BE', postalCode: '2720' },
  { name: 'Tüscherz-Alfermée', canton: 'BE', postalCode: '2525' },
  { name: 'Twann', canton: 'BE', postalCode: '2513' },
  { name: 'Ursenbach', canton: 'BE', postalCode: '3453' },
  { name: 'Vahlern', canton: 'BE', postalCode: '3618' },
  { name: 'Vinelz', canton: 'BE', postalCode: '2523' },
  { name: 'Wachseldorn', canton: 'BE', postalCode: '3618' },
  { name: 'Wangen an der Aare', canton: 'BE', postalCode: '3383' },
  { name: 'Wangenried', canton: 'BE', postalCode: '4577' },
  { name: 'Wengen', canton: 'BE', postalCode: '3823' },
  { name: 'Wengi', canton: 'BE', postalCode: '3295' },
  { name: 'Wichtrach', canton: 'BE', postalCode: '3114' },
  { name: 'Wiedlisbach', canton: 'BE', postalCode: '4537' },
  { name: 'Wileroltigen', canton: 'BE', postalCode: '3205' },
  { name: 'Willadingen', canton: 'BE', postalCode: '3315' },
  { name: 'Wiler bei Ursenbach', canton: 'BE', postalCode: '3452' },
  { name: 'Wynau', canton: 'BE', postalCode: '4924' },
  { name: 'Wynigen', canton: 'BE', postalCode: '3473' },
  { name: 'Zollbrück', canton: 'BE', postalCode: '3422' },
  { name: 'Zweisimmen', canton: 'BE', postalCode: '3770' },
  { name: 'Twann-Tüscherz', canton: 'BE', postalCode: '2513' },
  { name: 'Mont-Tramelan', canton: 'BE', postalCode: '2720' },
  { name: 'Reconvilier', canton: 'BE', postalCode: '2732' },
  { name: 'Büre', canton: 'BE', postalCode: '3297' },
  { name: 'Gaicht', canton: 'BE', postalCode: '3704' },
  { name: 'Schwanden', canton: 'BE', postalCode: '3766' },
  { name: 'Gsteigwiler', canton: 'BE', postalCode: '3806' },
  { name: 'Gündlischwand', canton: 'BE', postalCode: '3806' },
  { name: 'Lütschental', canton: 'BE', postalCode: '3823' },
  { name: 'Saxeten', canton: 'BE', postalCode: '3806' },
  { name: 'Därligen', canton: 'BE', postalCode: '3705' },
  { name: 'Leissigen', canton: 'BE', postalCode: '3705' },
  { name: 'Aeschi', canton: 'BE', postalCode: '3704' },
  { name: 'Bremgarten bei Bern', canton: 'BE', postalCode: '3047' },
  { name: 'Kirchenthurnen', canton: 'BE', postalCode: '3128' },
  { name: 'Rüti bei Riggisberg', canton: 'BE', postalCode: '3133' },
  { name: 'Kaufdorf', canton: 'BE', postalCode: '3126' },
  { name: 'Lohnstorf', canton: 'BE', postalCode: '3127' },
  { name: 'Rümligen', canton: 'BE', postalCode: '3127' },
  { name: 'Albligen', canton: 'BE', postalCode: '3151' },
  { name: 'Riggisberg', canton: 'BE', postalCode: '3132' },
  { name: 'Bolligen', canton: 'BE', postalCode: '3065' },
  { name: 'Vechigen', canton: 'BE', postalCode: '3076' },
  { name: 'Seftigen', canton: 'BE', postalCode: '3087' },
  { name: 'Bätterkinden', canton: 'BE', postalCode: '3315' },
  { name: 'Oberdiessbach', canton: 'BE', postalCode: '3672' },
  { name: 'Belp', canton: 'BE', postalCode: '3123' },
  { name: 'Münsingen', canton: 'BE', postalCode: '3110' },
  { name: 'Ittigen', canton: 'BE', postalCode: '3063' },
  { name: 'Ostermundigen', canton: 'BE', postalCode: '3072' },
  { name: 'Worb', canton: 'BE', postalCode: '3076' },
  
  // VAUD (VD) - municipios restantes
  { name: 'Aclens', canton: 'VD', postalCode: '1125' },
  { name: 'Allaman', canton: 'VD', postalCode: '1163' },
  { name: 'Apples', canton: 'VD', postalCode: '1143' },
  { name: 'Assens', canton: 'VD', postalCode: '1041' },
  { name: 'Aubonne', canton: 'VD', postalCode: '1170' },
  { name: 'Avenches', canton: 'VD', postalCode: '1580' },
  { name: 'Ballens', canton: 'VD', postalCode: '1143' },
  { name: 'Ballaigues', canton: 'VD', postalCode: '1338' },
  { name: 'Bassins', canton: 'VD', postalCode: '1149' },
  { name: 'Baulmes', canton: 'VD', postalCode: '1443' },
  { name: 'Bavois', canton: 'VD', postalCode: '1372' },
  { name: 'Begnins', canton: 'VD', postalCode: '1268' },
  { name: 'Belmont-sur-Lausanne', canton: 'VD', postalCode: '1092' },
  { name: 'Berolle', canton: 'VD', postalCode: '1143' },
  { name: 'Bière', canton: 'VD', postalCode: '1145' },
  { name: 'Blonay', canton: 'VD', postalCode: '1807' },
  { name: 'Bogis-Bossey', canton: 'VD', postalCode: '1273' },
  { name: 'Bofflens', canton: 'VD', postalCode: '1318' },
  { name: 'Bonvillars', canton: 'VD', postalCode: '1426' },
  { name: 'Borex', canton: 'VD', postalCode: '1279' },
  { name: 'Boussens', canton: 'VD', postalCode: '1035' },
  { name: 'Bremblens', canton: 'VD', postalCode: '1040' },
  { name: 'Bretigny', canton: 'VD', postalCode: '1453' },
  { name: 'Buchillon', canton: 'VD', postalCode: '1169' },
  { name: 'Bursinel', canton: 'VD', postalCode: '1185' },
  { name: 'Bursins', canton: 'VD', postalCode: '1185' },
  { name: 'Bussy', canton: 'VD', postalCode: '1036' },
  { name: 'Chaméry', canton: 'VD', postalCode: '1067' },
  { name: 'Champigny', canton: 'VD', postalCode: '1037' },
  { name: 'Chardonne', canton: 'VD', postalCode: '1807' },
  { name: 'Chavannes-le-Chêne', canton: 'VD', postalCode: '1405' },
  { name: 'Chavannes-près-Renens', canton: 'VD', postalCode: '1022' },
  { name: 'Chavannes-sur-Morges', canton: 'VD', postalCode: '1108' },
  { name: 'Chavornay', canton: 'VD', postalCode: '1373' },
  { name: 'Chessel', canton: 'VD', postalCode: '1845' },
  { name: 'Chevroux', canton: 'VD', postalCode: '1534' },
  { name: 'Chexbres', canton: 'VD', postalCode: '1071' },
  { name: 'Clarmont', canton: 'VD', postalCode: '1112' },
  { name: 'Concise', canton: 'VD', postalCode: '1429' },
  { name: 'Corcelles-Chavornay', canton: 'VD', postalCode: '1373' },
  { name: 'Corcelles-le-Jorat', canton: 'VD', postalCode: '1054' },
  { name: 'Corcelles-près-Concise', canton: 'VD', postalCode: '1428' },
  { name: 'Cossonay', canton: 'VD', postalCode: '1304' },
  { name: 'Cottens', canton: 'VD', postalCode: '1113' },
  { name: 'Crassier', canton: 'VD', postalCode: '1262' },
  { name: 'Crissier', canton: 'VD', postalCode: '1023' },
  { name: 'Croy', canton: 'VD', postalCode: '1323' },
  { name: 'Cuarnens', canton: 'VD', postalCode: '1143' },
  { name: 'Cugy', canton: 'VD', postalCode: '1052' },
  { name: 'Denges', canton: 'VD', postalCode: '1027' },
  { name: 'Denens', canton: 'VD', postalCode: '1133' },
  { name: 'Dizy', canton: 'VD', postalCode: '1114' },
  { name: 'Dommartin', canton: 'VD', postalCode: '1053' },
  { name: 'Donneloye', canton: 'VD', postalCode: '1353' },
  { name: 'Duillier', canton: 'VD', postalCode: '1267' },
  { name: 'Dully', canton: 'VD', postalCode: '1185' },
  { name: 'Echallens', canton: 'VD', postalCode: '1040' },
  { name: 'Echandens', canton: 'VD', postalCode: '1026' },
  { name: 'Echichens', canton: 'VD', postalCode: '1123' },
  { name: 'Ecublens', canton: 'VD', postalCode: '1024' },
  { name: 'Eclépens', canton: 'VD', postalCode: '1315' },
  { name: 'Ecoteaux', canton: 'VD', postalCode: '1413' },
  { name: 'Egrenolles', canton: 'VD', postalCode: '1278' },
  { name: 'Epenex', canton: 'VD', postalCode: '1032' },
  { name: 'Epalinges', canton: 'VD', postalCode: '1062' },
  { name: 'Etoy', canton: 'VD', postalCode: '1164' },
  { name: 'Fechy', canton: 'VD', postalCode: '1187' },
  { name: 'Ferlens', canton: 'VD', postalCode: '1083' },
  { name: 'Font', canton: 'VD', postalCode: '1606' },
  { name: 'Fontanezier', canton: 'VD', postalCode: '1429' },
  { name: 'Forel', canton: 'VD', postalCode: '1098' },
  { name: 'Founex', canton: 'VD', postalCode: '1297' },
  { name: 'Francillon', canton: 'VD', postalCode: '1053' },
  { name: 'Genolier', canton: 'VD', postalCode: '1272' },
  { name: 'Giez', canton: 'VD', postalCode: '1423' },
  { name: 'Gilly', canton: 'VD', postalCode: '1182' },
  { name: 'Gimel', canton: 'VD', postalCode: '1188' },
  { name: 'Gingins', canton: 'VD', postalCode: '1274' },
  { name: 'Gollion', canton: 'VD', postalCode: '1124' },
  { name: 'Grandcour', canton: 'VD', postalCode: '1523' },
  { name: 'Grandvaux', canton: 'VD', postalCode: '1091' },
  { name: 'Granges', canton: 'VD', postalCode: '1422' },
  { name: 'Gryon', canton: 'VD', postalCode: '1882' },
  { name: 'Henniez', canton: 'VD', postalCode: '1533' },
  { name: 'Hermenches', canton: 'VD', postalCode: '1081' },
  { name: 'Jongny', canton: 'VD', postalCode: '1805' },
  { name: 'Jouxtens-Mézery', canton: 'VD', postalCode: '1008' },
  { name: 'L\'Abbaye', canton: 'VD', postalCode: '1344' },
  { name: 'L\'Isle', canton: 'VD', postalCode: '1145' },
  { name: 'La Chaux', canton: 'VD', postalCode: '1334' },
  { name: 'La Rippe', canton: 'VD', postalCode: '1273' },
  { name: 'La Sarraz', canton: 'VD', postalCode: '1315' },
  { name: 'La Tour-de-Peilz', canton: 'VD', postalCode: '1814' },
  { name: 'Lavigny', canton: 'VD', postalCode: '1175' },
  { name: 'Le Chenit', canton: 'VD', postalCode: '1342' },
  { name: 'Le Lieu', canton: 'VD', postalCode: '1346' },
  { name: 'Le Mont-Pèlerin', canton: 'VD', postalCode: '1083' },
  { name: 'Le Vaud', canton: 'VD', postalCode: '1186' },
  { name: 'Les Clées', canton: 'VD', postalCode: '1357' },
  { name: 'Lignerolle', canton: 'VD', postalCode: '1317' },
  { name: 'Lussy', canton: 'VD', postalCode: '1132' },
  { name: 'Lutry', canton: 'VD', postalCode: '1095' },
  { name: 'Maracon', canton: 'VD', postalCode: '1512' },
  { name: 'Marchissy', canton: 'VD', postalCode: '1189' },
  { name: 'Marnand', canton: 'VD', postalCode: '1433' },
  { name: 'Mathod', canton: 'VD', postalCode: '1433' },
  { name: 'Mex', canton: 'VD', postalCode: '1032' },
  { name: 'Mézières', canton: 'VD', postalCode: '1081' },
  { name: 'Mies', canton: 'VD', postalCode: '1291' },
  { name: 'Mollens', canton: 'VD', postalCode: '1132' },
  { name: 'Molondin', canton: 'VD', postalCode: '1433' },
  { name: 'Montricher', canton: 'VD', postalCode: '1141' },
  { name: 'Mont-la-Ville', canton: 'VD', postalCode: '1146' },
  { name: 'Montpreveyres', canton: 'VD', postalCode: '1081' },
  { name: 'Morrens', canton: 'VD', postalCode: '1037' },
  { name: 'Moudon', canton: 'VD', postalCode: '1510' },
  { name: 'Mouthier', canton: 'VD', postalCode: '1433' },
  { name: 'Nyon', canton: 'VD', postalCode: '1260' },
  { name: 'Ogens', canton: 'VD', postalCode: '1082' },
  { name: 'Onnens', canton: 'VD', postalCode: '1425' },
  { name: 'Orbe', canton: 'VD', postalCode: '1350' },
  { name: 'Orny', canton: 'VD', postalCode: '1321' },
  { name: 'Oron', canton: 'VD', postalCode: '1608' },
  { name: 'Oron-la-Ville', canton: 'VD', postalCode: '1608' },
  { name: 'Oron-le-Châtel', canton: 'VD', postalCode: '1609' },
  { name: 'Oulens-sous-Echallens', canton: 'VD', postalCode: '1040' },
  { name: 'Pailly', canton: 'VD', postalCode: '1041' },
  { name: 'Pampigny', canton: 'VD', postalCode: '1142' },
  { name: 'Penthalaz', canton: 'VD', postalCode: '1305' },
  { name: 'Peney-le-Jorat', canton: 'VD', postalCode: '1082' },
  { name: 'Perroy', canton: 'VD', postalCode: '1189' },
  { name: 'Pizy', canton: 'VD', postalCode: '1149' },
  { name: 'Pompaples', canton: 'VD', postalCode: '1318' },
  { name: 'Prahins', canton: 'VD', postalCode: '1425' },
  { name: 'Premier', canton: 'VD', postalCode: '1321' },
  { name: 'Prilly', canton: 'VD', postalCode: '1008' },
  { name: 'Préverenges', canton: 'VD', postalCode: '1124' },
  { name: 'Rances', canton: 'VD', postalCode: '1353' },
  { name: 'Renens', canton: 'VD', postalCode: '1020' },
  { name: 'Rivaz', canton: 'VD', postalCode: '1072' },
  { name: 'Roche', canton: 'VD', postalCode: '1845' },
  { name: 'Romainmôtier', canton: 'VD', postalCode: '1323' },
  { name: 'Ropraz', canton: 'VD', postalCode: '1086' },
  { name: 'Rossens', canton: 'VD', postalCode: '1053' },
  { name: 'Rue', canton: 'VD', postalCode: '1543' },
  { name: 'Rueyres', canton: 'VD', postalCode: '1353' },
  { name: 'Saint-George', canton: 'VD', postalCode: '1188' },
  { name: 'Saint-Livres', canton: 'VD', postalCode: '1182' },
  { name: 'Saint-Légier-La Chiésaz', canton: 'VD', postalCode: '1806' },
  { name: 'Saint-Prex', canton: 'VD', postalCode: '1162' },
  { name: 'Saint-Saphorin', canton: 'VD', postalCode: '1073' },
  { name: 'Saint-Sulpice', canton: 'VD', postalCode: '1025' },
  { name: 'Savigny', canton: 'VD', postalCode: '1073' },
  { name: 'Senarclens', canton: 'VD', postalCode: '1318' },
  { name: 'Servion', canton: 'VD', postalCode: '1086' },
  { name: 'Signy', canton: 'VD', postalCode: '1278' },
  { name: 'Sullens', canton: 'VD', postalCode: '1037' },
  { name: 'Tannay', canton: 'VD', postalCode: '1291' },
  { name: 'Thierrens', canton: 'VD', postalCode: '1514' },
  { name: 'Treycovignens', canton: 'VD', postalCode: '1040' },
  { name: 'Trélex', canton: 'VD', postalCode: '1267' },
  { name: 'Vallorbe', canton: 'VD', postalCode: '1337' },
  { name: 'Vaulion', canton: 'VD', postalCode: '1328' },
  { name: 'Vaux-sur-Morges', canton: 'VD', postalCode: '1114' },
  { name: 'Veigy', canton: 'VD', postalCode: '1245' },
  { name: 'Veytaux', canton: 'VD', postalCode: '1820' },
  { name: 'Vich', canton: 'VD', postalCode: '1867' },
  { name: 'Villars-sous-Yens', canton: 'VD', postalCode: '1169' },
  { name: 'Villeneuve', canton: 'VD', postalCode: '1844' },
  { name: 'Vinzel', canton: 'VD', postalCode: '1189' },
  { name: 'Vufflens-la-Ville', canton: 'VD', postalCode: '1303' },
  { name: 'Vufflens-le-Château', canton: 'VD', postalCode: '1133' },
  { name: 'Vuiteboeuf', canton: 'VD', postalCode: '1442' },
  { name: 'Yens', canton: 'VD', postalCode: '1169' },
  { name: 'Yverdon-les-Bains', canton: 'VD', postalCode: '1400' },
  { name: 'Yvonand', canton: 'VD', postalCode: '1462' },
  { name: 'Agiez', canton: 'VD', postalCode: '1373' },
  { name: 'Arnex-sur-Orbe', canton: 'VD', postalCode: '1321' },
  { name: 'Bullet', canton: 'VD', postalCode: '1451' },
  { name: 'Champvent', canton: 'VD', postalCode: '1442' },
  { name: 'Fiez', canton: 'VD', postalCode: '1429' },
  { name: 'Goumoëns', canton: 'VD', postalCode: '1430' },
  { name: 'Mauborget', canton: 'VD', postalCode: '1451' },
  { name: 'Montcherand', canton: 'VD', postalCode: '1372' },
  { name: 'Novalles', canton: 'VD', postalCode: '1430' },
  { name: 'Ormont-Dessus', canton: 'VD', postalCode: '1863' },
  { name: 'Ormont-Dessous', canton: 'VD', postalCode: '1862' },
  { name: 'Poliez-Pittet', canton: 'VD', postalCode: '1413' },
  { name: 'Provence', canton: 'VD', postalCode: '1451' },
  { name: 'Rossenges', canton: 'VD', postalCode: '1082' },
  { name: 'Sainte-Croix', canton: 'VD', postalCode: '1450' },
  { name: 'Sévery', canton: 'VD', postalCode: '1149' },
  { name: 'Suchy', canton: 'VD', postalCode: '1373' },
  { name: 'Suscévaz', canton: 'VD', postalCode: '1430' },
  { name: 'Vugelles-La Mothe', canton: 'VD', postalCode: '1428' },
  { name: 'Essert-sous-Champvent', canton: 'VD', postalCode: '1442' },
  { name: 'Besse', canton: 'VD', postalCode: '1451' },
  { name: 'La Praz', canton: 'VD', postalCode: '1321' },
  { name: 'Denges', canton: 'VD', postalCode: '1027' },
  { name: 'Fiez', canton: 'VD', postalCode: '1429' },
  { name: 'Montreux', canton: 'VD', postalCode: '1820' },
  { name: 'Vevey', canton: 'VD', postalCode: '1800' },
  { name: 'Bursinel', canton: 'VD', postalCode: '1185' },
  { name: 'Dully', canton: 'VD', postalCode: '1185' },
  { name: 'Bursins', canton: 'VD', postalCode: '1185' },
  { name: 'Gilly', canton: 'VD', postalCode: '1182' },
  { name: 'Founex', canton: 'VD', postalCode: '1297' },
  { name: 'Bogis-Bossey', canton: 'VD', postalCode: '1273' },
  { name: 'Chéserex', canton: 'VD', postalCode: '1274' },
  { name: 'Gingins', canton: 'VD', postalCode: '1274' },
  { name: 'Trélex', canton: 'VD', postalCode: '1267' },
  { name: 'Grens', canton: 'VD', postalCode: '1275' },
  
  // SOLOTHURN (SO) - municipios restantes
  { name: 'Aedermannsdorf', canton: 'SO', postalCode: '4714' },
  { name: 'Aetingen', canton: 'SO', postalCode: '4577' },
  { name: 'Balm bei Günsberg', canton: 'SO', postalCode: '4718' },
  { name: 'Bellach', canton: 'SO', postalCode: '4512' },
  { name: 'Bettlach', canton: 'SO', postalCode: '5044' },
  { name: 'Boningen', canton: 'SO', postalCode: '4627' },
  { name: 'Buchegg', canton: 'SO', postalCode: '4587' },
  { name: 'Burgäschi', canton: 'SO', postalCode: '4587' },
  { name: 'Derendingen', canton: 'SO', postalCode: '4552' },
  { name: 'Deitingen', canton: 'SO', postalCode: '4573' },
  { name: 'Dornach', canton: 'SO', postalCode: '4143' },
  { name: 'Egerkingen', canton: 'SO', postalCode: '4618' },
  { name: 'Eppenberg-Wöschnau', canton: 'SO', postalCode: '5012' },
  { name: 'Erlinsbach', canton: 'SO', postalCode: '5018' },
  { name: 'Feldbrunnen', canton: 'SO', postalCode: '4503' },
  { name: 'Flumenthal', canton: 'SO', postalCode: '4703' },
  { name: 'Gänsbrunnen', canton: 'SO', postalCode: '4718' },
  { name: 'Gempen', canton: 'SO', postalCode: '4145' },
  { name: 'Grenchen', canton: 'SO', postalCode: '2540' },
  { name: 'Günsberg', canton: 'SO', postalCode: '4718' },
  { name: 'Hauenstein', canton: 'SO', postalCode: '4617' },
  { name: 'Hersiwil', canton: 'SO', postalCode: '4577' },
  { name: 'Hochwald', canton: 'SO', postalCode: '4146' },
  { name: 'Hofstetten', canton: 'SO', postalCode: '4462' },
  { name: 'Kammersrohr', canton: 'SO', postalCode: '4718' },
  { name: 'Kappel', canton: 'SO', postalCode: '4577' },
  { name: 'Kienberg', canton: 'SO', postalCode: '5082' },
  { name: 'Kleinlützel', canton: 'SO', postalCode: '4239' },
  { name: 'Kriegstetten', canton: 'SO', postalCode: '4577' },
  { name: 'Langendorf', canton: 'SO', postalCode: '4513' },
  { name: 'Laupersdorf', canton: 'SO', postalCode: '4710' },
  { name: 'Lommiswil', canton: 'SO', postalCode: '4514' },
  { name: 'Lostorf', canton: 'SO', postalCode: '4666' },
  { name: 'Luterbach', canton: 'SO', postalCode: '4572' },
  { name: 'Matzendorf', canton: 'SO', postalCode: '4716' },
  { name: 'Messen', canton: 'SO', postalCode: '4587' },
  { name: 'Mühledorf', canton: 'SO', postalCode: '4587' },
  { name: 'Mümliswil', canton: 'SO', postalCode: '4717' },
  { name: 'Nennigkofen', canton: 'SO', postalCode: '4587' },
  { name: 'Niederbuchsiten', canton: 'SO', postalCode: '4626' },
  { name: 'Niedergösgen', canton: 'SO', postalCode: '5016' },
  { name: 'Oberbuchsiten', canton: 'SO', postalCode: '4625' },
  { name: 'Oberdorf', canton: 'SO', postalCode: '4718' },
  { name: 'Obergösgen', canton: 'SO', postalCode: '5016' },
  { name: 'Olten', canton: 'SO', postalCode: '4600' },
  { name: 'Riedholz', canton: 'SO', postalCode: '4515' },
  { name: 'Rickenbach', canton: 'SO', postalCode: '4703' },
  { name: 'Rohr', canton: 'SO', postalCode: '4143' },
  { name: 'Schönenwerd', canton: 'SO', postalCode: '5012' },
  { name: 'Selzach', canton: 'SO', postalCode: '2545' },
  { name: 'Solothurn', canton: 'SO', postalCode: '4500' },
  { name: 'Stüsslingen', canton: 'SO', postalCode: '4666' },
  { name: 'Trimbach', canton: 'SO', postalCode: '5026' },
  { name: 'Walterswil', canton: 'SO', postalCode: '4715' },
  { name: 'Wangen', canton: 'SO', postalCode: '4703' },
  { name: 'Welschenrohr', canton: 'SO', postalCode: '4716' },
  { name: 'Winznau', canton: 'SO', postalCode: '4702' },
  { name: 'Wisen', canton: 'SO', postalCode: '4494' },
  { name: 'Zuchwil', canton: 'SO', postalCode: '4531' },
  { name: 'Balsthal', canton: 'SO', postalCode: '4710' },
  { name: 'Welschenrohr-Gänsbrunnen', canton: 'SO', postalCode: '4716' },
  
  // AARGAU (AG) - últimos
  { name: 'Ammerswil', canton: 'AG', postalCode: '5600' },
  { name: 'Arni', canton: 'AG', postalCode: '8907' },
  { name: 'Attelwil', canton: 'AG', postalCode: '5055' },
  { name: 'Baldingen', canton: 'AG', postalCode: '5304' },
  { name: 'Benzenschwil', canton: 'AG', postalCode: '5618' },
  { name: 'Bergdietikon', canton: 'AG', postalCode: '8962' },
  { name: 'Berikon', canton: 'AG', postalCode: '8965' },
  { name: 'Besenbüren', canton: 'AG', postalCode: '5625' },
  { name: 'Bettwil', canton: 'AG', postalCode: '5619' },
  { name: 'Biberstein', canton: 'AG', postalCode: '5032' },
  { name: 'Birmenstorf', canton: 'AG', postalCode: '5413' },
  { name: 'Böbikon', canton: 'AG', postalCode: '5305' },
  { name: 'Bözen', canton: 'AG', postalCode: '5084' },
  { name: 'Bremwil', canton: 'AG', postalCode: '5704' },
  { name: 'Brunegg', canton: 'AG', postalCode: '5504' },
  { name: 'Büttikon', canton: 'AG', postalCode: '5616' },
  { name: 'Burg', canton: 'AG', postalCode: '5608' },
  { name: 'Busslingen', canton: 'AG', postalCode: '5444' },
  { name: 'Buttwil', canton: 'AG', postalCode: '5622' },
  { name: 'Densbüren', canton: 'AG', postalCode: '5245' },
  { name: 'Dintikon', canton: 'AG', postalCode: '5606' },
  { name: 'Dottikon', canton: 'AG', postalCode: '5605' },
  { name: 'Dürrenäsch', canton: 'AG', postalCode: '5712' },
  { name: 'Egliswil', canton: 'AG', postalCode: '5703' },
  { name: 'Ehrendingen', canton: 'AG', postalCode: '5305' },
  { name: 'Eiken', canton: 'AG', postalCode: '5074' },
  { name: 'Elfingen', canton: 'AG', postalCode: '5083' },
  { name: 'Endingen', canton: 'AG', postalCode: '5305' },
  { name: 'Ennetbaden', canton: 'AG', postalCode: '5407' },
  { name: 'Erlinsbach', canton: 'AG', postalCode: '5018' },
  { name: 'Fahrwangen', canton: 'AG', postalCode: '5604' },
  { name: 'Fischbach-Göslikon', canton: 'AG', postalCode: '5525' },
  { name: 'Fislisbach', canton: 'AG', postalCode: '5442' },
  { name: 'Freienwil', canton: 'AG', postalCode: '5303' },
  { name: 'Gansingen', canton: 'AG', postalCode: '5272' },
  { name: 'Gebenstorf', canton: 'AG', postalCode: '5412' },
  { name: 'Geltwil', canton: 'AG', postalCode: '5628' },
  { name: 'Gipf-Oberfrick', canton: 'AG', postalCode: '5073' },
  { name: 'Gontenschwil', canton: 'AG', postalCode: '5725' },
  { name: 'Gränichen', canton: 'AG', postalCode: '5722' },
  { name: 'Habsburg', canton: 'AG', postalCode: '5245' },
  { name: 'Hallwil', canton: 'AG', postalCode: '5705' },
  { name: 'Hausen', canton: 'AG', postalCode: '5212' },
  { name: 'Hendschiken', canton: 'AG', postalCode: '5604' },
  { name: 'Hermetschwil-Staffeln', canton: 'AG', postalCode: '5626' },
  { name: 'Hirschthal', canton: 'AG', postalCode: '5042' },
  { name: 'Holderbank', canton: 'AG', postalCode: '5026' },
  { name: 'Hottwil', canton: 'AG', postalCode: '5054' },
  { name: 'Hunzenschwil', canton: 'AG', postalCode: '5502' },
  { name: 'Ittenthal', canton: 'AG', postalCode: '5082' },
  { name: 'Kaiserstuhl', canton: 'AG', postalCode: '8463' },
  { name: 'Kallern', canton: 'AG', postalCode: '5624' },
  { name: 'Killwangen', canton: 'AG', postalCode: '8956' },
  { name: 'Klingnau', canton: 'AG', postalCode: '5313' },
  { name: 'Koblenz', canton: 'AG', postalCode: '5316' },
  { name: 'Küttigen', canton: 'AG', postalCode: '5024' },
  { name: 'Künten', canton: 'AG', postalCode: '5445' },
  { name: 'Leibstadt', canton: 'AG', postalCode: '5325' },
  { name: 'Leimbach', canton: 'AG', postalCode: '5627' },
  { name: 'Leutwil', canton: 'AG', postalCode: '5725' },
  { name: 'Lupfig', canton: 'AG', postalCode: '5112' },
  { name: 'Lunkhofen', canton: 'AG', postalCode: '5408' },
  { name: 'Magden', canton: 'AG', postalCode: '4153' },
  { name: 'Mandach', canton: 'AG', postalCode: '5314' },
  { name: 'Mägenwil', canton: 'AG', postalCode: '5503' },
  { name: 'Menziken', canton: 'AG', postalCode: '5737' },
  { name: 'Merenschwand', canton: 'AG', postalCode: '5634' },
  { name: 'Mittelhäusern', canton: 'AG', postalCode: '5212' },
  { name: 'Mönthal', canton: 'AG', postalCode: '5063' },
  { name: 'Möriken-Wildegg', canton: 'AG', postalCode: '5102' },
  { name: 'Murgenthal', canton: 'AG', postalCode: '4853' },
  { name: 'Niederlenz', canton: 'AG', postalCode: '5702' },
  { name: 'Oberentfelden', canton: 'AG', postalCode: '5036' },
  { name: 'Oberkulm', canton: 'AG', postalCode: '5727' },
  { name: 'Oberlunkhofen', canton: 'AG', postalCode: '8917' },
  { name: 'Obermumpf', canton: 'AG', postalCode: '4325' },
  { name: 'Oberehrendingen', canton: 'AG', postalCode: '5305' },
  { name: 'Obersiggenthal', canton: 'AG', postalCode: '5305' },
  { name: 'Oberwil-Lieli', canton: 'AG', postalCode: '8966' },
  { name: 'Olsberg', canton: 'AG', postalCode: '5042' },
  { name: 'Othmarsingen', canton: 'AG', postalCode: '5504' },
  { name: 'Ottlingen', canton: 'AG', postalCode: '5452' },
  { name: 'Remigen', canton: 'AG', postalCode: '5223' },
  { name: 'Rietheim', canton: 'AG', postalCode: '5332' },
  { name: 'Riniken', canton: 'AG', postalCode: '5222' },
  { name: 'Rohr', canton: 'AG', postalCode: '4118' },
  { name: 'Rottenschwil', canton: 'AG', postalCode: '5607' },
  { name: 'Rudolfstetten-Friedlisberg', canton: 'AG', postalCode: '8964' },
  { name: 'Rüfenach', canton: 'AG', postalCode: '5225' },
  { name: 'Sarmenstorf', canton: 'AG', postalCode: '5612' },
  { name: 'Schafisheim', canton: 'AG', postalCode: '5503' },
  { name: 'Schinznach-Bad', canton: 'AG', postalCode: '5116' },
  { name: 'Schinznach-Dorf', canton: 'AG', postalCode: '5116' },
  { name: 'Schlossrued', canton: 'AG', postalCode: '5056' },
  { name: 'Schmiedrued', canton: 'AG', postalCode: '5057' },
  { name: 'Schupfart', canton: 'AG', postalCode: '5083' },
  { name: 'Schwaderloch', canton: 'AG', postalCode: '5274' },
  { name: 'Seengen', canton: 'AG', postalCode: '5707' },
  { name: 'Seon', canton: 'AG', postalCode: '5702' },
  { name: 'Sins', canton: 'AG', postalCode: '5643' },
  { name: 'Sisseln', canton: 'AG', postalCode: '4334' },
  { name: 'Staffelbach', canton: 'AG', postalCode: '5053' },
  { name: 'Stetten', canton: 'AG', postalCode: '5605' },
  { name: 'Stilli', canton: 'AG', postalCode: '5234' },
  { name: 'Strengelbach', canton: 'AG', postalCode: '4803' },
  { name: 'Sulz', canton: 'AG', postalCode: '5083' },
  { name: 'Tägerig', canton: 'AG', postalCode: '5408' },
  { name: 'Teufenthal', canton: 'AG', postalCode: '5723' },
  { name: 'Thalheim', canton: 'AG', postalCode: '5082' },
  { name: 'Turgi', canton: 'AG', postalCode: '5305' },
  { name: 'Uerkheim', canton: 'AG', postalCode: '4813' },
  { name: 'Unterentfelden', canton: 'AG', postalCode: '5035' },
  { name: 'Unterkulm', canton: 'AG', postalCode: '5726' },
  { name: 'Unterlunkhofen', canton: 'AG', postalCode: '8918' },
  { name: 'Villigen', canton: 'AG', postalCode: '5236' },
  { name: 'Villmergen', canton: 'AG', postalCode: '5612' },
  { name: 'Vordemwald', canton: 'AG', postalCode: '4813' },
  { name: 'Wegenstetten', canton: 'AG', postalCode: '4118' },
  { name: 'Widen', canton: 'AG', postalCode: '8967' },
  { name: 'Wiliberg', canton: 'AG', postalCode: '5056' },
  { name: 'Wölflinswil', canton: 'AG', postalCode: '5083' },
  { name: 'Zetzwil', canton: 'AG', postalCode: '5729' },
  { name: 'Zeiningen', canton: 'AG', postalCode: '4314' },
  { name: 'Zuzgen', canton: 'AG', postalCode: '4315' },
  
  // BASEL-LANDSCHAFT (BL) - últimos
  { name: 'Aesch', canton: 'BL', postalCode: '4147' },
  { name: 'Allschwil', canton: 'BL', postalCode: '4123' },
  { name: 'Anwil', canton: 'BL', postalCode: '4463' },
  { name: 'Arlesheim', canton: 'BL', postalCode: '4144' },
  { name: 'Bennwil', canton: 'BL', postalCode: '4448' },
  { name: 'Binningen', canton: 'BL', postalCode: '4102' },
  { name: 'Birsfelden', canton: 'BL', postalCode: '4127' },
  { name: 'Böckten', canton: 'BL', postalCode: '4461' },
  { name: 'Bottmingen', canton: 'BL', postalCode: '4103' },
  { name: 'Bretzwil', canton: 'BL', postalCode: '4206' },
  { name: 'Bubendorf', canton: 'BL', postalCode: '4416' },
  { name: 'Buckten', canton: 'BL', postalCode: '4449' },
  { name: 'Buus', canton: 'BL', postalCode: '4454' },
  { name: 'Diepflingen', canton: 'BL', postalCode: '4441' },
  { name: 'Diegten', canton: 'BL', postalCode: '4453' },
  { name: 'Duggingen', canton: 'BL', postalCode: '4203' },
  { name: 'Eptingen', canton: 'BL', postalCode: '4458' },
  { name: 'Frenkendorf', canton: 'BL', postalCode: '4402' },
  { name: 'Füllinsdorf', canton: 'BL', postalCode: '4414' },
  { name: 'Giebenach', canton: 'BL', postalCode: '4305' },
  { name: 'Grellingen', canton: 'BL', postalCode: '4203' },
  { name: 'Hemmiken', canton: 'BL', postalCode: '4462' },
  { name: 'Hölstein', canton: 'BL', postalCode: '4447' },
  { name: 'Itingen', canton: 'BL', postalCode: '4452' },
  { name: 'Känerkinden', canton: 'BL', postalCode: '4461' },
  { name: 'Kilchberg', canton: 'BL', postalCode: '4447' },
  { name: 'Lampenberg', canton: 'BL', postalCode: '4448' },
  { name: 'Langenbruck', canton: 'BL', postalCode: '4438' },
  { name: 'Laufen', canton: 'BL', postalCode: '4225' },
  { name: 'Lausen', canton: 'BL', postalCode: '4415' },
  { name: 'Läufelfingen', canton: 'BL', postalCode: '4448' },
  { name: 'Liedertswil', canton: 'BL', postalCode: '4438' },
  { name: 'Liesberg', canton: 'BL', postalCode: '4226' },
  { name: 'Maisprach', canton: 'BL', postalCode: '4124' },
  { name: 'Muttenz', canton: 'BL', postalCode: '4132' },
  { name: 'Nusshof', canton: 'BL', postalCode: '4445' },
  { name: 'Oberdorf', canton: 'BL', postalCode: '4436' },
  { name: 'Oberwil', canton: 'BL', postalCode: '4104' },
  { name: 'Oltingen', canton: 'BL', postalCode: '4454' },
  { name: 'Ormalingen', canton: 'BL', postalCode: '4464' },
  { name: 'Pfeffingen', canton: 'BL', postalCode: '4109' },
  { name: 'Pratteln', canton: 'BL', postalCode: '4133' },
  { name: 'Ramlinsburg', canton: 'BL', postalCode: '4445' },
  { name: 'Reigoldswil', canton: 'BL', postalCode: '4438' },
  { name: 'Reinach', canton: 'BL', postalCode: '4153' },
  { name: 'Rickenbach', canton: 'BL', postalCode: '4457' },
  { name: 'Röschenz', canton: 'BL', postalCode: '4233' },
  { name: 'Rothenfluh', canton: 'BL', postalCode: '4466' },
  { name: 'Rümlingen', canton: 'BL', postalCode: '4458' },
  { name: 'Rünenberg', canton: 'BL', postalCode: '4467' },
  { name: 'Seltisberg', canton: 'BL', postalCode: '4411' },
  { name: 'Sissach', canton: 'BL', postalCode: '4450' },
  { name: 'Tecknau', canton: 'BL', postalCode: '4455' },
  { name: 'Tierstein', canton: 'BL', postalCode: '4226' },
  { name: 'Wahlen', canton: 'BL', postalCode: '4233' },
  { name: 'Waldenburg', canton: 'BL', postalCode: '4437' },
  { name: 'Wenslingen', canton: 'BL', postalCode: '4467' },
  { name: 'Witterswil', canton: 'BL', postalCode: '4108' },
  { name: 'Ziefen', canton: 'BL', postalCode: '4414' },
  { name: 'Zunzgen', canton: 'BL', postalCode: '4447' },
  { name: 'Zeglingen', canton: 'BL', postalCode: '4455' },
  { name: 'Hofstetten-Flüh', canton: 'BL', postalCode: '4108' },
  { name: 'Nenzlingen', canton: 'BL', postalCode: '4224' },
  { name: 'Burg im Leimental', canton: 'BL', postalCode: '4108' },
]

function createSlug(name: string, canton: string): string {
  return name
    .toLowerCase()
    .replace(/[àáâäæãåā]/g, 'a')
    .replace(/[èéêëēėę]/g, 'e')
    .replace(/[îïíīįì]/g, 'i')
    .replace(/[ôöòóœøōõ]/g, 'o')
    .replace(/[ûüùúū]/g, 'u')
    .replace(/[çćč]/g, 'c')
    .replace(/[ß]/g, 'ss')
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .trim() + '-' + canton.toLowerCase()
}

async function main() {
  console.log('🌍 Agregando últimos municipios faltantes...')
  console.log('='.repeat(60))
  
  let added = 0
  let updated = 0
  let skipped = 0
  
  for (const municipality of finalMunicipalities) {
    const canton = await prisma.canton.findUnique({
      where: { code: municipality.canton }
    })
    
    if (!canton) {
      skipped++
      continue
    }
    
    const slug = createSlug(municipality.name, municipality.canton)
    
    const existing = await prisma.city.findFirst({
      where: {
        name: municipality.name,
        cantonId: canton.id
      }
    })
    
    if (existing) {
      if (municipality.postalCode && existing.postalCode !== municipality.postalCode) {
        try {
          await prisma.city.update({
            where: { id: existing.id },
            data: { 
              postalCode: municipality.postalCode,
              updatedAt: new Date()
            }
          })
          updated++
        } catch (e) {}
      }
      continue
    }
    
    try {
      await prisma.city.create({
        data: {
          id: `city_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
          name: municipality.name,
          slug: slug,
          postalCode: municipality.postalCode,
          cantonId: canton.id,
          updatedAt: new Date()
        }
      })
      added++
      
      if (added % 50 === 0) {
        console.log(`✓ Procesados ${added} municipios nuevos...`)
      }
    } catch (error: any) {
      if (error.code !== 'P2002') {}
    }
  }
  
  console.log('\n' + '='.repeat(60))
  console.log('✅ SEED COMPLETADO!')
  console.log('='.repeat(60))
  console.log(`📊 Municipios agregados: ${added}`)
  console.log(`📊 Municipios actualizados: ${updated}`)
  console.log(`📊 Omitidos: ${skipped}`)
  
  const total = await prisma.city.count()
  console.log(`\n📈 Total de ciudades en base de datos: ${total}`)
}

main()
  .catch((e) => {
    console.error('❌ Error:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
