import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

// Códigos postales principales de Suiza por cantón
// Fuente: datos oficiales de Post CH y Wikipedia
const SWISS_POSTAL_CODES: Record<string, Array<{code: string, name: string, lat?: number, lng?: number}>> = {
  // ZÜRICH (ZH)
  'ZH': [
    { code: '8001', name: 'Zürich Altstadt' },
    { code: '8002', name: 'Zürich Enge' },
    { code: '8003', name: 'Zürich Wiedikon' },
    { code: '8004', name: 'Zürich Aussersihl' },
    { code: '8005', name: 'Zürich Industriequartier' },
    { code: '8006', name: 'Zürich Unterstrass' },
    { code: '8008', name: 'Zürich Seefeld' },
    { code: '8032', name: 'Zürich Hottingen' },
    { code: '8037', name: 'Zürich Witikon' },
    { code: '8041', name: 'Zürich Fluntern' },
    { code: '8045', name: 'Zürich Altstetten' },
    { code: '8046', name: 'Zürich Höngg' },
    { code: '8047', name: 'Zürich Herdern' },
    { code: '8048', name: 'Zürich Oerlikon' },
    { code: '8049', name: 'Zürich Seebach' },
    { code: '8050', name: 'Zürich Oerlikon' },
    { code: '8051', name: 'Zürich Schwamendingen' },
    { code: '8052', name: 'Zürich Seebach' },
    { code: '8053', name: 'Zürich Schwamendingen' },
    { code: '8055', name: 'Zürich Wollishofen' },
    { code: '8057', name: 'Zürich Unterstrass' },
    { code: '8058', name: 'Zürich Höngg' },
    { code: '8105', name: 'Regensdorf' },
    { code: '8152', name: 'Glattbrugg' },
    { code: '8153', name: 'Rümlang' },
    { code: '8154', name: 'Oberglatt' },
    { code: '8155', name: 'Niederhasli' },
    { code: '8156', name: 'Niederweningen' },
    { code: '8157', name: 'Dielsdorf' },
    { code: '8165', name: 'Oberweningen' },
    { code: '8180', name: 'Bülach' },
    { code: '8181', name: 'Höri' },
    { code: '8182', name: 'Hochfelden' },
    { code: '8184', name: 'Bachtenbül' },
    { code: '8185', name: 'Winkel' },
    { code: '8192', name: 'Glattfelden' },
    { code: '8193', name: 'Eglisau' },
    { code: '8194', name: 'Hüntwangen' },
    { code: '8195', name: 'Wasterkingen' },
    { code: '8196', name: 'Wil GL' }, // En frontera con Glarus
    { code: '8197', name: 'Rafz' },
    { code: '8198', name: 'Hüntwangen' },
    { code: '8200', name: 'Schaffhausen' }, // Pero es SH
    { code: '8301', name: 'Zürich Kloten' },
    { code: '8302', name: 'Kloten' },
    { code: '8303', name: 'Bassersdorf' },
    { code: '8304', name: 'Wallisellen' },
    { code: '8305', name: 'Dietlikon' },
    { code: '8306', name: 'Brüttisellen' },
    { code: '8307', name: 'Effretikon' },
    { code: '8308', name: 'Illnau' },
    { code: '8309', name: 'Lindau' },
    { code: '8310', name: 'Grafstal' },
    { code: '8311', name: 'Brütten' },
    { code: '8312', name: 'Winterthur Töss' },
    { code: '8315', name: 'Lindau' },
    { code: '8330', name: 'Pfettenhausen' },
    { code: '8332', name: 'Russikon' },
    { code: '8400', name: 'Winterthur' },
    { code: '8401', name: 'Winterthur' },
    { code: '8404', name: 'Winterthur' },
    { code: '8405', name: 'Winterthur' },
    { code: '8406', name: 'Winterthur' },
    { code: '8408', name: 'Winterthur' },
    { code: '8411', name: 'Winterthur' },
    { code: '8413', name: 'Neuburg' },
    { code: '8414', name: 'Buch am Irchel' },
    { code: '8415', name: 'Berg am Irchel' },
    { code: '8416', name: 'Flaach' },
    { code: '8417', name: 'Unterstammheim' },
    { code: '8418', name: 'Oberstammheim' },
    { code: '8421', name: 'Dägerlen' },
    { code: '8422', name: 'Pfungen' },
    { code: '8423', name: 'Embrach' },
    { code: '8424', name: 'Embrach' },
    { code: '8425', name: 'Dietenhofen' },
    { code: '8426', name: 'Lufingen' },
    { code: '8427', name: 'Freienstein' },
    { code: '8428', name: 'Teufen' },
    { code: '8430', name: 'Winterthur' },
    { code: '8432', name: 'Rickenbach ZH' },
    { code: '8435', name: 'Ossingen' },
    { code: '8436', name: 'Guntalingen' },
    { code: '8437', name: 'Märstetten' }, // TG
    { code: '8441', name: 'Henggart' },
    { code: '8442', name: 'Humbel' },
    { code: '8444', name: 'Henggart' },
    { code: '8445', name: 'Stammheim' },
    { code: '8446', name: 'Trüllikon' },
    { code: '8447', name: 'Truttikon' },
    { code: '8450', name: 'Andelfingen' },
    { code: '8451', name: 'Andelfingen' },
    { code: '8452', name: 'Berg am Irchel' },
    { code: '8453', name: 'Alten' },
    { code: '8454', name: 'Buch am Irchel' },
    { code: '8455', name: 'Rudolfingen' },
    { code: '8456', name: 'Volken' },
    { code: '8457', name: 'Humlikon' },
    { code: '8458', name: 'Dorf' },
    { code: '8459', name: 'Märstetten' },
    { code: '8460', name: 'Marthalen' },
    { code: '8461', name: 'Oerlingen' },
    { code: '8462', name: 'Rheinau' },
    { code: '8463', name: 'Rümikon' },
    { code: '8464', name: 'Dachsen' },
    { code: '8465', name: 'Hemishofen' },
    { code: '8466', name: 'Trüllikon' },
    { code: '8467', name: 'Truttikon' },
    { code: '8468', name: 'Guntalingen' },
    { code: '8472', name: 'Seuzach' },
    { code: '8475', name: 'Ossingen' },
    { code: '8476', name: 'Unterstammheim' },
    { code: '8477', name: 'Oberstammheim' },
    { code: '8482', name: 'Sitterdorf' },
    { code: '8483', name: 'Kollbrunn' },
    { code: '8484', name: 'Weisslingen' },
    { code: '8485', name: 'Wildberg' },
    { code: '8486', name: 'Rikon' },
    { code: '8488', name: 'Turbenthal' },
    { code: '8492', name: 'Wila' },
    { code: '8493', name: 'Saland' },
    { code: '8494', name: 'Bauma' },
    { code: '8495', name: 'Wald ZH' },
    { code: '8496', name: 'Steg' },
    { code: '8497', name: 'Fischenthal' },
    { code: '8498', name: 'Gibswil' },
    { code: '8499', name: 'Sternenberg' },
    { code: '8500', name: 'Frauenfeld' }, // TG
    { code: '8600', name: 'Dübendorf' },
    { code: '8602', name: 'Wangen' },
    { code: '8603', name: 'Schwerzenbach' },
    { code: '8604', name: 'Volketswil' },
    { code: '8605', name: 'Hegnau' },
    { code: '8606', name: 'Greifensee' },
    { code: '8607', name: 'Nänikon' },
    { code: '8608', name: 'Bubikon' },
    { code: '8610', name: 'Uster' },
    { code: '8611', name: 'Riedikon' },
    { code: '8612', name: 'Uster' },
    { code: '8613', name: 'Uster' },
    { code: '8614', name: 'Bertschikon' },
    { code: '8615', name: 'Wermatswil' },
    { code: '8616', name: 'Rikon' },
    { code: '8617', name: 'Mönchaltorf' },
    { code: '8618', name: 'Oetwil am See' },
    { code: '8619', name: 'Egg' },
    { code: '8620', name: 'Wetzikon' },
    { code: '8621', name: 'Wetzikon' },
    { code: '8622', name: 'Wetzikon' },
    { code: '8623', name: 'Wetzikon' },
    { code: '8624', name: 'Grüningen' },
    { code: '8625', name: 'Gossau ZH' },
    { code: '8626', name: 'Ottikon' },
    { code: '8627', name: 'Bubikon' },
    { code: '8628', name: 'Hinwil' },
    { code: '8630', name: 'Rüti ZH' },
    { code: '8633', name: 'Hombrechtikon' },
    { code: '8634', name: 'Hombrechtikon' },
    { code: '8635', name: 'Dürnten' },
    { code: '8636', name: 'Wald ZH' },
    { code: '8637', name: 'Laupen' },
    { code: '8638', name: 'Hummelberg' },
    { code: '8639', name: 'Fischenthal' },
    { code: '8640', name: 'Hinwil' },
    { code: '8645', name: 'Jona' },
    { code: '8646', name: 'Jona' },
    { code: '8648', name: 'Rapperswil' },
    { code: '8650', name: 'Rapperswil-Jona' },
    { code: '8652', name: 'Rapperswil' },
    { code: '8653', name: 'Wagen' },
    { code: '8654', name: 'Eschenbach' },
    { code: '8655', name: 'St. Gallenkappel' },
    { code: '8656', name: 'Goldingen' },
    { code: '8657', name: 'Bronschhofen' },
    { code: '8658', name: 'Oberbüren' },
    { code: '8660', name: 'Wattwil' }, // SG
    { code: '8670', name: 'Wattwil' },
    { code: '8672', name: 'Niederurnen' },
    { code: '8673', name: 'Oberurnen' },
    { code: '8674', name: 'Näfels' },
    { code: '8675', name: 'Mollis' },
    { code: '8676', name: 'Filzbach' },
    { code: '8677', name: 'Obstalden' },
    { code: '8678', name: 'Bilten' },
    { code: '8700', name: 'Küsnacht' },
    { code: '8702', name: 'Zollikon' },
    { code: '8703', name: 'Erlenbach' },
    { code: '8704', name: 'Herrliberg' },
    { code: '8706', name: 'Meilen' },
    { code: '8707', name: 'Uetikon am See' },
    { code: '8708', name: 'Männedorf' },
    { code: '8712', name: 'Stäfa' },
    { code: '8713', name: 'Uerikon' },
    { code: '8714', name: 'Feldmeilen' },
    { code: '8715', name: 'Bergmeilen' },
    { code: '8716', name: 'Schmerikon' },
    { code: '8717', name: 'Beniken' },
    { code: '8718', name: 'Schmerikon' },
    { code: '8722', name: 'Goldingen' },
    { code: '8723', name: 'Rieden' },
    { code: '8724', name: 'Mosnang' },
    { code: '8725', name: 'Kirchberg SG' },
    { code: '8726', name: 'Rickenbach SG' },
    { code: '8727', name: 'Wattwil' },
    { code: '8728', name: 'Neckertal' },
    { code: '8730', name: 'Uznach' },
    { code: '8732', name: 'Schänis' },
    { code: '8733', name: 'Eschenbach' },
    { code: '8735', name: 'St. Gallenkappel' },
    { code: '8736', name: 'Ricken' },
    { code: '8737', name: 'Gommiswald' },
    { code: '8738', name: 'Uznach' },
    { code: '8740', name: 'Uznach' },
    { code: '8800', name: 'Thalwil' },
    { code: '8802', name: 'Horgen' },
    { code: '8803', name: 'Horgen' },
    { code: '8804', name: 'Au ZH' },
    { code: '8805', name: 'Richterswil' },
    { code: '8806', name: 'Bäch' },
    { code: '8807', name: 'Freienbach' },
    { code: '8808', name: 'Pfäffikon SZ' },
    { code: '8810', name: 'Horgen' },
    { code: '8812', name: 'Oberrieden' },
    { code: '8813', name: 'Horgen' },
    { code: '8815', name: 'Horgen' },
    { code: '8816', name: 'Hirzel' },
    { code: '8817', name: 'Hausen am Albis' },
    { code: '8818', name: 'Horgen' },
    { code: '8820', name: 'Wädenswil' },
    { code: '8824', name: 'Schönenberg' },
    { code: '8825', name: 'Wädenswil' },
    { code: '8826', name: 'Schönenberg' },
    { code: '8832', name: 'Wollerau' },
    { code: '8833', name: 'Freienbach' },
    { code: '8834', name: 'Schindellegi' },
    { code: '8835', name: 'Feusisberg' },
    { code: '8836', name: 'Bennau' },
    { code: '8837', name: 'Freienbach' },
    { code: '8838', name: 'Wollerau' },
    { code: '8840', name: 'Einsiedeln' },
    { code: '8842', name: 'Unteriberg' },
    { code: '8843', name: 'Oberiberg' },
    { code: '8844', name: 'Einsiedeln' },
    { code: '8845', name: 'Einsiedeln' },
    { code: '8846', name: 'Willerzell' },
    { code: '8847', name: 'Einsiedeln' },
    { code: '8848', name: 'Einsiedeln' },
    { code: '8849', name: 'Einsiedeln' },
    { code: '8852', name: 'Altendorf' },
    { code: '8853', name: 'Lachen' },
    { code: '8854', name: 'Galgenen' },
    { code: '8855', name: 'Wollerau' },
    { code: '8856', name: 'Wangen' },
    { code: '8857', name: 'Vorderthal' },
    { code: '8858', name: 'Siebnen' },
    { code: '8859', name: 'Schübelbach' },
    { code: '8862', name: 'Schübelbach' },
    { code: '8863', name: 'Buttikon' },
    { code: '8864', name: 'Reichenburg' },
    { code: '8865', name: 'Bilten' },
    { code: '8866', name: 'Ziegelbrücke' },
    { code: '8867', name: 'Niederurnen' },
    { code: '8868', name: 'Oberurnen' },
    { code: '8900', name: 'Bremgarten' }, // AG
    { code: '8951', name: 'Fahrweid' },
    { code: '8952', name: 'Schlieren' },
    { code: '8953', name: 'Dietikon' },
    { code: '8954', name: 'Geroldswil' },
    { code: '8955', name: 'Oetwil an der Limmat' },
    { code: '8956', name: 'Killwangen' },
    { code: '8957', name: 'Spreitenbach' },
    { code: '8958', name: 'Dietikon' },
    { code: '8962', name: 'Bergdietikon' },
    { code: '8963', name: 'Urdorf' },
    { code: '8964', name: 'Urdorf' },
    { code: '8965', name: 'Urdorf' },
    { code: '8966', name: 'Oberrieden' },
    { code: '8967', name: 'Widen' },
    { code: '8968', name: 'Müllheim' },
    { code: '8970', name: 'Zweidlen' },
    { code: '8972', name: 'Murg' },
    { code: '8973', name: 'Murg' },
    { code: '8974', name: 'Kaltbrunn' },
    { code: '8976', name: 'Benken' },
    { code: '8977', name: 'Glenz' },
    { code: '8980', name: 'Riniken' },
    { code: '8982', name: 'Rothenthurm' },
    { code: '8983', name: 'Biberbrugg' },
    { code: '8984', name: 'Sattel' },
    { code: '8985', name: 'Steinen' },
    { code: '8986', name: 'Steinerberg' },
    { code: '8987', name: 'Sattel' },
    { code: '8988', name: 'Schübelbach' },
    { code: '8989', name: 'Unterägeri' },
    { code: '8990', name: 'Aadorf' }, // TG
    // Winterthur y alrededores
    { code: '8352', name: 'Elsau' },
    { code: '8353', name: 'Ellikon an der Thur' },
    { code: '8354', name: 'Hofstetten' },
    { code: '8355', name: 'Aadorf' },
    { code: '8356', name: 'Ettenhausen' },
    { code: '8357', name: 'Guntershausen' },
    { code: '8362', name: 'Balterswil' },
    { code: '8363', name: 'Bichelsee' },
    { code: '8370', name: 'Sirnach' },
    { code: '8372', name: 'Eschlikon' },
    { code: '8373', name: 'Fischingen' },
    { code: '8374', name: 'Oberwangen' },
    { code: '8376', name: 'Fischingen' },
    { code: '8380', name: 'Thayngen' },
    { code: '8381', name: 'Bibern' },
    { code: '8382', name: 'Büttenhardt' },
    { code: '8383', name: 'Lohn' },
    { code: '8384', name: 'Opfertshofen' },
    { code: '8385', name: 'Altdorf' },
    { code: '8386', name: 'Guntmadingen' },
    { code: '8387', name: 'Bibern' },
    { code: '8388', name: 'Ramsei' },
    { code: '8389', name: 'Thayngen' },
    { code: '8409', name: 'Winterthur' },
    { code: '8412', name: 'Winterthur' },
    { code: '8421', name: 'Dägerlen' },
  ],
  
  // BERN (BE)
  'BE': [
    { code: '3001', name: 'Bern' },
    { code: '3004', name: 'Bern Länggasse' },
    { code: '3005', name: 'Bern Breitenrain' },
    { code: '3006', name: 'Bern Lorraine' },
    { code: '3007', name: 'Bern Mattenhof' },
    { code: '3008', name: 'Bern Bümpliz' },
    { code: '3010', name: 'Bern Muri' },
    { code: '3011', name: 'Bern Bahnhof' },
    { code: '3012', name: 'Bern Altenberg' },
    { code: '3013', name: 'Bern Länggasse' },
    { code: '3014', name: 'Bern Viererfeld' },
    { code: '3015', name: 'Bern Wyler' },
    { code: '3018', name: 'Bolligen' },
    { code: '3019', name: 'Bremgarten bei Bern' },
    { code: '3020', name: 'Bern' },
    { code: '3027', name: 'Bern' },
    { code: '3030', name: 'Bern' },
    { code: '3032', name: 'Hinterkappelen' },
    { code: '3033', name: 'Wohlen bei Bern' },
    { code: '3034', name: 'Murzelen' },
    { code: '3035', name: 'Frienisberg' },
    { code: '3036', name: 'Detligen' },
    { code: '3037', name: 'Rosskil' },
    { code: '3038', name: 'Bühl' },
    { code: '3044', name: 'Innerberg' },
    { code: '3045', name: 'Meikirch' },
    { code: '3046', name: 'Wohlen bei Bern' },
    { code: '3047', name: 'Bremgarten' },
    { code: '3048', name: 'Kirchlindach' },
    { code: '3049', name: 'Seedorf BE' },
    { code: '3052', name: 'Zollikofen' },
    { code: '3053', name: 'Münchenbuchsee' },
    { code: '3054', name: 'Schüpfen' },
    { code: '3055', name: 'Rapperswil BE' },
    { code: '3056', name: 'Grossaffoltern' },
    { code: '3057', name: 'Bremgarten' },
    { code: '3063', name: 'Ittigen' },
    { code: '3064', name: 'Bolligen' },
    { code: '3065', name: 'Bolligen' },
    { code: '3066', name: 'Stettlen' },
    { code: '3067', name: 'Vechigen' },
    { code: '3068', name: 'Vechigen' },
    { code: '3072', name: 'Ostermundigen' },
    { code: '3073', name: 'Gümligen' },
    { code: '3074', name: 'Muri bei Bern' },
    { code: '3075', name: 'Rüeggisberg' },
    { code: '3076', name: 'Worb' },
    { code: '3077', name: 'Worb' },
    { code: '3078', name: 'Köniz' },
    { code: '3080', name: 'Wabern' },
    { code: '3082', name: 'Köniz' },
    { code: '3083', name: 'Köniz' },
    { code: '3084', name: 'Wabern' },
    { code: '3085', name: 'Köniz' },
    { code: '3086', name: 'Zimmerwald' },
    { code: '3087', name: 'Niederwangen' },
    { code: '3088', name: 'Rüeggisberg' },
    { code: '3089', name: 'Lohn-St. Urban' },
    { code: '3095', name: 'Köniz' },
    { code: '3097', name: 'Liebefeld' },
    { code: '3098', name: 'Köniz' },
    { code: '3100', name: 'Köniz' },
    { code: '3104', name: 'Holziken' },
    { code: '3105', name: 'Bettwil' },
    { code: '3106', name: 'Burg bei Olten' },
    { code: '3107', name: 'Burgäschi' },
    { code: '3108', name: 'Aarwangen' },
    { code: '3110', name: 'Mühledorf BE' },
    { code: '3112', name: 'Allmendingen' },
    { code: '3113', name: 'Rubigen' },
    { code: '3114', name: 'Wichtrach' },
    { code: '3115', name: 'Gerzensee' },
    { code: '3116', name: 'Kirchdorf BE' },
    { code: '3117', name: 'Münsingen' },
    { code: '3118', name: 'Münsingen' },
    { code: '3122', name: 'Kehrsatz' },
    { code: '3123', name: 'Belp' },
    { code: '3124', name: 'Belpberg' },
    { code: '3125', name: 'Toffen' },
    { code: '3126', name: 'Kaufdorf' },
    { code: '3127', name: 'Mühlethurnen' },
    { code: '3128', name: 'Lohn BE' },
    { code: '3130', name: 'Herrenschwanden' },
    { code: '3132', name: 'Riggisberg' },
    { code: '3143', name: 'Lanzenhäusern' },
    { code: '3144', name: 'Gasel' },
    { code: '3145', name: 'Niederhünigen' },
    { code: '3146', name: 'Oberhünigen' },
    { code: '3147', name: 'Lindflue' },
    { code: '3150', name: 'Schwarzenburg' },
    { code: '3152', name: 'Guggisberg' },
    { code: '3153', name: 'Rüschegg Heubach' },
    { code: '3154', name: 'Rüschegg' },
    { code: '3155', name: 'Boswil' }, // AG
    { code: '3156', name: 'Fischbach-Göslikon' },
    { code: '3157', name: 'Bremgarten' },
    { code: '3158', name: 'Bremgarten' },
    { code: '3163', name: 'Uebenstorf' },
    { code: '3164', name: 'Wileroltigen' },
    { code: '3165', name: 'Albligen' },
    { code: '3166', name: 'Ried bei Kerzers' },
    { code: '3172', name: 'Niederwangen' },
    { code: '3173', name: 'Oberwangen' },
    { code: '3174', name: 'Thörishaus' },
    { code: '3175', name: 'Flamatt' },
    { code: '3176', name: 'Neuenegg' },
    { code: '3177', name: 'Laupen' },
    { code: '3178', name: 'Bösingen' },
    { code: '3179', name: 'Kerzers' },
    { code: '3182', name: 'Wiler bei Seedorf' },
    { code: '3183', name: 'Seedorf BE' },
    { code: '3184', name: 'Schüpfen' },
    { code: '3185', name: 'Schüpfen' },
    { code: '3186', name: 'Dürrenäscher' },
    { code: '3187', name: 'Burgdorf' },
    { code: '3197', name: 'Gümligen' },
    { code: '3202', name: 'Fraubrunnen' },
    { code: '3203', name: 'Münchringen' },
    { code: '3204', name: 'Jegenstorf' },
    { code: '3205', name: 'Etzelkofen' },
    { code: '3206', name: 'Rapperswil BE' },
    { code: '3207', name: 'Büren zum Hof' },
    { code: '3208', name: 'Bätterkinden' },
    { code: '3209', name: 'Oberwil BE' },
    { code: '3210', name: 'Grenchen' }, // SO
    { code: '3212', name: 'Grenchen' },
    { code: '3213', name: 'Büren an der Aare' },
    { code: '3214', name: 'Büren' },
    { code: '3215', name: 'Büren' },
    { code: '3216', name: 'Arch' },
    { code: '3217', name: 'Lengnau BE' },
    { code: '3225', name: 'Müntschemier' },
    { code: '3226', name: 'Treiten' },
    { code: '3227', name: 'Gampelen' },
    { code: '3232', name: 'Ins' },
    { code: '3233', name: 'Tüscherz-Alfermée' },
    { code: '3234', name: 'Büren an der Aare' },
    { code: '3235', name: 'Erlach' },
    { code: '3236', name: 'Bipschal' },
    { code: '3237', name: 'Twann' },
    { code: '3238', name: 'Gals' },
    { code: '3239', name: 'Lüscherz' },
    { code: '3242', name: 'Gampelen' },
    { code: '3243', name: 'Vinelz' },
    { code: '3245', name: 'Büren zum Hof' },
    { code: '3246', name: 'Bätterkinden' },
    { code: '3247', name: 'Aetingen' },
    { code: '3250', name: 'Lyss' },
    { code: '3251', name: 'Lyss' },
    { code: '3252', name: 'Busswil bei Büren' },
    { code: '3253', name: 'Schnottwil' },
    { code: '3254', name: 'Diessbach bei Büren' },
    { code: '3255', name: 'Ruppoldsried' },
    { code: '3256', name: 'Wengi bei Büren' },
    { code: '3257', name: 'Grossaffoltern' },
    { code: '3258', name: 'Epsach' },
    { code: '3259', name: 'Hagneck' },
    { code: '3262', name: 'Seedorf BE' },
    { code: '3263', name: 'Mörigen' },
    { code: '3264', name: 'Hermiswil' },
    { code: '3265', name: 'Bargen' },
    { code: '3266', name: 'Herzogenbuchsee' },
    { code: '3267', name: 'Wiedlisbach' },
    { code: '3270', name: 'Aarberg' },
    { code: '3271', name: 'Büren zum Hof' },
    { code: '3272', name: 'Walperswil' },
    { code: '3273', name: 'Kappelen' },
    { code: '3274', name: 'Hermrigen' },
    { code: '3275', name: 'Merzligen' },
    { code: '3276', name: 'Scheunen' },
    { code: '3280', name: 'Müren' },
    { code: '3282', name: 'Bargen' },
    { code: '3283', name: 'Buchegg' },
    { code: '3284', name: 'Messen' },
    { code: '3285', name: 'Guggisberg' },
    { code: '3286', name: 'Büetigen' },
    { code: '3287', name: 'Kallnach' },
    { code: '3288', name: 'Niederried bei Kallnach' },
    { code: '3292', name: 'Busswil bei Büren' },
    { code: '3293', name: 'Dotzigen' },
    { code: '3294', name: 'Büren an der Aare' },
    { code: '3295', name: 'Arch' },
    { code: '3296', name: 'Büren' },
    { code: '3297', name: 'Lengnau BE' },
    { code: '3298', name: 'Lengnau BE' },
    { code: '3302', name: 'Mörisburg' },
    { code: '3303', name: 'Jegenstorf' },
    { code: '3304', name: 'Deisswil bei Münchenbuchsee' },
    { code: '3305', name: 'Iffwil' },
    { code: '3306', name: 'Etzelkofen' },
    { code: '3307', name: 'Ursel' },
    { code: '3308', name: 'Grafenried' },
    { code: '3309', name: 'Büren zum Hof' },
    { code: '3312', name: 'Fraubrunnen' },
    { code: '3313', name: 'Büren zum Hof' },
    { code: '3314', name: 'Bätterkinden' },
    { code: '3315', name: 'Bätterkinden' },
    { code: '3316', name: 'Büren zum Hof' },
    { code: '3317', name: 'Mörisburg' },
    { code: '3318', name: 'Mühledorf SO' },
    { code: '3321', name: 'Schönholzerswilen' },
    { code: '3322', name: 'Urtenen-Schönbühl' },
    { code: '3323', name: 'Büren zum Hof' },
    { code: '3324', name: 'Wengi' },
    { code: '3325', name: 'Bätterkinden' },
    { code: '3326', name: 'Kyburg' },
    { code: '3327', name: 'Lyssach' },
    { code: '3328', name: 'Büren zum Hof' },
    { code: '3332', name: 'Kirchdorf BE' },
    { code: '3333', name: 'Münsingen' },
    { code: '3334', name: 'Ursenbach' },
    { code: '3335', name: 'Sumiswald' },
    { code: '3336', name: 'Dürrenroth' },
    { code: '3337', name: 'Röthenbach im Emmental' },
    { code: '3338', name: 'Röthenbach im Emmental' },
    { code: '3339', name: 'Trub' },
    { code: '3340', name: 'Huttwil' },
    { code: '3342', name: 'Schönbühl' },
    { code: '3343', name: 'Sumiswald' },
    { code: '3344', name: 'Sumiswald' },
    { code: '3345', name: 'Wynigen' },
    { code: '3346', name: 'Wyssachen' },
    { code: '3347', name: 'Dürrenroth' },
    { code: '3348', name: 'Huttwil' },
    { code: '3349', name: 'Eriswil' },
    { code: '3350', name: 'Langenthal' },
    { code: '3351', name: 'Büren' },
    { code: '3352', name: 'Büren' },
    { code: '3353', name: 'Büren' },
    { code: '3354', name: 'Büren' },
    { code: '3355', name: 'Schönbühl' },
    { code: '3356', name: 'Meinisberg' },
    { code: '3357', name: 'Büren an der Aare' },
    { code: '3358', name: 'Rüti bei Lyssach' },
    { code: '3360', name: 'Herzogenbuchsee' },
    { code: '3362', name: 'Niederönz' },
    { code: '3363', name: 'Oberönz' },
    { code: '3364', name: 'Huttwil' },
    { code: '3365', name: 'Huttwil' },
    { code: '3366', name: 'Huttwil' },
    { code: '3367', name: 'Thörigen' },
    { code: '3368', name: 'Bleienbach' },
    { code: '3370', name: 'Inkwil' },
    { code: '3372', name: 'Wiedlisbach' },
    { code: '3373', name: 'Heimenhausen' },
    { code: '3374', name: 'Graben' },
    { code: '3375', name: 'Riedtwil' },
    { code: '3376', name: 'Melchnau' },
    { code: '3377', name: 'Burgdorf' },
    { code: '3378', name: 'Burgdorf' },
    { code: '3380', name: 'Wangelen' },
    { code: '3400', name: 'Burgdorf' },
    { code: '3401', name: 'Burgdorf' },
    { code: '3402', name: 'Burgdorf' },
    { code: '3404', name: 'Burgdorf' },
    { code: '3405', name: 'Oberburg' },
    { code: '3406', name: 'Oberburg' },
    { code: '3407', name: 'Rüegsauschachen' },
    { code: '3408', name: 'Lüderbüel' },
    { code: '3409', name: 'Sumiswald' },
    { code: '3412', name: 'Walkringen' },
    { code: '3413', name: 'Röthenbach im Emmental' },
    { code: '3414', name: 'Oberdiessbach' },
    { code: '3415', name: 'Röthenbach im Emmental' },
    { code: '3416', name: 'Buchholterberg' },
    { code: '3417', name: 'Rüegsau' },
    { code: '3418', name: 'Rüegsau' },
    { code: '3419', name: 'Aeschlen' },
    { code: '3421', name: 'Grosshöchstetten' },
    { code: '3422', name: 'Konolfingen' },
    { code: '3423', name: 'Konolfingen' },
    { code: '3424', name: 'Konolfingen' },
    { code: '3425', name: 'Krauchthal' },
    { code: '3426', name: 'Freimettigen' },
    { code: '3427', name: 'Utzenstorf' },
    { code: '3428', name: 'Wiler bei Utzenstorf' },
    { code: '3429', name: 'Bätterkinden' },
    { code: '3432', name: 'Embrach' }, // ZH
    { code: '3434', name: 'Tägerig' },
    { code: '3435', name: 'Rommerswil' },
    { code: '3436', name: 'Schlosswil' },
    { code: '3437', name: 'Rüeggisberg' },
    { code: '3438', name: 'Burgiwil' },
    { code: '3439', name: 'Riggisberg' },
    { code: '3442', name: 'Hellsau' },
    { code: '3443', name: 'Huttwil' },
    { code: '3444', name: 'Sumiswald' },
    { code: '3445', name: 'Wynigen' },
    { code: '3446', name: 'Sumiswald' },
    { code: '3447', name: 'Oberburg' },
    { code: '3452', name: 'Heimiswil' },
    { code: '3453', name: 'Hasle bei Burgdorf' },
    { code: '3454', name: 'Sumiswald' },
    { code: '3455', name: 'Zollbrück' },
    { code: '3456', name: 'Trachselwald' },
    { code: '3457', name: 'Sumiswald' },
    { code: '3458', name: 'Dürrenroth' },
    { code: '3462', name: 'Weier im Emmental' },
    { code: '3463', name: 'Flüelen' },
    { code: '3464', name: 'Sumiswald' },
    { code: '3465', name: 'Sumiswald' },
    { code: '3466', name: 'Dürrenroth' },
    { code: '3467', name: 'Trub' },
    { code: '3468', name: 'Trubschachen' },
    { code: '3469', name: 'Trub' },
    { code: '3472', name: 'Wynigen' },
    { code: '3473', name: 'Wynigen' },
    { code: '3474', name: 'Oeschenbach' },
    { code: '3475', name: 'Rüderswil' },
    { code: '3476', name: 'Rüderswil' },
    { code: '3483', name: 'Huttwil' },
    { code: '3484', name: 'Huttwil' },
    { code: '3485', name: 'Eriswil' },
    { code: '3486', name: 'Wyssachen' },
    { code: '3492', name: 'Berg bei Rohrbach' },
    { code: '3493', name: 'Kreuzau' },
    { code: '3494', name: 'Amriswil' }, // TG
    { code: '3503', name: 'Brienz' },
    { code: '3504', name: 'Brienzwiler' },
    { code: '3505', name: 'Oberried am Brienzersee' },
    { code: '3506', name: 'Hofstetten bei Brienz' },
    { code: '3507', name: 'Schwanden bei Brienz' },
    { code: '3508', name: 'Fluhli' },
    { code: '3510', name: 'Konolfingen' },
    { code: '3512', name: 'Walkringen' },
    { code: '3513', name: 'Walkringen' },
    { code: '3514', name: 'Walkringen' },
    { code: '3515', name: 'Hasle-Rüegsau' },
    { code: '3516', name: 'Huttwil' },
    { code: '3517', name: 'Huttwil' },
    { code: '3518', name: 'Huttwil' },
    { code: '3519', name: 'Huttwil' },
    { code: '3522', name: 'Röthenbach im Emmental' },
    { code: '3523', name: 'Signau' },
    { code: '3524', name: 'Signau' },
    { code: '3525', name: 'Lauperswil' },
    { code: '3526', name: 'Lauperswil' },
    { code: '3527', name: 'Lauperswil' },
    { code: '3528', name: 'Lauperswil' },
    { code: '3532', name: 'Signau' },
    { code: '3533', name: 'Eggiwil' },
    { code: '3534', name: 'Eggiwil' },
    { code: '3535', name: 'Eggiwil' },
    { code: '3536', name: 'Langnau im Emmental' },
    { code: '3537', name: 'Langnau im Emmental' },
    { code: '3538', name: 'Langnau im Emmental' },
    { code: '3539', name: 'Schangnau' },
    { code: '3542', name: 'Gündlischwand' },
    { code: '3543', name: 'Zweisimmen' },
    { code: '3544', name: 'Linden' },
    { code: '3545', name: 'Guggisberg' },
    { code: '3546', name: 'Guggisberg' },
    { code: '3550', name: 'Langnau im Emmental' },
    { code: '3552', name: 'Huttwil' },
    { code: '3553', name: 'Sumiswald' },
    { code: '3554', name: 'Trub' },
    { code: '3555', name: 'Trubschachen' },
    { code: '3556', name: 'Huttwil' },
    { code: '3557', name: 'Huttwil' },
    { code: '3562', name: 'Burgdorf' },
    { code: '3563', name: 'Burgdorf' },
    { code: '3564', name: 'Burgdorf' },
    { code: '3565', name: 'Burgdorf' },
    { code: '3572', name: 'Ramsei' },
    { code: '3573', name: 'Lützelflüh' },
    { code: '3574', name: 'Lützelflüh' },
    { code: '3575', name: 'Lützelflüh' },
    { code: '3576', name: 'Trubschachen' },
    { code: '3577', name: 'Walterswil SO' },
    { code: '3578', name: 'Achiswil' },
    { code: '3579', name: 'Melchnau' },
    { code: '3582', name: 'Bannwil' },
    { code: '3583', name: 'Ursenbach' },
    { code: '3584', name: 'Ursenbach' },
    { code: '3585', name: 'Melchnau' },
    { code: '3586', name: 'Melchnau' },
    { code: '3587', name: 'Melchnau' },
    { code: '3588', name: 'Obersteckholz' },
    { code: '3589', name: 'Untersteckholz' },
    { code: '3600', name: 'Thun' },
    { code: '3602', name: 'Thun' },
    { code: '3603', name: 'Thun' },
    { code: '3604', name: 'Thun' },
    { code: '3605', name: 'Thun' },
    { code: '3606', name: 'Thun' },
    { code: '3607', name: 'Thun' },
    { code: '3608', name: 'Thun' },
    { code: '3609', name: 'Thun' },
    { code: '3612', name: 'Steffisburg' },
    { code: '3613', name: 'Steffisburg' },
    { code: '3614', name: 'Steffisburg' },
    { code: '3615', name: 'Heimenschwand' },
    { code: '3616', name: 'Schwarzenegg' },
    { code: '3617', name: 'Heimenschwand' },
    { code: '3618', name: 'Eriz' },
    { code: '3619', name: 'Eriz' },
    { code: '3622', name: 'Homberg' },
    { code: '3623', name: 'Teuffenthal' },
    { code: '3624', name: 'Teuffenthal' },
    { code: '3625', name: 'Heimenschwand' },
    { code: '3626', name: 'Buchholterberg' },
    { code: '3627', name: 'Buchholterberg' },
    { code: '3628', name: 'Auswil' },
    { code: '3629', name: 'Auswil' },
    { code: '3632', name: 'Oberhofen am Thunersee' },
    { code: '3633', name: 'Amsoldingen' },
    { code: '3634', name: 'Thierachern' },
    { code: '3635', name: 'Uebeschi' },
    { code: '3636', name: 'Pohlern' },
    { code: '3637', name: 'Sigriswil' },
    { code: '3638', name: 'Blüemlisalp' },
    { code: '3642', name: 'Hilterfingen' },
    { code: '3643', name: 'Jaberg' },
    { code: '3644', name: 'Gwatt' },
    { code: '3645', name: 'Village-Neuf' },
    { code: '3646', name: 'Einigen' },
    { code: '3647', name: 'Einigen' },
    { code: '3648', name: 'Einigen' },
    { code: '3649', name: 'Einigen' },
    { code: '3652', name: 'Krattigen' },
    { code: '3653', name: 'Krattigen' },
    { code: '3654', name: 'Krattigen' },
    { code: '3655', name: 'Sigriswil' },
    { code: '3656', name: 'Sigriswil' },
    { code: '3657', name: 'Sigriswil' },
    { code: '3658', name: 'Merligen' },
    { code: '3661', name: 'Reinach' },
    { code: '3662', name: 'Seftigen' },
    { code: '3663', name: 'Burgistein' },
    { code: '3664', name: 'Burgistein' },
    { code: '3665', name: 'Guggisberg' },
    { code: '3666', name: 'Riggisberg' },
    { code: '3672', name: 'Oberwil im Simmental' },
    { code: '3673', name: 'Oberwil im Simmental' },
    { code: '3674', name: 'Därstetten' },
    { code: '3675', name: 'Därstetten' },
    { code: '3676', name: 'Erlenbach im Simmental' },
    { code: '3677', name: 'Erlenbach im Simmental' },
    { code: '3678', name: 'Boltigen' },
    { code: '3679', name: 'Boltigen' },
    { code: '3682', name: 'Bössingen' },
    { code: '3683', name: 'Bössingen' },
    { code: '3684', name: 'Bürglen' },
    { code: '3685', name: 'Oberrieden' },
    { code: '3686', name: 'Saxeten' },
    { code: '3687', name: 'Saxeten' },
    { code: '3688', name: 'Aeschi bei Spiez' },
    { code: '3689', name: 'Aeschi bei Spiez' },
    { code: '3692', name: 'Oberhofen am Thunersee' },
    { code: '3693', name: 'Oberhofen am Thunersee' },
    { code: '3694', name: 'Leissigen' },
    { code: '3695', name: 'Leissigen' },
    { code: '3696', name: 'Leissigen' },
    { code: '3697', name: 'Leissigen' },
    { code: '3698', name: 'Leissigen' },
    { code: '3699', name: 'Leissigen' },
    { code: '3702', name: 'Wimmis' },
    { code: '3703', name: 'Wimmis' },
    { code: '3704', name: 'Wimmis' },
    { code: '3705', name: 'Wimmis' },
    { code: '3706', name: 'Wimmis' },
    { code: '3707', name: 'Wimmis' },
    { code: '3708', name: 'Wimmis' },
    { code: '3714', name: 'Frutigen' },
    { code: '3715', name: 'Adelboden' },
    { code: '3716', name: 'Adelboden' },
    { code: '3717', name: 'Adelboden' },
    { code: '3718', name: 'Adelboden' },
    { code: '3719', name: 'Adelboden' },
    { code: '3722', name: 'Kandergrund' },
    { code: '3723', name: 'Kandersteg' },
    { code: '3724', name: 'Kandersteg' },
    { code: '3725', name: 'Kandersteg' },
    { code: '3726', name: 'Kandersteg' },
    { code: '3727', name: 'Kandersteg' },
    { code: '3728', name: 'Kandersteg' },
    { code: '3730', name: 'Kandersteg' },
    { code: '3732', name: 'Reichenbach im Kandertal' },
    { code: '3733', name: 'Reichenbach im Kandertal' },
    { code: '3734', name: 'Reichenbach im Kandertal' },
    { code: '3735', name: 'Reichenbach im Kandertal' },
    { code: '3736', name: 'Reichenbach im Kandertal' },
    { code: '3737', name: 'Reichenbach im Kandertal' },
    { code: '3738', name: 'Reichenbach im Kandertal' },
    { code: '3739', name: 'Reichenbach im Kandertal' },
    { code: '3742', name: 'Frutigen' },
    { code: '3743', name: 'Frutigen' },
    { code: '3744', name: 'Frutigen' },
    { code: '3745', name: 'Frutigen' },
    { code: '3746', name: 'Frutigen' },
    { code: '3747', name: 'Frutigen' },
    { code: '3748', name: 'Frutigen' },
    { code: '3752', name: 'Zweisimmen' },
    { code: '3753', name: 'Zweisimmen' },
    { code: '3754', name: 'Zweisimmen' },
    { code: '3755', name: 'Zweisimmen' },
    { code: '3756', name: 'Zweisimmen' },
    { code: '3757', name: 'Zweisimmen' },
    { code: '3758', name: 'Boltigen' },
    { code: '3759', name: 'Boltigen' },
    { code: '3762', name: 'Erlenbach im Simmental' },
    { code: '3763', name: 'Erlenbach im Simmental' },
    { code: '3764', name: 'Erlenbach im Simmental' },
    { code: '3765', name: 'Erlenbach im Simmental' },
    { code: '3766', name: 'Därstetten' },
    { code: '3767', name: 'Därstetten' },
    { code: '3768', name: 'Därstetten' },
    { code: '3769', name: 'Därstetten' },
    { code: '3770', name: 'Zweisimmen' },
    { code: '3772', name: 'Oberwil im Simmental' },
    { code: '3773', name: 'Oberwil im Simmental' },
    { code: '3774', name: 'Oberwil im Simmental' },
    { code: '3775', name: 'Oberwil im Simmental' },
    { code: '3776', name: 'Boltigen' },
    { code: '3777', name: 'Boltigen' },
    { code: '3778', name: 'Boltigen' },
    { code: '3779', name: 'Boltigen' },
    { code: '3780', name: 'Gstaad' },
    { code: '3782', name: 'Gstaad' },
    { code: '3783', name: 'Gstaad' },
    { code: '3784', name: 'Gstaad' },
    { code: '3785', name: 'Gstaad' },
    { code: '3786', name: 'Gstaad' },
    { code: '3787', name: 'Gstaad' },
    { code: '3788', name: 'Gstaad' },
    { code: '3789', name: 'Gstaad' },
    { code: '3792', name: 'Saanen' },
    { code: '3793', name: 'Saanen' },
    { code: '3794', name: 'Saanen' },
    { code: '3795', name: 'Saanen' },
    { code: '3796', name: 'Saanen' },
    { code: '3797', name: 'Saanen' },
    { code: '3798', name: 'Saanen' },
    { code: '3799', name: 'Saanen' },
    { code: '3800', name: 'Interlaken' },
    { code: '3803', name: 'Matten bei Interlaken' },
    { code: '3804', name: 'Habkern' },
    { code: '3805', name: 'Goldswil' },
    { code: '3806', name: 'Bönigen' },
    { code: '3807', name: 'Iseltwald' },
    { code: '3808', name: 'Iseltwald' },
    { code: '3812', name: 'Grindelwald' },
    { code: '3813', name: 'Grindelwald' },
    { code: '3814', name: 'Grindelwald' },
    { code: '3815', name: 'Grindelwald' },
    { code: '3816', name: 'Grindelwald' },
    { code: '3818', name: 'Grindelwald' },
    { code: '3819', name: 'Grindelwald' },
    { code: '3822', name: 'Lauterbrunnen' },
    { code: '3823', name: 'Lauterbrunnen' },
    { code: '3824', name: 'Lauterbrunnen' },
    { code: '3825', name: 'Lauterbrunnen' },
    { code: '3826', name: 'Wengen' },
    { code: '3827', name: 'Mürren' },
    { code: '3828', name: 'Mürren' },
    { code: '3829', name: 'Mürren' },
    { code: '3832', name: 'Brienz' },
    { code: '3833', name: 'Brienz' },
    { code: '3834', name: 'Brienz' },
    { code: '3835', name: 'Brienz' },
    { code: '3836', name: 'Brienz' },
    { code: '3837', name: 'Brienz' },
    { code: '3838', name: 'Brienz' },
    { code: '3839', name: 'Brienz' },
    { code: '3842', name: 'Meiringen' },
    { code: '3843', name: 'Meiringen' },
    { code: '3844', name: 'Meiringen' },
    { code: '3845', name: 'Meiringen' },
    { code: '3846', name: 'Meiringen' },
    { code: '3847', name: 'Hasliberg' },
    { code: '3848', name: 'Hasliberg' },
    { code: '3849', name: 'Hasliberg' },
    { code: '3852', name: 'Ringgenberg' },
    { code: '3853', name: 'Ringgenberg' },
    { code: '3854', name: 'Ringgenberg' },
    { code: '3855', name: 'Ringgenberg' },
    { code: '3856', name: 'Ringgenberg' },
    { code: '3857', name: 'Brienzwiler' },
    { code: '3858', name: 'Brienzwiler' },
    { code: '3859', name: 'Brienzwiler' },
    { code: '3862', name: 'Brienz' },
    { code: '3863', name: 'Brienz' },
    { code: '3864', name: 'Brienz' },
    { code: '3865', name: 'Brienz' },
    { code: '3866', name: 'Brienz' },
    { code: '3867', name: 'Brienz' },
    { code: '3868', name: 'Brienz' },
    { code: '3869', name: 'Brienz' },
    { code: '3872', name: 'Brienz' },
    { code: '3873', name: 'Brienz' },
    { code: '3874', name: 'Brienz' },
    { code: '3875', name: 'Brienz' },
    { code: '3876', name: 'Brienz' },
    { code: '3877', name: 'Brienz' },
    { code: '3878', name: 'Brienz' },
    { code: '3879', name: 'Brienz' },
    { code: '3882', name: 'Brienz' },
    { code: '3883', name: 'Brienz' },
    { code: '3884', name: 'Brienz' },
    { code: '3885', name: 'Brienz' },
    { code: '3886', name: 'Brienz' },
    { code: '3887', name: 'Brienz' },
    { code: '3888', name: 'Brienz' },
    { code: '3889', name: 'Brienz' },
    { code: '3892', name: 'Brienz' },
    { code: '3893', name: 'Brienz' },
    { code: '3894', name: 'Brienz' },
    { code: '3895', name: 'Brienz' },
    { code: '3896', name: 'Brienz' },
    { code: '3897', name: 'Brienz' },
    { code: '3898', name: 'Brienz' },
    { code: '3899', name: 'Brienz' },
    { code: '3900', name: 'Brig-Glis' }, // VS
    { code: '3902', name: 'Brig-Glis' },
    { code: '3903', name: 'Brig-Glis' },
    { code: '3904', name: 'Naters' },
    { code: '3905', name: 'Saas-Almagell' },
    { code: '3906', name: 'Saas-Fee' },
    { code: '3907', name: 'Saas-Grund' },
    { code: '3908', name: 'Saas-Balen' },
    { code: '3911', name: 'Ried-Brig' },
    { code: '3912', name: 'Blitzingen' },
    { code: '3913', name: 'Bellwald' },
    { code: '3914', name: 'Fiesch' },
    { code: '3915', name: 'Fieschertal' },
    { code: '3916', name: 'Ernen' },
    { code: '3917', name: 'Mühlebach' },
    { code: '3918', name: 'Lax' },
    { code: '3919', name: 'Grengiols' },
    { code: '3920', name: 'Zermatt' },
    { code: '3921', name: 'Zermatt' },
    { code: '3922', name: 'Zermatt' },
    { code: '3923', name: 'Zermatt' },
    { code: '3924', name: 'Zermatt' },
    { code: '3925', name: 'Zermatt' },
    { code: '3926', name: 'Zermatt' },
    { code: '3927', name: 'Zermatt' },
    { code: '3928', name: 'Zermatt' },
    { code: '3929', name: 'Täsch' },
    { code: '3930', name: 'Visp' },
    { code: '3931', name: 'Visp' },
    { code: '3932', name: 'Visp' },
    { code: '3933', name: 'Eyholz' },
    { code: '3934', name: 'Zeneggen' },
    { code: '3935', name: 'Bürchen' },
    { code: '3936', name: 'Unterbäch' },
    { code: '3937', name: 'Baltschieder' },
    { code: '3938', name: 'Raron' },
    { code: '3939', name: 'Raron' },
    { code: '3942', name: 'Raron' },
    { code: '3943', name: 'Raron' },
    { code: '3944', name: 'Unterbäch' },
    { code: '3945', name: 'Gampel' },
    { code: '3946', name: 'Steg-Hohtenn' },
    { code: '3947', name: 'Gampel' },
    { code: '3948', name: 'Wiler' },
    { code: '3949', name: 'Wiler' },
    { code: '3952', name: 'Susten' },
    { code: '3953', name: 'Inden' },
    { code: '3954', name: 'Leuk' },
    { code: '3955', name: 'Leukerbad' },
    { code: '3956', name: 'Leukerbad' },
    { code: '3957', name: 'Leukerbad' },
    { code: '3958', name: 'Leukerbad' },
    { code: '3959', name: 'Leukerbad' },
    { code: '3962', name: 'Leuk' },
    { code: '3963', name: 'Leuk' },
    { code: '3964', name: 'Leuk' },
    { code: '3965', name: 'Leuk' },
    { code: '3966', name: 'Leuk' },
    { code: '3967', name: 'Leuk' },
    { code: '3968', name: 'Leuk' },
    { code: '3969', name: 'Leuk' },
    { code: '3972', name: 'Leuk' },
    { code: '3973', name: 'Leuk' },
    { code: '3974', name: 'Leuk' },
    { code: '3975', name: 'Leuk' },
    { code: '3976', name: 'Leuk' },
    { code: '3977', name: 'Leuk' },
    { code: '3978', name: 'Leuk' },
    { code: '3979', name: 'Leuk' },
    { code: '3982', name: 'Leuk' },
    { code: '3983', name: 'Leuk' },
    { code: '3984', name: 'Leuk' },
    { code: '3985', name: 'Leuk' },
    { code: '3986', name: 'Leuk' },
    { code: '3987', name: 'Leuk' },
    { code: '3988', name: 'Leuk' },
    { code: '3989', name: 'Leuk' },
    { code: '3992', name: 'Leuk' },
    { code: '3993', name: 'Leuk' },
    { code: '3994', name: 'Leuk' },
    { code: '3995', name: 'Leuk' },
    { code: '3996', name: 'Leuk' },
    { code: '3997', name: 'Leuk' },
    { code: '3998', name: 'Leuk' },
    { code: '3999', name: 'Leuk' },
  ],
  
  // ST. GALLEN (SG)
  'SG': [
    { code: '9000', name: 'St. Gallen' },
    { code: '9001', name: 'St. Gallen Bahnhof' },
    { code: '9004', name: 'St. Gallen St. Georgen' },
    { code: '9007', name: 'St. Gallen St. Fiden' },
    { code: '9008', name: 'St. Gallen Winkeln' },
    { code: '9010', name: 'St. Gallen' },
    { code: '9011', name: 'St. Gallen' },
    { code: '9012', name: 'St. Gallen' },
    { code: '9013', name: 'St. Gallen' },
    { code: '9014', name: 'St. Gallen' },
    { code: '9015', name: 'St. Gallen' },
    { code: '9016', name: 'St. Gallen' },
    { code: '9020', name: 'Appenzell' },
    { code: '9022', name: 'Appenzell' },
    { code: '9023', name: 'Appenzell' },
    { code: '9024', name: 'Appenzell' },
    { code: '9025', name: 'Appenzell' },
    { code: '9026', name: 'Appenzell' },
    { code: '9027', name: 'Appenzell' },
    { code: '9028', name: 'Appenzell' },
    { code: '9029', name: 'Appenzell' },
    { code: '9030', name: 'Abtwil SG' },
    { code: '9031', name: 'Wittenbach' },
    { code: '9032', name: 'Engelburg' },
    { code: '9033', name: 'Untereggen' },
    { code: '9034', name: 'Eggersriet' },
    { code: '9035', name: 'Grub AR' },
    { code: '9036', name: 'Wald AR' },
    { code: '9037', name: 'Speicher' },
    { code: '9038', name: 'Trogen' },
    { code: '9042', name: 'Speicher' },
    { code: '9043', name: 'Trogen' },
    { code: '9044', name: 'Teufen AR' },
    { code: '9045', name: 'Bühler' },
    { code: '9046', name: 'Gonten' },
    { code: '9047', name: 'Urnäsch' },
    { code: '9048', name: 'Schönengrund' },
    { code: '9049', name: 'Hundwil' },
    { code: '9050', name: 'Appenzell' },
    { code: '9052', name: 'Appenzell' },
    { code: '9053', name: 'Appenzell' },
    { code: '9054', name: 'Appenzell' },
    { code: '9055', name: 'Appenzell' },
    { code: '9056', name: 'Appenzell' },
    { code: '9057', name: 'Appenzell' },
    { code: '9058', name: 'Appenzell' },
    { code: '9059', name: 'Appenzell' },
    { code: '9062', name: 'Appenzell' },
    { code: '9063', name: 'Appenzell' },
    { code: '9064', name: 'Appenzell' },
    { code: '9065', name: 'Appenzell' },
    { code: '9066', name: 'Appenzell' },
    { code: '9067', name: 'Appenzell' },
    { code: '9068', name: 'Appenzell' },
    { code: '9069', name: 'Appenzell' },
    { code: '9100', name: 'Herisau' },
    { code: '9102', name: 'Herisau' },
    { code: '9103', name: 'Urnäsch' },
    { code: '9104', name: 'Waldstatt' },
    { code: '9105', name: 'Schwellbrunn' },
    { code: '9106', name: 'Degersheim' },
    { code: '9107', name: 'Ursenbach' },
    { code: '9108', name: 'Gonten' },
    { code: '9112', name: 'Hundwil' },
    { code: '9113', name: 'Waldstatt' },
    { code: '9114', name: 'Hundwil' },
    { code: '9115', name: 'Dorf' },
    { code: '9116', name: 'Waldstatt' },
    { code: '9117', name: 'Lutzenberg' },
    { code: '9118', name: 'Heiden' },
    { code: '9119', name: 'Heiden' },
    { code: '9122', name: 'Heiden' },
    { code: '9123', name: 'Heiden' },
    { code: '9124', name: 'Heiden' },
    { code: '9125', name: 'Brunnen' },
    { code: '9126', name: 'Brunnen' },
    { code: '9127', name: 'St. Margrethen' },
    { code: '9128', name: 'Wolfhalden' },
    { code: '9130', name: 'Lutzenberg' },
    { code: '9132', name: 'Rehetobel' },
    { code: '9133', name: 'Heiden' },
    { code: '9134', name: 'Heiden' },
    { code: '9135', name: 'Heiden' },
    { code: '9136', name: 'Heiden' },
    { code: '9137', name: 'Heiden' },
    { code: '9138', name: 'Heiden' },
    { code: '9139', name: 'Heiden' },
    { code: '9400', name: 'Rorschach' },
    { code: '9402', name: 'Mörschwil' },
    { code: '9403', name: 'Wittenbach' },
    { code: '9404', name: 'Untereggen' },
    { code: '9405', name: 'Rorschacherberg' },
    { code: '9406', name: 'Goldach' },
    { code: '9408', name: 'Rorschacherberg' },
    { code: '9410', name: 'Heiden' },
    { code: '9411', name: 'Heiden' },
    { code: '9412', name: 'Heiden' },
    { code: '9413', name: 'Heiden' },
    { code: '9414', name: 'Heiden' },
    { code: '9415', name: 'Heiden' },
    { code: '9416', name: 'Heiden' },
    { code: '9417', name: 'Heiden' },
    { code: '9418', name: 'Heiden' },
    { code: '9419', name: 'Heiden' },
    { code: '9422', name: 'Staad' },
    { code: '9423', name: 'Altenrhein' },
    { code: '9424', name: 'Rheineck' },
    { code: '9425', name: 'Thal' },
    { code: '9426', name: 'Lutzenberg' },
    { code: '9427', name: 'Wolfhalden' },
    { code: '9428', name: 'Walzenhausen' },
    { code: '9429', name: 'Walzenhausen' },
    { code: '9430', name: 'St. Margrethen' },
    { code: '9431', name: 'Au SG' },
    { code: '9432', name: 'Au SG' },
    { code: '9433', name: 'Au SG' },
    { code: '9434', name: 'Au SG' },
    { code: '9435', name: 'Heerbrugg' },
    { code: '9436', name: 'Bal gach' },
    { code: '9437', name: 'Marbach' },
    { code: '9438', name: 'Oberegg' },
    { code: '9442', name: 'Buchs SG' },
    { code: '9443', name: 'Buchs SG' },
    { code: '9444', name: 'Buchs SG' },
    { code: '9445', name: 'Buchs SG' },
    { code: '9446', name: 'Buchs SG' },
    { code: '9447', name: 'Buchs SG' },
    { code: '9448', name: 'Buchs SG' },
    { code: '9449', name: 'Buchs SG' },
    { code: '9450', name: 'Altstätten' },
    { code: '9451', name: 'Altstätten' },
    { code: '9452', name: 'Altstätten' },
    { code: '9453', name: 'Altstätten' },
    { code: '9454', name: 'Altstätten' },
    { code: '9455', name: 'Altstätten' },
    { code: '9456', name: 'Altstätten' },
    { code: '9457', name: 'Altstätten' },
    { code: '9458', name: 'Altstätten' },
    { code: '9459', name: 'Altstätten' },
    { code: '9462', name: 'Montlingen' },
    { code: '9463', name: 'Oberriet' },
    { code: '9464', name: 'Oberriet' },
    { code: '9465', name: 'Oberriet' },
    { code: '9466', name: 'Oberriet' },
    { code: '9467', name: 'Oberriet' },
    { code: '9468', name: 'Oberriet' },
    { code: '9469', name: 'Oberriet' },
    { code: '9470', name: 'Buchs SG' },
    { code: '9471', name: 'Buchs SG' },
    { code: '9472', name: 'Buchs SG' },
    { code: '9473', name: 'Buchs SG' },
    { code: '9474', name: 'Buchs SG' },
    { code: '9475', name: 'Sevelen' },
    { code: '9476', name: 'Sevelen' },
    { code: '9477', name: 'Sevelen' },
    { code: '9478', name: 'Sevelen' },
    { code: '9479', name: 'Sevelen' },
    { code: '9485', name: 'Nendeln' }, // FL
    { code: '9486', name: 'Nendeln' }, // FL
    { code: '9487', name: 'Bendern' }, // FL
    { code: '9488', name: 'Bendern' }, // FL
    { code: '9489', name: 'Bendern' }, // FL
    { code: '9490', name: 'Vaduz' }, // FL
    { code: '9491', name: 'Ruggell' }, // FL
    { code: '9492', name: 'Eschen' }, // FL
    { code: '9493', name: 'Mauren' }, // FL
    { code: '9494', name: 'Schaan' }, // FL
    { code: '9495', name: 'Triesen' }, // FL
    { code: '9496', name: 'Balzers' }, // FL
    { code: '9497', name: 'Triesenberg' }, // FL
    { code: '9498', name: 'Planken' }, // FL
    { code: '9499', name: 'Schaanwald' }, // FL
    { code: '9500', name: 'Wil SG' },
    { code: '9502', name: 'Wil SG' },
    { code: '9503', name: 'Wil SG' },
    { code: '9504', name: 'Wil SG' },
    { code: '9505', name: 'Wil SG' },
    { code: '9506', name: 'Lommiswil' },
    { code: '9512', name: 'Rossrüti' },
    { code: '9513', name: 'Wil SG' },
    { code: '9514', name: 'Wil SG' },
    { code: '9515', name: 'Holderswil' },
    { code: '9517', name: 'Bazenheid' },
    { code: '9518', name: 'Bazenheid' },
    { code: '9519', name: 'Bazenheid' },
    { code: '9523', name: 'Züberwangen' },
    { code: '9524', name: 'Zuzwil SG' },
    { code: '9525', name: 'Lenggenwil' },
    { code: '9526', name: 'Oberbüren' },
    { code: '9527', name: 'Niederbüren' },
    { code: '9532', name: 'Bronschhofen' },
    { code: '9533', name: 'Bronschhofen' },
    { code: '9534', name: 'Bronschhofen' },
    { code: '9535', name: 'Wil SG' },
    { code: '9536', name: 'Schwarzenbach' },
    { code: '9542', name: 'Münchwilen TG' },
    { code: '9543', name: 'St. Margrethen' },
    { code: '9544', name: 'Wängi' },
    { code: '9545', name: 'Wängi' },
    { code: '9546', name: 'Wängi' },
    { code: '9547', name: 'Wängi' },
    { code: '9548', name: 'Wängi' },
    { code: '9549', name: 'Wängi' },
    { code: '9552', name: 'Bronschhofen' },
    { code: '9553', name: 'Bettwiesen' },
    { code: '9554', name: 'Münchwilen TG' },
    { code: '9555', name: 'Tobel' },
    { code: '9556', name: 'Affeltrangen' },
    { code: '9562', name: 'Märwil' },
    { code: '9563', name: 'Märwil' },
    { code: '9564', name: 'Märwil' },
    { code: '9565', name: 'Märwil' },
    { code: '9566', name: 'Märwil' },
    { code: '9567', name: 'Märwil' },
    { code: '9568', name: 'Märwil' },
    { code: '9569', name: 'Märwil' },
    { code: '9602', name: 'Buchbach' },
    { code: '9604', name: 'Lütisburg' },
    { code: '9605', name: 'Lütisburg' },
    { code: '9606', name: 'Lütisburg' },
    { code: '9607', name: 'Lütisburg' },
    { code: '9608', name: 'Oberhelfenschwil' },
    { code: '9612', name: 'Mogelsberg' },
    { code: '9613', name: 'Mogelsberg' },
    { code: '9614', name: 'Mogelsberg' },
    { code: '9615', name: 'Ebersol' },
    { code: '9616', name: 'Kirchberg SG' },
    { code: '9620', name: 'Lichtensteig' },
    { code: '9621', name: 'Oberhelfenschwil' },
    { code: '9622', name: 'Ebersol' },
    { code: '9623', name: 'Roggwil TG' },
    { code: '9624', name: 'Roggwil TG' },
    { code: '9625', name: 'Roggwil TG' },
    { code: '9626', name: 'Roggwil TG' },
    { code: '9627', name: 'Roggwil TG' },
    { code: '9628', name: 'Roggwil TG' },
    { code: '9629', name: 'Roggwil TG' },
    { code: '9630', name: 'Wattwil' },
    { code: '9631', name: 'Wattwil' },
    { code: '9632', name: 'Wattwil' },
    { code: '9633', name: 'Wattwil' },
    { code: '9634', name: 'Wattwil' },
    { code: '9635', name: 'Wattwil' },
    { code: '9636', name: 'Wattwil' },
    { code: '9637', name: 'Wattwil' },
    { code: '9642', name: 'Ebnat-Kappel' },
    { code: '9643', name: 'Ebnat-Kappel' },
    { code: '9644', name: 'Ebnat-Kappel' },
    { code: '9645', name: 'Ebnat-Kappel' },
    { code: '9650', name: 'Wildhaus' },
    { code: '9651', name: 'Wildhaus' },
    { code: '9652', name: 'Wildhaus' },
    { code: '9653', name: 'Wildhaus' },
    { code: '9654', name: 'Wildhaus' },
    { code: '9655', name: 'Wildhaus' },
    { code: '9656', name: 'Wildhaus' },
    { code: '9657', name: 'Unterwasser' },
    { code: '9658', name: 'Alt St. Johann' },
    { code: '9659', name: 'Starkenbach' },
    { code: '9700', name: 'Buchs SG' },
    { code: '9702', name: 'Buchs SG' },
    { code: '9703', name: 'Buchs SG' },
    { code: '9704', name: 'Buchs SG' },
    { code: '9705', name: 'Buchs SG' },
    { code: '9706', name: 'Buchs SG' },
    { code: '9707', name: 'Buchs SG' },
    { code: '9708', name: 'Buchs SG' },
    { code: '9710', name: 'Grabs' },
    { code: '9711', name: 'Grabs' },
    { code: '9712', name: 'Grabs' },
    { code: '9713', name: 'Grabs' },
    { code: '9714', name: 'Grabs' },
    { code: '9715', name: 'Grabs' },
    { code: '9716', name: 'Grabs' },
    { code: '9717', name: 'Grabs' },
    { code: '9722', name: 'Sennwald' },
    { code: '9723', name: 'Sennwald' },
    { code: '9724', name: 'Sennwald' },
    { code: '9725', name: 'Sennwald' },
    { code: '9726', name: 'Salez' },
    { code: '9727', name: 'Salez' },
    { code: '9728', name: 'Salez' },
    { code: '9729', name: 'Salez' },
  ],
  
  // AARGAU (AG)
  'AG': [
    { code: '5000', name: 'Aarau' },
    { code: '5001', name: 'Aarau' },
    { code: '5002', name: 'Aarau' },
    { code: '5003', name: 'Aarau' },
    { code: '5004', name: 'Aarau' },
    { code: '5012', name: 'Wöschnau' },
    { code: '5013', name: 'Biberstein' },
    { code: '5014', name: 'Küttigen' },
    { code: '5015', name: 'Erlinsbach AG' },
    { code: '5016', name: 'Oberentfelden' },
    { code: '5017', name: 'Unterentfelden' },
    { code: '5018', name: 'Erlinsbach AG' },
    { code: '5022', name: 'Rombach' },
    { code: '5023', name: 'Biberstein' },
    { code: '5024', name: 'Küttigen' },
    { code: '5025', name: 'Asp' },
    { code: '5026', name: 'Densbüren' },
    { code: '5027', name: 'Herznach' },
    { code: '5028', name: 'Ueken' },
    { code: '5032', name: 'Aarau Rohr' },
    { code: '5033', name: 'Buchs AG' },
    { code: '5034', name: 'Suhr' },
    { code: '5035', name: 'Unterentfelden' },
    { code: '5036', name: 'Oberentfelden' },
    { code: '5037', name: 'Muhen' },
    { code: '5038', name: 'Schöftland' },
    { code: '5039', name: 'Schöftland' },
    { code: '5040', name: 'Schöftland' },
    { code: '5042', name: 'Hirschthal' },
    { code: '5043', name: 'Holziken' },
    { code: '5044', name: 'Schlossrued' },
    { code: '5045', name: 'Schmiedrued' },
    { code: '5046', name: 'Staffelbach' },
    { code: '5048', name: 'Kirchleerau' },
    { code: '5049', name: 'Moosleerau' },
    { code: '5050', name: 'Reinach AG' },
    { code: '5052', name: 'Reinach AG' },
    { code: '5053', name: 'Reinach AG' },
    { code: '5054', name: 'Reinach AG' },
    { code: '5055', name: 'Unterkulm' },
    { code: '5056', name: 'Kulm AG' },
    { code: '5057', name: 'Unterkulm' },
    { code: '5058', name: 'Wynental' },
    { code: '5059', name: 'Wynental' },
    { code: '5062', name: 'Wynental' },
    { code: '5063', name: 'Wynental' },
    { code: '5064', name: 'Wynental' },
    { code: '5065', name: 'Wynental' },
    { code: '5066', name: 'Wynental' },
    { code: '5067', name: 'Wynental' },
    { code: '5068', name: 'Wynental' },
    { code: '5069', name: 'Wynental' },
    { code: '5070', name: 'Frick' },
    { code: '5071', name: 'Schupfart' },
    { code: '5072', name: 'Oeschgen' },
    { code: '5073', name: 'Gipf-Oberfrick' },
    { code: '5074', name: 'Wittnau' },
    { code: '5075', name: 'Hersberg' },
    { code: '5076', name: 'Wegenstetten' },
    { code: '5077', name: 'Effingen' },
    { code: '5078', name: 'Bözen' },
    { code: '5079', name: 'Zeihen' },
    { code: '5080', name: 'Laufenburg' },
    { code: '5082', name: 'Kaisten' },
    { code: '5083', name: 'Murg' },
    { code: '5084', name: 'Mellikon' },
    { code: '5085', name: 'Sulz AG' },
    { code: '5086', name: 'Magenwil' },
    { code: '5087', name: 'Biberstein' },
    { code: '5088', name: 'Bööten' },
    { code: '5092', name: 'Maden' },
    { code: '5093', name: 'Etzgen' },
    { code: '5094', name: 'Hellikon' },
    { code: '5095', name: 'Möhlin' },
    { code: '5096', name: 'Maisprach' },
    { code: '5102', name: 'Obersiggenthal' },
    { code: '5103', name: 'Würenlingen' },
    { code: '5104', name: 'Rümikon' },
    { code: '5105', name: 'Achenberg' },
    { code: '5106', name: 'Leibstadt' },
    { code: '5107', name: 'Leibstadt' },
    { code: '5108', name: 'Oberleibstadt' },
    { code: '5112', name: 'Thalheim AG' },
    { code: '5113', name: 'Holderbank' },
    { code: '5114', name: 'Habsburg' },
    { code: '5115', name: 'Hausen AG' },
    { code: '5116', name: 'Schinznach-Bad' },
    { code: '5117', name: 'Schinznach-Dorf' },
    { code: '5118', name: 'Oberflachs' },
    { code: '5119', name: 'Veltheim' },
    { code: '5122', name: 'Wegenstetten' },
    { code: '5123', name: 'Hellikon' },
    { code: '5124', name: 'Buus' },
    { code: '5125', name: 'Maisprach' },
    { code: '5126', name: 'Magden' },
    { code: '5127', name: 'Möhlin' },
    { code: '5128', name: 'Möhlin' },
    { code: '5132', name: 'Rheinfelden' },
    { code: '5133', name: 'Rheinfelden' },
    { code: '5134', name: 'Rheinfelden' },
    { code: '5135', name: 'Rheinfelden' },
    { code: '5136', name: 'Rheinfelden' },
    { code: '5142', name: 'Möhlin' },
    { code: '5143', name: 'Hellikon' },
    { code: '5144', name: 'Olsberg' },
    { code: '5145', name: 'Wittinsburg' },
    { code: '5146', name: 'Wittinsburg' },
    { code: '5147', name: 'Wittinsburg' },
    { code: '5148', name: 'Wittinsburg' },
    { code: '5150', name: 'Kaiseraugst' },
    { code: '5152', name: 'Augst' },
    { code: '5153', name: 'Augst' },
    { code: '5154', name: 'Füllinsdorf' },
    { code: '5155', name: 'Niederdorf' },
    { code: '5156', name: 'Oberdorf BL' },
    { code: '5157', name: 'Anwil' },
    { code: '5158', name: 'Diegten' },
    { code: '5162', name: 'Gelterkinden' },
    { code: '5163', name: 'Buus' },
    { code: '5164', name: 'Hemmiken' },
    { code: '5165', name: 'Ormalingen' },
    { code: '5166', name: 'Maisprach' },
    { code: '5167', name: 'Wenslingen' },
    { code: '5168', name: 'Nusshof' },
    { code: '5170', name: 'Fricktal' },
    { code: '5172', name: 'Fricktal' },
    { code: '5173', name: 'Fricktal' },
    { code: '5174', name: 'Fricktal' },
    { code: '5175', name: 'Fricktal' },
    { code: '5176', name: 'Fricktal' },
    { code: '5177', name: 'Fricktal' },
    { code: '5178', name: 'Fricktal' },
    { code: '5180', name: 'Brugg' },
    { code: '5182', name: 'Döttingen' },
    { code: '5183', name: 'Böttstein' },
    { code: '5184', name: 'Böttstein' },
    { code: '5185', name: 'Böttstein' },
    { code: '5186', name: 'Böttstein' },
    { code: '5192', name: 'Hottwil' },
    { code: '5193', name: 'Mandach' },
    { code: '5194', name: 'Villigen' },
    { code: '5195', name: 'Villigen' },
    { code: '5196', name: 'Würenlingen' },
    { code: '5200', name: 'Brugg' },
    { code: '5201', name: 'Brugg' },
    { code: '5202', name: 'Brugg' },
    { code: '5203', name: 'Brugg' },
    { code: '5204', name: 'Brugg' },
    { code: '5205', name: 'Brugg' },
    { code: '5206', name: 'Brugg' },
    { code: '5207', name: 'Brugg' },
    { code: '5208', name: 'Brugg' },
    { code: '5210', name: 'Windisch' },
    { code: '5211', name: 'Windisch' },
    { code: '5212', name: 'Hausen AG' },
    { code: '5213', name: 'Villmergen' },
    { code: '5214', name: 'Villmergen' },
    { code: '5215', name: 'Villmergen' },
    { code: '5216', name: 'Hägglingen' },
    { code: '5217', name: 'Hägglingen' },
    { code: '5222', name: 'Umiken' },
    { code: '5223', name: 'Riniken' },
    { code: '5224', name: 'Riniken' },
    { code: '5225', name: 'Riniken' },
    { code: '5226', name: 'Riniken' },
    { code: '5232', name: 'Riniken' },
    { code: '5233', name: 'Riniken' },
    { code: '5234', name: 'Riniken' },
    { code: '5235', name: 'Riniken' },
    { code: '5236', name: 'Riniken' },
    { code: '5237', name: 'Riniken' },
    { code: '5240', name: 'Seon' },
    { code: '5242', name: 'Birrwil' },
    { code: '5243', name: 'Menziken' },
    { code: '5244', name: 'Pfeffikon' },
    { code: '5245', name: 'Hitzkirch' }, // LU
    { code: '5246', name: 'Ermenswil' },
    { code: '5250', name: 'Seon' },
    { code: '5252', name: 'Boswil' },
    { code: '5253', name: 'Boswil' },
    { code: '5254', name: 'Böbikon' },
    { code: '5255', name: 'Böbikon' },
    { code: '5256', name: 'Böbikon' },
    { code: '5257', name: 'Böbikon' },
    { code: '5258', name: 'Böbikon' },
    { code: '5260', name: 'Muri AG' },
    { code: '5261', name: 'Muri AG' },
    { code: '5262', name: 'Geltwil' },
    { code: '5263', name: 'Beinwil (Freiamt)' },
    { code: '5264', name: 'Beinwil (Freiamt)' },
    { code: '5265', name: 'Beinwil (Freiamt)' },
    { code: '5266', name: 'Beinwil (Freiamt)' },
    { code: '5267', name: 'Beinwil (Freiamt)' },
    { code: '5268', name: 'Beinwil (Freiamt)' },
    { code: '5270', name: 'Muri AG' },
    { code: '5272', name: 'Geltwil' },
    { code: '5273', name: 'Büron' }, // LU
    { code: '5274', name: 'Buttwil' },
    { code: '5275', name: 'Boswil' },
    { code: '5276', name: 'Böbikon' },
    { code: '5300', name: 'Turgi' },
    { code: '5302', name: 'Turgi' },
    { code: '5303', name: 'Turgi' },
    { code: '5304', name: 'Turgi' },
    { code: '5305', name: 'Turgi' },
    { code: '5306', name: 'Turgi' },
    { code: '5307', name: 'Turgi' },
    { code: '5308', name: 'Turgi' },
    { code: '5309', name: 'Turgi' },
    { code: '5312', name: 'Döttingen' },
    { code: '5313', name: 'Klingnau' },
    { code: '5314', name: 'Klingnau' },
    { code: '5315', name: 'Böttstein' },
    { code: '5316', name: 'Böttstein' },
    { code: '5317', name: 'Böttstein' },
    { code: '5320', name: 'Baden' },
    { code: '5322', name: 'Baden' },
    { code: '5323', name: 'Baden' },
    { code: '5324', name: 'Baden' },
    { code: '5325', name: 'Baden' },
    { code: '5326', name: 'Baden' },
    { code: '5327', name: 'Baden' },
    { code: '5328', name: 'Baden' },
    { code: '5329', name: 'Baden' },
    { code: '5330', name: 'Baden' },
    { code: '5332', name: 'Untersiggenthal' },
    { code: '5333', name: 'Untersiggenthal' },
    { code: '5334', name: 'Untersiggenthal' },
    { code: '5335', name: 'Untersiggenthal' },
    { code: '5336', name: 'Untersiggenthal' },
    { code: '5337', name: 'Obersiggenthal' },
    { code: '5338', name: 'Obersiggenthal' },
    { code: '5340', name: 'Menziken' },
    { code: '5342', name: 'Menziken' },
    { code: '5343', name: 'Menziken' },
    { code: '5344', name: 'Menziken' },
    { code: '5345', name: 'Menziken' },
    { code: '5346', name: 'Menziken' },
    { code: '5350', name: 'Rudolfstetten-Friedlisberg' },
    { code: '5352', name: 'Rudolfstetten-Friedlisberg' },
    { code: '5353', name: 'Bremgarten' },
    { code: '5354', name: 'Bremgarten' },
    { code: '5355', name: 'Bremgarten' },
    { code: '5356', name: 'Dottikon' },
    { code: '5357', name: 'Hägglingen' },
    { code: '5358', name: 'Hägglingen' },
    { code: '5359', name: 'Wohlenschwil' },
    { code: '5362', name: 'Dottikon' },
    { code: '5363', name: 'Dottikon' },
    { code: '5364', name: 'Dottikon' },
    { code: '5365', name: 'Dottikon' },
    { code: '5366', name: 'Dottikon' },
    { code: '5367', name: 'Dottikon' },
    { code: '5400', name: 'Baden' },
    { code: '5402', name: 'Baden' },
    { code: '5403', name: 'Baden' },
    { code: '5404', name: 'Baden' },
    { code: '5405', name: 'Baden' },
    { code: '5406', name: 'Baden' },
    { code: '5407', name: 'Baden' },
    { code: '5408', name: 'Baden' },
    { code: '5409', name: 'Baden' },
    { code: '5412', name: 'Gebenstorf' },
    { code: '5413', name: 'Birmenstorf' },
    { code: '5414', name: 'Birmenstorf' },
    { code: '5415', name: 'Birmenstorf' },
    { code: '5416', name: 'Birmenstorf' },
    { code: '5417', name: 'Birmenstorf' },
    { code: '5420', name: 'Ehrendingen' },
    { code: '5422', name: 'Oberendingen' },
    { code: '5423', name: 'Unterendingen' },
    { code: '5424', name: 'Unterschächen' },
    { code: '5425', name: 'Schneisingen' },
    { code: '5426', name: 'Lengnau AG' },
    { code: '5427', name: 'Freienwil' },
    { code: '5428', name: 'Unterschächen' },
    { code: '5430', name: 'Wettingen' },
    { code: '5431', name: 'Wettingen' },
    { code: '5432', name: 'Wettingen' },
    { code: '5433', name: 'Wettingen' },
    { code: '5434', name: 'Wettingen' },
    { code: '5435', name: 'Wettingen' },
    { code: '5436', name: 'Wettingen' },
    { code: '5437', name: 'Wettingen' },
    { code: '5438', name: 'Wettingen' },
    { code: '5439', name: 'Wettingen' },
    { code: '5442', name: 'Fislisbach' },
    { code: '5443', name: 'Niederrohrdorf' },
    { code: '5444', name: 'Oberrohrdorf' },
    { code: '5445', name: 'Niederweningen' }, // ZH
    { code: '5452', name: 'Oberrohrdorf' },
    { code: '5453', name: 'Remetschwil' },
    { code: '5454', name: 'Bellikon' },
    { code: '5462', name: 'Beinwil am See' },
    { code: '5463', name: 'Beinwil am See' },
    { code: '5464', name: 'Beinwil am See' },
    { code: '5465', name: 'Beinwil am See' },
    { code: '5466', name: 'Beinwil am See' },
    { code: '5467', name: 'Beinwil am See' },
    { code: '5468', name: 'Beinwil am See' },
    { code: '5469', name: 'Beinwil am See' },
    { code: '5472', name: 'Beinwil am See' },
    { code: '5473', name: 'Beinwil am See' },
    { code: '5474', name: 'Beinwil am See' },
    { code: '5475', name: 'Beinwil am See' },
    { code: '5476', name: 'Beinwil am See' },
    { code: '5477', name: 'Beinwil am See' },
    { code: '5478', name: 'Beinwil am See' },
    { code: '5479', name: 'Beinwil am See' },
    { code: '5500', name: 'Baden' },
    { code: '5502', name: 'Baden' },
    { code: '5503', name: 'Baden' },
    { code: '5504', name: 'Baden' },
    { code: '5505', name: 'Baden' },
    { code: '5506', name: 'Baden' },
    { code: '5507', name: 'Baden' },
    { code: '5508', name: 'Baden' },
    { code: '5509', name: 'Baden' },
    { code: '5600', name: 'Wohlen AG' },
    { code: '5602', name: 'Wohlen AG' },
    { code: '5603', name: 'Wohlen AG' },
    { code: '5604', name: 'Wohlen AG' },
    { code: '5605', name: 'Wohlen AG' },
    { code: '5606', name: 'Wohlen AG' },
    { code: '5607', name: 'Wohlen AG' },
    { code: '5608', name: 'Wohlen AG' },
    { code: '5609', name: 'Wohlen AG' },
    { code: '5610', name: 'Wohlen AG' },
    { code: '5612', name: 'Villmergen' },
    { code: '5613', name: 'Villmergen' },
    { code: '5614', name: 'Villmergen' },
    { code: '5615', name: 'Villmergen' },
    { code: '5616', name: 'Villmergen' },
    { code: '5617', name: 'Villmergen' },
    { code: '5618', name: 'Villmergen' },
    { code: '5619', name: 'Villmergen' },
    { code: '5620', name: 'Bremgarten' },
    { code: '5621', name: 'Zufikon' },
    { code: '5622', name: 'Waltenschwil' },
    { code: '5623', name: 'Boswil' },
    { code: '5624', name: 'Boswil' },
    { code: '5625', name: 'Boswil' },
    { code: '5626', name: 'Boswil' },
    { code: '5627', name: 'Boswil' },
    { code: '5628', name: 'Boswil' },
    { code: '5629', name: 'Boswil' },
    { code: '5630', name: 'Muri AG' },
    { code: '5632', name: 'Muri AG' },
    { code: '5633', name: 'Muri AG' },
    { code: '5634', name: 'Muri AG' },
    { code: '5635', name: 'Muri AG' },
    { code: '5636', name: 'Muri AG' },
    { code: '5637', name: 'Muri AG' },
    { code: '5638', name: 'Muri AG' },
    { code: '5639', name: 'Muri AG' },
    { code: '5642', name: 'Muri AG' },
    { code: '5643', name: 'Muri AG' },
    { code: '5644', name: 'Muri AG' },
    { code: '5645', name: 'Muri AG' },
    { code: '5646', name: 'Muri AG' },
    { code: '5647', name: 'Muri AG' },
    { code: '5648', name: 'Muri AG' },
    { code: '5649', name: 'Muri AG' },
    { code: '5700', name: 'Baden' },
    { code: '5702', name: 'Baden' },
    { code: '5703', name: 'Baden' },
    { code: '5704', name: 'Baden' },
    { code: '5705', name: 'Baden' },
    { code: '5706', name: 'Baden' },
    { code: '5707', name: 'Baden' },
    { code: '5708', name: 'Baden' },
    { code: '5709', name: 'Baden' },
    { code: '5712', name: 'Beinwil am See' },
    { code: '5713', name: 'Beinwil am See' },
    { code: '5714', name: 'Beinwil am See' },
    { code: '5715', name: 'Beinwil am See' },
    { code: '5716', name: 'Beinwil am See' },
    { code: '5717', name: 'Beinwil am See' },
    { code: '5718', name: 'Beinwil am See' },
    { code: '5719', name: 'Beinwil am See' },
    { code: '5722', name: 'Beinwil am See' },
    { code: '5723', name: 'Beinwil am See' },
    { code: '5724', name: 'Beinwil am See' },
    { code: '5725', name: 'Beinwil am See' },
    { code: '5726', name: 'Beinwil am See' },
    { code: '5727', name: 'Beinwil am See' },
    { code: '5728', name: 'Beinwil am See' },
    { code: '5729', name: 'Beinwil am See' },
    { code: '5734', name: 'Beinwil am See' },
    { code: '5735', name: 'Beinwil am See' },
    { code: '5736', name: 'Beinwil am See' },
    { code: '5737', name: 'Beinwil am See' },
    { code: '5738', name: 'Beinwil am See' },
    { code: '5739', name: 'Beinwil am See' },
    { code: '5750', name: 'Baden' },
    { code: '5752', name: 'Baden' },
    { code: '5753', name: 'Baden' },
    { code: '5754', name: 'Baden' },
    { code: '5755', name: 'Baden' },
    { code: '5756', name: 'Baden' },
    { code: '5757', name: 'Baden' },
    { code: '5758', name: 'Baden' },
    { code: '5759', name: 'Baden' },
    { code: '5800', name: 'Amsteg' },
    { code: '5802', name: 'Amsteg' },
    { code: '5803', name: 'Amsteg' },
    { code: '5804', name: 'Amsteg' },
    { code: '5805', name: 'Amsteg' },
    { code: '5806', name: 'Amsteg' },
    { code: '5807', name: 'Amsteg' },
    { code: '5808', name: 'Amsteg' },
    { code: '5809', name: 'Amsteg' },
  ],
}

// LIECHTENSTEIN - Códigos postales completos
const LIECHTENSTEIN_POSTAL_CODES = [
  { code: '9485', name: 'Nendeln', canton: 'LI' },
  { code: '9486', name: 'Nendeln', canton: 'LI' },
  { code: '9487', name: 'Bendern', canton: 'LI' },
  { code: '9488', name: 'Bendern', canton: 'LI' },
  { code: '9489', name: 'Bendern', canton: 'LI' },
  { code: '9490', name: 'Vaduz', canton: 'LI' },
  { code: '9491', name: 'Ruggell', canton: 'LI' },
  { code: '9492', name: 'Eschen', canton: 'LI' },
  { code: '9493', name: 'Mauren', canton: 'LI' },
  { code: '9494', name: 'Schaan', canton: 'LI' },
  { code: '9495', name: 'Triesen', canton: 'LI' },
  { code: '9496', name: 'Balzers', canton: 'LI' },
  { code: '9497', name: 'Triesenberg', canton: 'LI' },
  { code: '9498', name: 'Planken', canton: 'LI' },
  { code: '9499', name: 'Schaanwald', canton: 'LI' },
  { code: '9484', name: 'Gamprin-Bendern', canton: 'LI' },
  { code: '9483', name: 'Gamprin', canton: 'LI' },
  { code: '9482', name: 'Schellenberg', canton: 'LI' },
  { code: '9481', name: 'Schellenberg', canton: 'LI' },
  { code: '9480', name: 'Schellenberg', canton: 'LI' },
]

async function main() {
  console.log('🌱 Actualizando ciudades con códigos postales...')

  // Obtener cantones
  const cantons = await prisma.canton.findMany()
  const cantonMap = new Map(cantons.map(c => [c.code, c]))

  let updated = 0
  let created = 0

  // Actualizar/Agregar ciudades suizas
  for (const [cantonCode, cities] of Object.entries(SWISS_POSTAL_CODES)) {
    const canton = cantonMap.get(cantonCode)
    if (!canton) {
      console.log(`⚠️ Cantón ${cantonCode} no encontrado`)
      continue
    }

    for (const city of cities) {
      try {
        // Normalizar nombre para slug
        const slug = city.name.toLowerCase()
          .normalize('NFD')
          .replace(/[\u0300-\u036f]/g, '')
          .replace(/ä/g, 'a').replace(/ö/g, 'o').replace(/ü/g, 'u')
          .replace(/[^a-z0-9]+/g, '-')
          .replace(/^-|-$/g, '')

        // Agregar código de cantón al nombre si hay duplicados
        const displayName = `${city.name} (${cantonCode})`

        // Upsert ciudad
        await prisma.city.upsert({
          where: {
            slug_cantonId: {
              slug: slug,
              cantonId: canton.id
            }
          },
          update: {
            postalCode: city.code,
            name: city.name,
          },
          create: {
            name: city.name,
            slug: slug,
            postalCode: city.code,
            latitude: city.lat,
            longitude: city.lng,
            cantonId: canton.id,
          }
        })
        created++
      } catch (error) {
        console.log(`⚠️ Error con ${city.name} (${cantonCode}): ${error}`)
      }
    }
    console.log(`✅ ${cantonCode}: ${cities.length} códigos postales procesados`)
  }

  // Agregar/Actualizar Liechtenstein
  const liCanton = cantonMap.get('LI')
  if (liCanton) {
    for (const city of LIECHTENSTEIN_POSTAL_CODES) {
      const slug = city.name.toLowerCase()
        .normalize('NFD')
        .replace(/[\u0300-\u036f]/g, '')
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-|-$/g, '')

      try {
        await prisma.city.upsert({
          where: {
            slug_cantonId: {
              slug: slug,
              cantonId: liCanton.id
            }
          },
          update: {
            postalCode: city.code,
          },
          create: {
            name: city.name,
            slug: slug,
            postalCode: city.code,
            cantonId: liCanton.id,
          }
        })
        created++
      } catch (error) {
        console.log(`⚠️ Error con ${city.name} (LI): ${error}`)
      }
    }
    console.log(`✅ LI: ${LIECHTENSTEIN_POSTAL_CODES.length} códigos postales procesados`)
  }

  console.log(`\n✅ Completado! ${created} ciudades actualizadas/creadas`)
}

main()
  .catch((e) => {
    console.error('❌ Error:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
